package com.drtahir.studentkit.ui.screens

/**
 * KHYBER PAKHTUNKHWA (KP) BSN SEMESTER 2 QUESTION BANK
 * 200+ Comprehensive Questions for KMU Peshawar / PNC Syllabus
 * Subjects:
 * 1. Fundamentals of Nursing II (FON-621) - 50 Qs
 * 2. Anatomy & Physiology II (ANAT-622) - 50 Qs
 * 3. Applied Nutrition (NUT-623) - 40 Qs
 * 4. Community Health Nursing I (CHN-624) - 40 Qs
 * 5. English II - Communication Skills (ENG-625) - 30 Qs
 * Total = 210 Questions
 */
object KpSemester2QuestionBank {

    fun getQuestions(startId: Int): List<KpSemesterQuestion> {
        var idCounter = startId
        val questions = mutableListOf<KpSemesterQuestion>()

        // ==========================================
        // 1. FUNDAMENTALS OF NURSING II (FON-621) - 50 Qs
        // ==========================================
        val fon2Data = listOf(
            Triple("According to the 10 Rights of Medication Administration, which right requires verifying the patient using two identifiers?",
                listOf("Right Dose", "Right Patient", "Right Route", "Right Documentation"), 1),
            Triple("When administering oral medications to an adult patient, which position is safest to prevent aspiration?",
                listOf("Supine", "High-Fowler's or Sitting position", "Trendelenburg", "Prone"), 1),
            Triple("What angle of needle insertion is used when administering an Intramuscular (IM) injection in the ventrogluteal muscle?",
                listOf("15 degrees", "45 degrees", "90 degrees", "10 to 20 degrees"), 2),
            Triple("Subcutaneous (SC) injections (such as Insulin or Heparin) are administered at what angle?",
                listOf("15 degrees", "45 to 90 degrees", "90 degrees only", "10 degrees"), 1),
            Triple("Intradermal (ID) injections (such as Mantoux PPD test) are inserted at an angle of:",
                listOf("5 to 15 degrees with bevel up", "45 degrees", "90 degrees", "60 degrees"), 0),
            Triple("Which IM injection site is preferred in infants under 12 months of age due to muscle development?",
                listOf("Dorsogluteal muscle", "Vastus lateralis muscle (thigh)", "Deltoid muscle", "Rectus abdominis"), 1),
            Triple("What is the maximum volume of medication that should be injected into the adult deltoid muscle?",
                listOf("1 mL", "3 mL", "5 mL", "10 mL"), 0),
            Triple("When selecting a peripheral IV site, the nurse should begin site selection in:",
                listOf("Antecubital fossa first", "Most distal veins of non-dominant arm", "Subclavian vein", "Jugular vein"), 1),
            Triple("Phlebitis at a peripheral IV site is characterized by:",
                listOf("Coolness and blanching around site", "Warmth, redness (erythema), and a palpable cord along vein", "Puffiness without redness", "Systemic fever only"), 1),
            Triple("Infiltration at an IV line site is recognized by:",
                listOf("Erythema and warmth", "Coolness, edema, blanching, and leakage of fluid", "Blood backup in tubing", "Vein hardness"), 1),
            Triple("The standard drop factor for a microdrip IV administration set is:",
                listOf("10 gtt/mL", "15 gtt/mL", "20 gtt/mL", "60 gtt/mL"), 3),
            Triple("When inserting a nasogastric (NG) tube, how does the nurse estimate insertion length?",
                listOf("Tip of nose to earlobe to xiphoid process", "Forehead to sternum", "Chin to umbilicus", "Earlobe to pubic bone"), 0),
            Triple("The single most reliable bedside method to verify NG tube placement before tube feeding is:",
                listOf("Aspirating fluid and checking pH < 5", "Radiographic (X-ray) confirmation", "Auscultating air bolus over epigastrium", "Placing tube tip in water cup"), 1),
            Triple("Indwelling urinary catheter balloon inflation volume in an adult is typically inflated with:",
                listOf("Air", "10 mL of sterile water", "Sterile normal saline", "Hypertonic dextrose"), 1),
            Triple("Why should normal saline NOT be used to inflate a urinary catheter retention balloon?",
                listOf("It causes pain", "Salt crystals can crystallize and obstruct the deflation valve", "It dissolves the balloon", "It causes infection"), 1),
            Triple("To prevent Catheter-Associated Urinary Tract Infections (CAUTI), the drainage bag must be kept:",
                listOf("Above bladder level", "Below bladder level at all times", "On the bed sheets", "On the floor"), 1),
            Triple("Which enema solution draws water into the colon via osmotic pressure to stimulate peristalsis?",
                listOf("Tap water (hypotonic)", "Hypertonic saline (Fleet enema)", "Normal saline (isotonic)", "Soap suds"), 1),
            Triple("The nurse is providing wound care for a stage 3 pressure ulcer with slough. Hydrogel dressing functions primarily to:",
                listOf("Dry out wound base", "Provide moisture and encourage autolytic debridement", "Tighten wound edges", "Absorb massive hemorrhage"), 1),
            Triple("Surgical wound dehiscent is defined as:",
                listOf("Protrusion of internal organs through surgical incision", "Partial or total separation of outer surgical wound layers", "Infection with purulent drainage", "Delayed scar tissue formation"), 1),
            Triple("Evisceration occurs when internal organs protrude through an incision. Immediate nursing action is to:",
                listOf("Push organs back inside", "Cover exposed organs with sterile gauze soaked in warm sterile normal saline", "Apply tight pressure bandage", "Position patient in prone position"), 1),
            Triple("Oxygen therapy delivered via simple face mask requires a minimum flow rate of how many L/min to prevent rebreathing CO2?",
                listOf("1 to 2 L/min", "5 L/min", "10 to 15 L/min", "20 L/min"), 1),
            Triple("A Venturi mask is uniquely indicated for patients with COPD because it:",
                listOf("Delivers highest possible oxygen flow", "Delivers precise, fixed FiO2 concentration regardless of respiratory rate", "Provides humidified room air", "Heats oxygen"), 1),
            Triple("Nasopharyngeal suctioning pressure in adult patients should be set between:",
                listOf("40 - 60 mmHg", "80 - 120 mmHg", "150 - 200 mmHg", "220 - 250 mmHg"), 1),
            Triple("Tracheal suctioning should be limited to how many seconds per pass to avoid severe hypoxia?",
                listOf("5 seconds", "10 to 15 seconds", "30 seconds", "1 minute"), 1),
            Triple("When administering a soapsuds enema, the container should be held approximately how far above the anus?",
                listOf("6 inches (15 cm)", "12 to 18 inches (30 to 45 cm)", "24 inches (60 cm)", "36 inches (90 cm)"), 1),
            Triple("Which type of wound exudate is thin, clear, and watery?",
                listOf("Serous", "Purulent", "Sanguineous", "Serosanguineous"), 0),
            Triple("Which wound drainage contains both red blood cells and clear fluid, appearing pale pink?",
                listOf("Serous", "Sanguineous", "Serosanguineous", "Purulent"), 2),
            Triple("Purulent wound drainage indicates:",
                listOf("Normal healing", "Infection (containing WBCs, dead tissue, bacteria)", "Capillary bleeding", "Plasma loss"), 1),
            Triple("Hypokalemia (low potassium) manifests on ECG as:",
                listOf("Tall peaked T waves", "ST elevation", "Prominent U waves and flattened T waves", "Widened QRS complex"), 2),
            Triple("Hyperkalemia (high potassium) on ECG classically produces:",
                listOf("Inverted P waves", "Tall peaked T waves and widened QRS", "U waves", "ST depression"), 1),
            Triple("Which blood transfusion reaction occurs due to ABO blood incompatibility?",
                listOf("Acute Hemolytic Reaction", "Febrile Non-Hemolytic Reaction", "Mild Allergic Reaction", "Circulatory Overload"), 0),
            Triple("In the event of a suspected transfusion reaction, the nurse's immediate first step is to:",
                listOf("Slow the transfusion rate", "Stop the blood transfusion immediately and disconnect line", "Administer antihistamines", "Notify blood bank"), 1),
            Triple("Cold application causes localized:",
                listOf("Vasodilation", "Vasoconstriction", "Increased capillary permeability", "Muscle spasm"), 1),
            Triple("Heat application produces localized:",
                listOf("Vasoconstriction", "Vasodilation and increased tissue blood flow", "Decreased edema clearance", "Reduced cellular metabolism"), 1),
            Triple("An arterial blood gas pH of 7.25 with PaCO2 55 mmHg and HCO3 24 mEq/L represents:",
                listOf("Metabolic Acidosis", "Uncompensated Respiratory Acidosis", "Respiratory Alkalosis", "Metabolic Alkalosis"), 1),
            Triple("The most common complication of peripheral IV therapy marked by fluid overload is:",
                listOf("Hematoma", "Circulatory (Fluid) Overload", "Air Embolism", "Pneumothorax"), 1),
            Triple("Pulse oximetry accuracy is reduced in patients experiencing:",
                listOf("Fever", "Severe peripheral vasoconstriction, hypothermia, or carbon monoxide poisoning", "Hypertension", "Hyperglycemia"), 1),
            Triple("When applying anti-embolism stockings (TED hose), the nurse should remove them at least:",
                listOf("Once every 3 days", "Twice daily to assess skin and circulatory status", "Only when soiled", "Never"), 1),
            Triple("A patient in shock should be placed in which body position to augment venous return?",
                listOf("High-Fowler's", "Modified Trendelenburg (legs elevated 20 degrees)", "Prone", "Lithotomy"), 1),
            Triple("A tourniquet applied for IV blood collection should remain on the arm for no longer than:",
                listOf("30 seconds", "1 minute", "3 minutes", "5 minutes"), 1),
            Triple("Clean-catch midstream urine specimen collection instructions require the patient to:",
                listOf("Collect the first trickling stream of urine", "Clean perineum, void initial small portion, and collect middle stream into sterile cup", "Save 24 hours of urine in jug", "Collect from catheter bag"), 1),
            Triple("Which type of isolation precaution is mandatory for patients with active Pulmonary Tuberculosis?",
                listOf("Contact Precautions", "Droplet Precautions", "Airborne Precautions (N95 mask, negative pressure room)", "Standard Precautions only"), 2),
            Triple("Contact Precautions (gloves and gown) are mandatory for patients infected with:",
                listOf("Measles", "MRSA, VRE, or Clostridium difficile", "Influenza", "Chickenpox"), 1),
            Triple("Droplet Precautions require wearing a surgical mask when working within how many feet of the patient?",
                listOf("3 feet", "6 feet", "10 feet", "15 feet"), 0),
            Triple("Sharps (needles, scalpels) must be disposed of directly into:",
                listOf("Trash biohazard bag", "Puncture-resistant, hard plastic Sharps container without recapping", "Sterile tray", "Laundry bag"), 1),
            Triple("The nurse should never recap a used needle manually due to the risk of:",
                listOf("Bending needle", "Accidental needle-stick injury and bloodborne pathogen transmission", "Dulling point", "Contaminating tray"), 1),
            Triple("When performing tracheostomy care, suctioning should be preceded by:",
                listOf("Instilling tap water", "Hyperoxygenating the patient with 100% O2", "Sedating the patient", "Clamping cannula"), 1),
            Triple("Visual inspection of a normal colostomy stoma should reveal a color described as:",
                listOf("Pale pink or white", "Beefy red or dark pink and moist", "Dark purple or black", "Blue gray"), 1),
            Triple("A dark purple or black stoma indicates:",
                listOf("Normal vascularity", "Ischemia or necrosis requiring urgent surgical evaluation", "Normal healing", "Infection"), 1),
            Triple("Which electrolyte is necessary for normal blood clotting cascade and muscle contraction?",
                listOf("Sodium", "Calcium (Ca2+)", "Chloride", "Magnesium"), 1)
        )

        fon2Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 2,
                    subjectName = "Fundamentals of Nursing II",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Fundamentals of Nursing II (FON-621) core procedure/clinical concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU FON-621 / Lynn Clinical Nursing Skills"
                )
            )
        }

        // ==========================================
        // 2. ANATOMY & PHYSIOLOGY II (ANAT-622) - 50 Qs
        // ==========================================
        val anat2Data = listOf(
            Triple("The thick muscular middle layer of the heart wall responsible for contraction is the:",
                listOf("Endocardium", "Myocardium", "Epicardium", "Pericardium"), 1),
            Triple("Which heart chamber receives deoxygenated blood from the superior and inferior vena cava?",
                listOf("Left Atrium", "Right Atrium", "Right Ventricle", "Left Ventricle"), 1),
            Triple("The valve located between the right atrium and right ventricle is the:",
                listOf("Bicuspid (Mitral) valve", "Tricuspid valve", "Aortic valve", "Pulmonary valve"), 1),
            Triple("The valve located between the left atrium and left ventricle is the:",
                listOf("Tricuspid valve", "Bicuspid (Mitral) valve", "Pulmonary valve", "Eustachian valve"), 1),
            Triple("Deoxygenated blood travels from the right ventricle to the lungs via the:",
                listOf("Pulmonary veins", "Pulmonary artery (Trunk)", "Aorta", "Vena cava"), 1),
            Triple("Oxygenated blood returns from the lungs to the left atrium through four:",
                listOf("Pulmonary arteries", "Pulmonary veins", "Coronary sinuses", "Aortic arches"), 1),
            Triple("Which structure acts as the primary natural pacemaker of the heart?",
                listOf("Atrioventricular (AV) node", "Sinoatrial (SA) node", "Bundle of His", "Purkinje fibers"), 1),
            Triple("The intrinsic firing rate of the Sinoatrial (SA) node in a healthy resting heart is:",
                listOf("40 - 60 bpm", "60 - 100 bpm", "20 - 40 bpm", "100 - 120 bpm"), 1),
            Triple("On an Electrocardiogram (ECG), the P wave represents:",
                listOf("Atrial depolarization", "Ventricular depolarization", "Ventricular repolarization", "Atrial repolarization"), 0),
            Triple("The QRS complex on an ECG represents:",
                listOf("Atrial repolarization", "Ventricular depolarization", "Ventricular repolarization", "SA node impulse generation"), 1),
            Triple("The T wave on an ECG represents:",
                listOf("Atrial depolarization", "Ventricular depolarization", "Ventricular repolarization", "Purkinje firing"), 2),
            Triple("The vessel that carries oxygenated blood directly from left ventricle to systemic circulation is the:",
                listOf("Pulmonary trunk", "Aorta", "Superior vena cava", "Carotid artery"), 1),
            Triple("Which blood vessels contain valves to prevent backflow of low-pressure blood?",
                listOf("Arteries", "Arterioles", "Veins", "Capillaries"), 2),
            Triple("Microscopic vessels where exchange of gases, nutrients, and wastes occurs between blood and tissues are:",
                listOf("Venules", "Arterioles", "Capillaries", "Lymphatics"), 2),
            Triple("The throat cavity shared by both respiratory and digestive systems is the:",
                listOf("Larynx", "Pharynx", "Trachea", "Esophagus"), 1),
            Triple("The cartilaginous flap that closes over the larynx during swallowing to prevent aspiration is the:",
                listOf("Uvula", "Epiglottis", "Thyroid cartilage", "Cricoid cartilage"), 1),
            Triple("The vocal cords are situated within which respiratory structure?",
                listOf("Pharynx", "Larynx (Voice box)", "Trachea", "Bronchus"), 1),
            Triple("How many lobes does the right human lung possess?",
                listOf("2 lobes", "3 lobes", "4 lobes", "1 lobe"), 1),
            Triple("How many lobes does the left human lung possess?",
                listOf("1 lobe", "2 lobes", "3 lobes", "4 lobes"), 1),
            Triple("Which lipid-protein substance secreted by Type II alveolar cells reduces surface tension inside alveoli?",
                listOf("Mucus", "Surfactant", "Hemoglobin", "Pleural fluid"), 1),
            Triple("The primary force driving quiet expiration in a healthy individual is:",
                listOf("Active diaphragm contraction", "Passive elastic recoil of lung tissue and chest wall", "Abdominal muscle squeeze", "Intercostal muscle drive"), 1),
            Triple("Gastrointestinal wave-like muscular contractions that propel food along the digestive tract are called:",
                listOf("Segmentation", "Peristalsis", "Deglutition", "Mastication"), 1),
            Triple("Hydrochloric acid (HCl) and Intrinsic Factor are secreted in the stomach by which specialized cells?",
                listOf("Chief cells", "Parietal cells", "G cells", "Goblet cells"), 1),
            Triple("Pepsinogen, an inactive enzyme precursor for protein digestion, is secreted by gastric:",
                listOf("Parietal cells", "Chief cells", "Mucous neck cells", "Enteroendocrine cells"), 1),
            Triple("Which organ produces bile for fat emulsification?",
                listOf("Gallbladder", "Liver", "Pancreas", "Duodenum"), 1),
            Triple("Bile produced in the liver is stored and concentrated in the:",
                listOf("Pancreas", "Gallbladder", "Spleen", "Duodenum"), 1),
            Triple("Which hormone released by the duodenum stimulates gallbladder contraction and pancreatic enzyme release?",
                listOf("Gastrin", "Cholecystokinin (CCK)", "Secretin", "Ghrelin"), 1),
            Triple("The first and shortest segment of the small intestine receiving stomach chyme, bile, and pancreatic juice is the:",
                listOf("Jejunum", "Ileum", "Duodenum", "Cecum"), 2),
            Triple("Intrinsic factor secreted by gastric parietal cells is essential for absorbing which vitamin in the terminal ileum?",
                listOf("Vitamin A", "Vitamin B12 (Cobalamin)", "Vitamin C", "Vitamin D"), 1),
            Triple("The pouch-like initial segment of the large intestine bearing the vermiform appendix is the:",
                listOf("Colon", "Cecum", "Rectum", "Sigmoid"), 1),
            Triple("The functional unit of the human kidney responsible for blood filtration and urine formation is the:",
                listOf("Neuron", "Nephron", "Glomerulus", "Calyx"), 1),
            Triple("The tuft of capillaries where blood filtration originates inside Bowman's capsule is the:",
                listOf("Glomerulus", "Peritubular network", "Vasa recta", "Juxtaglomerular apparatus"), 0),
            Triple("Glomerular Filtration Rate (GFR) in a healthy young adult is approximately:",
                listOf("50 mL/min", "125 mL/min (approx. 180 L/day)", "250 mL/min", "500 mL/min"), 1),
            Triple("Aldosterone hormone acts on distal convoluted tubules and collecting ducts to promote:",
                listOf("Sodium reabsorption and potassium excretion", "Sodium excretion and potassium reabsorption", "Water excretion", "Calcium loss"), 0),
            Triple("Antidiuretic Hormone (ADH / Vasopressin) increases water reabsorption by inserting aquaporin channels into:",
                listOf("Proximal convoluted tubule", "Collecting ducts", "Loop of Henle", "Glomerulus"), 1),
            Triple("Which enzyme produced by juxtaglomerular renal cells converts angiotensinogen to angiotensin I in response to low BP?",
                listOf("Renin", "Erythropoietin", "ACE", "Aldosterone"), 0),
            Triple("Erythropoietin (EPO), which stimulates red blood cell production in bone marrow, is synthesized primarily by the:",
                listOf("Liver", "Kidneys", "Spleen", "Adrenal cortex"), 1),
            Triple("The tubes that transport urine from kidney renal pelvis to urinary bladder are the:",
                listOf("Urethra", "Ureters", "Efferent ducts", "Collecting tubules"), 1),
            Triple("Which hormone secreted by the anterior pituitary stimulates thyroid gland hormone production (T3/T4)?",
                listOf("ACTH", "Thyroid-Stimulating Hormone (TSH)", "FSH", "LH"), 1),
            Triple("Calcitonin hormone produced by thyroid parafollicular cells functions to:",
                listOf("Raise blood calcium", "Lower blood calcium level by depositing calcium into bone", "Stimulate vitamin D activation", "Decrease bone density"), 1),
            Triple("Parathyroid Hormone (PTH) increases blood calcium levels by:",
                listOf("Stimulating osteoclast bone resorption and renal calcium reabsorption", "Inhibiting osteoclasts", "Promoting urinary calcium loss", "Inhibiting vitamin D"), 0),
            Triple("Which adrenal cortex zone secretes glucocorticoids (primarily Cortisol)?",
                listOf("Zona glomerulosa", "Zona fasciculata", "Zona reticularis", "Adrenal medulla"), 1),
            Triple("The adrenal medulla secretes catecholamine stress hormones named:",
                listOf("Cortisol and Aldosterone", "Epinephrine (Adrenaline) and Norepinephrine", "Insulin and Glucagon", "Estrogen and Progesterone"), 1),
            Triple("Spermatogenesis occurs in which testicular structures?",
                listOf("Epididymis", "Seminiferous tubules", "Vas deferens", "Prostate gland"), 1),
            Triple("Which pituitary hormone triggers ovulation and corpus luteum formation in the female ovarian cycle?",
                listOf("Follicle-Stimulating Hormone (FSH)", "Luteinizing Hormone (LH)", "Prolactin", "Oxytocin"), 1),
            Triple("Fertilization of the human ovum by sperm normally occurs in which segment of the Fallopian tube?",
                listOf("Uterine cavity", "Ampulla of Fallopian (Uterine) tube", "Ovary", "Cervix"), 1),
            Triple("Implantation of the blastocyst normally occurs in the inner lining of the uterus called the:",
                listOf("Myometrium", "Endometrium", "Perimetrium", "Cervix"), 1),
            Triple("Which hormone produced by the syncytiotrophoblast maintains the corpus luteum during early pregnancy and is detected in pregnancy tests?",
                listOf("Human Chorionic Gonadotropin (hCG)", "Progesterone", "Estrogen", "Human Placental Lactogen"), 0),
            Triple("The sensory receptor organ for hearing situated within the cochlea is the:",
                listOf("Organ of Corti", "Vestibule", "Semicircular canals", "Tympanic membrane"), 0),
            Triple("The light-sensitive inner neural layer of the eye containing photoreceptor rods and cones is the:",
                listOf("Sclera", "Choroid", "Retina", "Cornea"), 2)
        )

        anat2Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 2,
                    subjectName = "Anatomy & Physiology II",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Anatomy & Physiology II (ANAT-622) core organ systems concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU ANAT-622 / Guyton & Hall Textbook of Medical Physiology"
                )
            )
        }

        // ==========================================
        // 3. APPLIED NUTRITION (NUT-623) - 40 Qs
        // ==========================================
        val nut1Data = listOf(
            Triple("Which energy yield value corresponds to one gram of dietary Carbohydrate or Protein?",
                listOf("2 kcal", "4 kcal", "7 kcal", "9 kcal"), 1),
            Triple("How many kilocalories (kcal) of energy are produced by metabolizing one gram of dietary Fat?",
                listOf("4 kcal", "7 kcal", "9 kcal", "12 kcal"), 2),
            Triple("Which macronutrient is the primary structural building block for body tissues and enzymes?",
                listOf("Carbohydrate", "Lipid", "Protein", "Dietary Fiber"), 2),
            Triple("The Recommended Dietary Allowance (RDA) for daily protein intake in a healthy adult is approximately:",
                listOf("0.4 g/kg body weight", "0.8 g/kg body weight", "2.0 g/kg body weight", "3.5 g/kg body weight"), 1),
            Triple("Kwashiorkor is a form of severe protein-energy malnutrition characterized by:",
                listOf("Severe muscle wasting without edema", "Generalized edema, fatty liver, and moon face due to protein deficiency", "Vitamin C deficiency", "High blood sugar"), 1),
            Triple("Marasmus is characterized by severe caloric deprivation causing:",
                listOf("Generalized edema", "Severe wasting of muscle and fat ('skin and bones' appearance) without edema", "Fatty liver", "Bleeding gums"), 1),
            Triple("Which type of dietary fiber is non-digestible, adds bulk to stool, and prevents constipation?",
                listOf("Insoluble Fiber (e.g., cellulose, bran)", "Soluble Fiber", "Saturated Fat", "Refined Starch"), 0),
            Triple("Soluble dietary fiber (e.g., pectin, oats) helps reduce blood cholesterol and glucose by:",
                listOf("Binding bile acids and slowing carbohydrate absorption", "Increasing gastric emptying speed", "Converting to fat", "Destroying insulin"), 0),
            Triple("Which fatty acids contain double bonds and are liquid at room temperature (e.g. olive oil, fish oil)?",
                listOf("Saturated Fatty Acids", "Unsaturated Fatty Acids (MUFAs & PUFAs)", "Trans Fatty Acids", "Cholesterol"), 1),
            Triple("Essential fatty acids that cannot be synthesized by human body include Linoleic acid (Omega-6) and:",
                listOf("Palmitic acid", "Alpha-Linolenic acid (Omega-3)", "Stearic acid", "Oleic acid"), 1),
            Triple("Which water-soluble vitamin is required for neural tube defect (spina bifida) prevention during early pregnancy?",
                listOf("Vitamin C", "Folic Acid (Vitamin B9)", "Vitamin B12", "Niacin"), 1),
            Triple("Pernicious anemia is caused by deficiency of Vitamin B12 secondary to lack of gastric:",
                listOf("Hydrochloric acid", "Intrinsic Factor", "Pepsin", "Gastrin"), 1),
            Triple("Which mineral is essential for thyroid hormone synthesis (T3 and T4)?",
                listOf("Iron", "Iodine", "Zinc", "Fluoride"), 1),
            Triple("Iodine deficiency in adults leads to thyroid enlargement known as:",
                listOf("Cushing's syndrome", "Goiter", "Acromegaly", "Tetany"), 1),
            Triple("Iron deficiency anemia is characterized microcytically on peripheral blood smear as:",
                listOf("Macrocytic normochromic", "Microcytic hypochromic RBCs", "Normocytic normochromic", "Sickle-shaped"), 1),
            Triple("Which dietary vitamin dramatically enhances non-heme iron absorption in the gut?",
                listOf("Vitamin A", "Vitamin C (Ascorbic Acid)", "Vitamin D", "Vitamin K"), 1),
            Triple("Vitamin D facilitates calcium absorption in the gut. Severe adult deficiency causes soft bones termed:",
                listOf("Rickets", "Osteomalacia", "Osteoarthritis", "Gout"), 1),
            Triple("A patient with hypertension should follow a DASH diet restricting daily sodium intake to under:",
                listOf("1,500 - 2,300 mg per day", "5,000 mg per day", "10,000 mg per day", "500 mg per day"), 0),
            Triple("Patients with severe Chronic Kidney Disease (CKD) on hemodialysis require dietary restriction of:",
                listOf("Water-soluble vitamins", "Potassium, Phosphorus, Sodium, and Fluid", "Calcium and iron", "Fiber"), 1),
            Triple("A diabetic diet emphasizes foods with a low Glycemic Index (GI), which means:",
                listOf("Foods cause a slow, gradual rise in blood glucose", "Foods cause rapid spikes in blood glucose", "Foods contain zero calories", "Foods are rich in sucrose"), 0),
            Triple("Body Mass Index (BMI) is calculated as weight in kilograms divided by:",
                listOf("Height in meters", "Height in meters squared (m²)", "Height in inches", "Age in years"), 1),
            Triple("According to WHO criteria, a BMI range of 25.0 to 29.9 kg/m² indicates:",
                listOf("Underweight", "Normal weight", "Overweight", "Obesity Class I"), 2),
            Triple("A BMI equal to or greater than 30.0 kg/m² defines:",
                listOf("Underweight", "Normal", "Overweight", "Obesity"), 3),
            Triple("In total parenteral nutrition (TPN) central line infusions, rapid cessation can precipitate severe:",
                listOf("Hyperglycemia", "Hypoglycemia", "Hyperkalemia", "Hypercalcemia"), 1),
            Triple("Enteral tube feeding bolus administration should be preceded by checking gastric residual volume (GRV). A GRV > 250-500 mL indicates:",
                listOf("Rapid digestion", "Delayed gastric emptying (hold feed and notify provider)", "Normal absorption", "Dehydration"), 1),
            Triple("To prevent tube feeding aspiration pneumonia, the head of bed during and 1 hour after feeding should be kept elevated at least:",
                listOf("10 degrees", "30 to 45 degrees", "90 degrees", "0 degrees (flat)"), 1),
            Triple("Celiac disease is an autoimmune enteropathy triggered by ingestion of gluten present in:",
                listOf("Rice and Corn", "Wheat, Barley, and Rye", "Soy and Peanut", "Milk and Eggs"), 1),
            Triple("Gouty arthritis is characterized by elevated serum uric acid levels. Patients should avoid purine-rich foods such as:",
                listOf("Fresh apples", "Organ meats (liver, kidney), sardines, and red wine", "Skim milk", "White rice"), 1),
            Triple("Which mineral works with calcium to maintain bone density and neuromuscular function?",
                listOf("Iron", "Magnesium", "Copper", "Selenium"), 1),
            Triple("Which mineral is crucial for wound healing, immune response, and taste perception (gustation)?",
                listOf("Zinc", "Iodine", "Fluoride", "Chromium"), 0),
            Triple("Dietary iron exists in two forms: Heme iron (found in meat) and Non-Heme iron (found in plants). Heme iron is:",
                listOf("Less absorbed than non-heme", "More readily absorbed by human intestinal mucosa", "Insoluble", "Excreted completely"), 1),
            Triple("A client receiving loop diuretic therapy (Furosemide) should consume potassium-rich foods such as:",
                listOf("Apples and white bread", "Bananas, oranges, potatoes, and spinach", "Cheese and butter", "White rice"), 1),
            Triple("Dietary fat digestion requires bile acids for emulsification and pancreatic lipase to form absorbable:",
                listOf("Monoglycerides and Free Fatty Acids", "Amino acids", "Monosaccharides", "Peptides"), 0),
            Triple("Which vitamin acts as a powerful fat-soluble antioxidant protecting cell membranes from lipid peroxidation?",
                listOf("Vitamin A", "Vitamin E (Tocopherol)", "Vitamin K", "Vitamin B6"), 1),
            Triple("Trans-fatty acids generated during industrial hydrogenation of vegetable oils raise:",
                listOf("HDL cholesterol", "LDL cholesterol while lowering HDL cholesterol", "Triglycerides only", "Blood glucose"), 1),
            Triple("Exclusive breastfeeding is recommended by WHO/UNICEF for infants during the first:",
                listOf("2 months of life", "6 months of life", "12 months of life", "24 months of life"), 1),
            Triple("Colostrum, the early breast milk produced in first few days postpartum, is rich in:",
                listOf("Fat and lactose", "Secretory IgA antibodies and protective factors", "Vitamin D", "Iron only"), 1),
            Triple("Introduction of complementary solid foods (weaning) should begin at age:",
                listOf("2 months", "4 months", "6 months", "12 months"), 2),
            Triple("Which condition is caused by severe thiamine (Vitamin B1) deficiency associated with chronic alcoholism?",
                listOf("Korsakoff Psychosis / Wernicke Encephalopathy", "Scurvy", "Rickets", "Pellagra"), 0),
            Triple("The principal extracellular fluid buffer system maintaining blood pH balance consists of:",
                listOf("Phosphate buffer", "Carbonic acid - Bicarbonate buffer system (H2CO3 / HCO3-)", "Protein buffer", "Hemoglobin buffer"), 1)
        )

        nut1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 2,
                    subjectName = "Applied Nutrition",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Applied Nutrition (NUT-623) key concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU NUT-623 / Krause's Food & the Nutrition Care Process"
                )
            )
        }

        // ==========================================
        // 4. COMMUNITY HEALTH NURSING I (CHN-624) - 40 Qs
        // ==========================================
        val chn1Data = listOf(
            Triple("The Alma-Ata Declaration of 1978 defined Primary Health Care (PHC) with the global goal of:",
                listOf("Free hospital care for all", "Health for All by the Year 2000", "Eradication of all bacteria", "Specialized ICU units"), 1),
            Triple("Primary level of prevention aims to:",
                listOf("Diagnose disease early", "Prevent disease or injury before it occurs (e.g. immunization, health education)", "Rehabilitate post-stroke patients", "Provide surgical treatment"), 1),
            Triple("Secondary level of prevention focuses on:",
                listOf("Health promotion", "Early diagnosis and prompt treatment (e.g., mammogram screening, Pap smear)", "Rehabilitation and disability limitation", "Immunization"), 1),
            Triple("Tertiary level of prevention aims to:",
                listOf("Stop disease onset", "Rehabilitate and minimize long-term disability (e.g., physical therapy post-amputation)", "Screen healthy populations", "Provide clean water"), 1),
            Triple("The Epidemiological Triad model of disease causation consists of:",
                listOf("Host, Agent, and Environment", "Doctor, Nurse, and Patient", "Bacteria, Virus, and Fungus", "Time, Place, and Person"), 0),
            Triple("Under the Expanded Programme on Immunization (EPI) schedule in Pakistan, the Pentavalent vaccine protects against 5 diseases including Diphtheria, Tetanus, Pertussis, Hepatitis B, and:",
                listOf("Tuberculosis", "Haemophilus influenzae type b (Hib)", "Measles", "Polio"), 1),
            Triple("In Pakistan's EPI schedule, how many doses of Pentavalent vaccine are administered to infants?",
                listOf("1 dose", "3 doses (at 6, 10, and 14 weeks)", "5 doses", "2 doses"), 1),
            Triple("The Measles vaccine in Pakistan's EPI schedule is administered at ages:",
                listOf("Birth and 6 weeks", "9 months and 15 months", "12 months and 2 years", "6 weeks and 10 weeks"), 1),
            Triple("Cold chain maintenance temperature for storing vaccines at health centers is between:",
                listOf("-20°C to -50°C", "+2°C to +8°C", "+15°C to +25°C", "0°C exactly"), 1),
            Triple("Vector-borne transmission of malaria occurs via:",
                listOf("Houseflies", "Anopheles mosquito bite", "Direct contact", "Contaminated food"), 1),
            Triple("Water purification method suitable for emergency household use in rural KP involves boiling water for at least:",
                listOf("30 seconds", "1 to 3 minutes at rolling boil", "10 seconds", "30 minutes"), 1),
            Triple("Incubation period of an infectious disease is defined as the time interval between:",
                listOf("Onset of symptoms and recovery", "Exposure to infectious agent and first appearance of signs/symptoms", "Diagnosis and treatment", "Birth and infection"), 1),
            Triple("Endemic disease refers to:",
                listOf("Sudden unexpected outbreak worldwide", "Constant presence or habitual prevalence of a disease in a given geographic area", "Complete absence of disease", "Animal disease outbreak"), 1),
            Triple("Epidemic disease refers to:",
                listOf("Normal expected cases in a city", "Occurrence of cases in a region clearly in excess of normal expectancy", "Worldwide pandemic", "Genetic disorder"), 1),
            Triple("Pandemic disease is defined as an epidemic that:",
                listOf("Occurs in a single village", "Spreads across multiple countries or continents affecting large populations", "Affects only animals", "Is confined to hospitals"), 1),
            Triple("The main cause of maternal mortality in developing countries including Pakistan is:",
                listOf("Obstetric Hemorrhage (PPH)", "Eclampsia", "Sepsis", "Unsafe abortion"), 0),
            Triple("Infant Mortality Rate (IMR) measures the number of infant deaths under 1 year of age per:",
                listOf("100 live births", "1,000 live births", "10,000 live births", "100,000 live births"), 1),
            Triple("Maternal Mortality Ratio (MMR) is calculated per how many live births?",
                listOf("1,000 live births", "10,000 live births", "100,000 live births", "1,000,000 live births"), 2),
            Triple("Lady Health Workers (LHWs) in Pakistan primarily provide community-based primary care including:",
                listOf("Major surgical operations", "Maternal and child health care, family planning, and immunization support", "ICU ventilator care", "Radiology scans"), 1),
            Triple("Which method of sewage disposal is most common in non-sewered rural household settings?",
                listOf("Activated sludge plant", "Pit latrine / Septic tank", "Incineration", "Open dumping"), 1),
            Triple("Chlorination of drinking water destroys bacteria. Residual free chlorine level in treated drinking water should be:",
                listOf("0.01 mg/L", "0.2 to 0.5 mg/L (ppm)", "5.0 mg/L", "10 mg/L"), 1),
            Triple("Fecal-oral transmitted hepatitis viral strains include:",
                listOf("Hepatitis B and C", "Hepatitis A and E", "Hepatitis D and B", "Hepatitis C and G"), 1),
            Triple("Poliomyelitis virus targets which nervous system cells leading to flaccid paralysis?",
                listOf("Cerebral cortex neurons", "Anterior horn motor neurons of spinal cord", "Sensory ganglion cells", "Schwann cells"), 1),
            Triple("Oral Polio Vaccine (OPV) contains:",
                listOf("Killed inactivated virus", "Live attenuated poliovirus strains", "Recombinant protein", "Toxoid"), 1),
            Triple("Inactivated Polio Vaccine (IPV) is administered via which route in Pakistan's EPI?",
                listOf("Oral drops", "Intramuscular or Subcutaneous injection", "Intradermal scratch", "Nasal spray"), 1),
            Triple("Which component of primary health care ensures access to safe drinking water and basic sanitation?",
                listOf("EPI immunization", "Environmental sanitation", "Maternal child care", "Essential drug supply"), 1),
            Triple("In demography, the Dependency Ratio compares dependent populations (<15 and >65 years) to the:",
                listOf("Total population", "Working-age population (15 to 64 years)", "Infant population", "Female population"), 1),
            Triple("Demographic Transition Model Phase 2 (High Expanding) is characterized by:",
                listOf("High birth rate and rapidly falling death rate due to healthcare improvements", "High birth and high death rate", "Low birth and low death rate", "Declining population"), 0),
            Triple("Which occupational lung disease is caused by prolonged inhalation of silica dust in mining/stonecutting?",
                listOf("Asbestosis", "Silicosis", "Byssinosis", "Coal worker pneumoconiosis"), 1),
            Triple("Byssinosis is an occupational respiratory disease seen in workers in which industry?",
                listOf("Coal mining", "Cotton textile industry", "Asbestos manufacturing", "Grain silos"), 1),
            Triple("Screening tests should possess high Sensitivity, which means the test correctly identifies:",
                listOf("People without the disease", "People who actually have the disease (True Positive rate)", "False negatives", "Lab errors"), 1),
            Triple("Specificity of a screening test measures the test's ability to correctly identify:",
                listOf("People who do NOT have the disease (True Negative rate)", "Diseased individuals", "Early stages", "Incurable cases"), 0),
            Triple("Herd immunity threshold for highly contagious airborne diseases like Measles requires population coverage of approximately:",
                listOf("50%", "70%", "92% to 95%", "100%"), 2),
            Triple("Which disease is transmitted through urine of infected animals contaminating water (Leptospirosis)?",
                listOf("Typhoid", "Leptospira interrogans", "Brucellosis", "Anthrax"), 1),
            Triple("Salmonella typhi causes Typhoid Fever. The gold standard diagnostic blood culture is most yieldful during week:",
                listOf("Week 1 of illness", "Week 4 of illness", "Convalescence", "After 2 months"), 0),
            Triple("Widal test for Typhoid fever detects antibodies against which bacterial antigens?",
                listOf("Vi and Capsular", "O (Somatic) and H (Flagellar) antigens", "LPS and Exotoxin", "Protein A"), 1),
            Triple("The recommended treatment for dehydration secondary to acute watery diarrhea in community settings is:",
                listOf("IV Normal Saline bolus only", "Oral Rehydration Salts (ORS) solution and Zinc supplementation", "Prophylactic antibiotics", "Antidiarrheal loperamide"), 1),
            Triple("Zinc supplementation in pediatric acute diarrhea reduces duration and severity. Daily recommended dose for infants > 6 months is:",
                listOf("5 mg for 5 days", "20 mg daily for 10 to 14 days", "50 mg once", "100 mg daily"), 1),
            Triple("Air pollution primary indoor health hazard in rural KP households stems from:",
                listOf("Tobacco smoke only", "Unvented biomass fuel combustion (wood, dung) for cooking/heating", "Kerosene lamps", "Industrial smog"), 1),
            Triple("Which national health insurance initiative in Khyber Pakhtunkhwa provides free inpatient hospital treatment to families?",
                listOf("BISP", "Sehat Sahulat Program / Sehat Card Plus", "EPI Program", "Prime Minister Health Initiative"), 1)
        )

        chn1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 2,
                    subjectName = "Community Health Nursing I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Community Health Nursing I (CHN-624) core public health concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU CHN-624 / Park's Textbook of Preventive and Social Medicine"
                )
            )
        }

        // ==========================================
        // 5. ENGLISH II - COMMUNICATION SKILLS (ENG-625) - 30 Qs
        // ==========================================
        val eng2Data = listOf(
            Triple("Therapeutic communication technique where the nurse repeats the patient's main statement to encourage elaboration is:",
                listOf("Restating / Reflection", "Changing the subject", "Offering false reassurance", "Asking closed questions"), 0),
            Triple("Which barrier to therapeutic communication blocks patient self-expression by minimizing their feelings?",
                listOf("Active listening", "Offering false reassurance ('Don't worry, everything will be fine')", "Using open-ended questions", "Clarifying"), 1),
            Triple("SBAR handover tool used in clinical communication stands for:",
                listOf("Situation, Background, Assessment, Recommendation", "System, Body, Action, Response", "Subjective, Bedside, Analysis, Record", "Symptoms, Blood pressure, Airway, Resuscitation"), 0),
            Triple("When communicating with an anxious patient, non-verbal cues such as maintaining open posture and eye contact communicate:",
                listOf("Aggression", "Empathy, attentiveness, and active interest", "Indifference", "Authority"), 1),
            Triple("Which question type encourages the patient to share detailed narrative information?",
                listOf("Closed-ended question ('Do you have pain?')", "Open-ended question ('Can you describe what your pain feels like?')", "Leading question", "Multiple choice question"), 1),
            Triple("Closed-ended questions in clinical history taking are best utilized to obtain:",
                listOf("Complex emotional feelings", "Specific direct facts quickly (e.g. 'What is your date of birth?')", "Patient's life history", "Philosophical views"), 1),
            Triple("Active listening requires the nurse to:",
                listOf("Interrupt to correct patient errors", "Focus fully on patient's verbal and non-verbal communication without judgment", "Plan next response while patient speaks", "Look at watch continuously"), 1),
            Triple("In non-verbal communication, 'Proxemics' refers to the study of:",
                listOf("Body gestures", "Personal spatial distance during interaction", "Tone of voice", "Eye movements"), 1),
            Triple("The personal space zone during a nurse-patient assessment interview is generally:",
                listOf("0 to 1.5 feet (Intimate zone)", "1.5 to 4 feet (Personal zone)", "4 to 12 feet (Social zone)", "> 12 feet (Public zone)"), 1),
            Triple("In healthcare communication, 'Empathy' is defined as:",
                listOf("Feeling sorry for the patient", "Understanding and sharing the emotional state of another without losing objectivity", "Ignoring emotions", "Giving advice"), 1),
            Triple("How does 'Sympathy' differ from 'Empathy'?",
                listOf("Sympathy involves sharing objective clinical facts", "Sympathy involves pity or feeling sorry for someone, losing professional objectivity", "Empathy is unprofessional", "They are identical"), 1),
            Triple("When communicating with a hearing-impaired adult patient, the nurse should:",
                listOf("Shout loudly in patient's ear", "Face the patient directly, speak clearly at a normal tone, and reduce background noise", "Use complex medical jargon", "Avoid eye contact"), 1),
            Triple("When delivering unfavorable medical news to a patient or family, the recommended framework is:",
                listOf("SBAR protocol", "SPIKES protocol (Setting, Perception, Invitation, Knowledge, Empathy, Strategy)", "SOAP note format", "ADPIE model"), 1),
            Triple("Paralanguage in non-verbal communication includes:",
                listOf("Written documentation", "Tone, pitch, volume, and speed of voice", "Hand gestures", "Physical stance"), 1),
            Triple("A nurse documenting patient progress using the SOAP format organizes notes into:",
                listOf("Situation, Observation, Action, Plan", "Subjective, Objective, Assessment, Plan", "Symptoms, Operative, Analysis, Pain", "Schedule, Order, Advice, Prescription"), 1),
            Triple("When giving an oral clinical presentation during morning ward rounds, the nurse should present concise information in logical order starting with:",
                listOf("Patient's home address", "Patient demographic, chief complaint, current clinical status, and care plan", "Bed making procedure", "Discharge summary"), 1),
            Triple("Feedback in the communication process serves to:",
                listOf("End interaction immediately", "Confirm that the intended message was correctly received and understood by decoder", "Distort message", "Increase anxiety"), 1),
            Triple("Which element of communication encodes the message?",
                listOf("Decoder", "Sender (Encoder)", "Channel", "Receiver"), 1),
            Triple("Noise in communication channels refers to:",
                listOf("Loud sounds only", "Any physical, physiological, or psychological barrier that distorts message transmission", "Written text", "Patient feedback"), 1),
            Triple("Which non-verbal behavior demonstrates active listening?",
                listOf("Crossing arms tightly", "Leaning slightly forward towards patient and nodding appropriately", "Checking phone notifications", "Looking away"), 1),
            Triple("The therapeutic communication technique of 'Silence' allows the patient to:",
                listOf("Feel ignored", "Process thoughts, reflect on feelings, and gather thoughts without rush", "Fall asleep", "End interview"), 1),
            Triple("Clarifying technique involves asking:",
                listOf("'Are you sure you aren't lying?'", "'Could you explain what you meant when you said you felt hopeless?'", "'Why did you do that?'", "'You shouldn't feel that way.'"), 1),
            Triple("An assertive communication style is characterized by:",
                listOf("Demanding control aggressively", "Expressing thoughts, needs, and feelings honestly and directly while respecting others", "Passive compliance", "Manipulation"), 1),
            Triple("Assertive communication differs from aggressive communication because aggressive communication:",
                listOf("Violates rights of others and uses intimidation or blaming", "Is quiet", "Promotes equality", "Uses open body language"), 0),
            Triple("In cross-cultural communication in KP healthcare, the nurse must remain sensitive to Pashto cultural norms regarding:",
                listOf("Language, modesty, gender dynamics, and family decision-making involvement", "Dietary preferences only", "Clothing colors", "Hospital furniture"), 0),
            Triple("When an interpreter is required for a non-English/Pashto speaking patient, the nurse should communicate by looking at:",
                listOf("The interpreter", "The patient directly while speaking", "The floor", "The medical record"), 1),
            Triple("Using medical jargon ('dyspnea', 'prandial', 'myocardial infarction') when speaking to patients creates:",
                listOf("Enhanced clarity", "A semantic communication barrier leading to confusion and misunderstanding", "Therapeutic rapport", "Trust"), 1),
            Triple("The 'Teach-Back' method in patient education evaluates understanding by:",
                listOf("Asking patient 'Do you understand?'", "Asking patient to explain back in their own words what was taught", "Giving a written exam", "Asking family"), 1),
            Triple("When a patient expresses anger regarding delayed care, the nurse's best response is:",
                listOf("Argue back defensively", "Acknowledge the patient's feelings empathetically and address the concern calmly", "Ignore the patient", "Call security immediately"), 1),
            Triple("In written nursing communication, progress notes must be documented:",
                listOf("At end of week", "Accurately, objectively, legibly, and contemporaneously (at time of occurrence)", "In pencil", "With opinionated comments"), 1)
        )

        eng2Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 2,
                    subjectName = "English II (Communication Skills)",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "English II (ENG-625) clinical communication & interpersonal skills. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU ENG-625 / Therapeutic Communication in Nursing"
                )
            )
        }

        // Add 100 extra questions for EACH subject in Semester 2 (500 extra questions)
        questions.addAll(KpSemester2PlusQuestionBank.getQuestions(idCounter))

        return questions
    }
}
