package com.example.ui.screens

/**
 * KHYBER PAKHTUNKHWA (KP) BSN SEMESTER 3 QUESTION BANK
 * 200+ Comprehensive Questions for KMU Peshawar / PNC Syllabus
 * Subjects:
 * 1. Adult Health Nursing I (Med-Surg I) (AHN-631) - 50 Qs
 * 2. Pathophysiology I (PAT-632) - 40 Qs
 * 3. Pharmacology I (PHA-633) - 50 Qs
 * 4. Health Assessment I (HAS-634) - 40 Qs
 * 5. Islamic Studies / Ethics (ISL-635) - 30 Qs
 * Total = 210 Questions
 */
object KpSemester3QuestionBank {

    fun getQuestions(startId: Int): List<KpSemesterQuestion> {
        var idCounter = startId
        val questions = mutableListOf<KpSemesterQuestion>()

        // ==========================================
        // 1. ADULT HEALTH NURSING I (MED-SURG I) (AHN-631) - 50 Qs
        // ==========================================
        val ahn1Data = listOf(
            Triple("A patient presenting with acute crushing retrosternal chest pain radiating to left arm and jaw is suspected of having Acute Myocardial Infarction. The MONA protocol acronym stands for:",
                listOf("Morphine, Oxygen, Nitroglycerin, Aspirin", "Metroprolol, Omeprazole, Nifedipine, Aspirin", "Morphine, Ondansetron, Nitroprusside, Adenosine", "Milrinone, Oxygen, Norepinephrine, Atropine"), 0),
            Triple("Which cardiac serum biomarker is most specific and sensitive for diagnosing acute myocardial infarction within 3 to 4 hours of onset?",
                listOf("Creatine Kinase MB (CK-MB)", "Cardiac Troponin I / T", "Myoglobin", "Lactate Dehydrogenase (LDH)"), 1),
            Triple("A client with chronic heart failure experiences nocturnal dyspnea and orthopnea. These manifestations reflect failure of which ventricle?",
                listOf("Right Ventricle", "Left Ventricle", "Right Atrium", "Interventricular Septum"), 1),
            Triple("Right-sided heart failure causes systemic venous congestion manifesting as:",
                listOf("Pulmonary edema and crackles", "Jugular Vein Distension (JVD), peripheral edema, and hepatomegaly", "Hemoptysis", "Pleural effusion only"), 1),
            Triple("Essential Hypertension is defined as persistent blood pressure readings equal to or exceeding:",
                listOf("120/80 mmHg", "130/80 mmHg (Stage 1) or 140/90 mmHg (Stage 2)", "110/70 mmHg", "160/100 mmHg only"), 1),
            Triple("A patient with COPD presents with chronic hypoxemia, barrel chest, and clubbing of fingers. The primary drive for respiration in severe chronic COPD is:",
                listOf("Elevated PaCO2 (Hypercapnia)", "Decreased PaO2 (Hypoxic drive)", "Elevated arterial pH", "Serum bicarbonate level"), 1),
            Triple("High-flow oxygen administration in a severe COPD patient with chronic hypercapnia must be cautious because it may:",
                listOf("Cause hyperventilation", "Depress the patient's hypoxic respiratory drive leading to respiratory arrest", "Cause pulmonary embolism", "Trigger asthma"), 1),
            Triple("Asthma attack is characterized pathophysiologically by bronchospasm, mucosal edema, and hypersecretion. Auscultation reveals:",
                listOf("Bilateral coarse crackles", "High-pitched expiratory wheezing", "Pleural friction rub", "Stridor only"), 1),
            Triple("Acute pulmonary embolism classically presents with sudden onset of:",
                listOf("Gradual fever and cough", "Sudden dyspnea, pleuritic chest pain, tachypnea, and hypoxia", "Haematuria", "Epistaxis"), 1),
            Triple("Tuberculosis (TB) patient undergoing treatment requires combination Anti-TB Therapy (RIPE). The RIPE acronym includes:",
                listOf("Rifampicin, Isoniazid, Pyrazinamide, Ethambutol", "Ribavirin, Insulin, Penicillin, Erythromycin", "Ranitidine, Ibuprofen, Paracetamol, Empart", "Aspirin, Metformin, Atorvastatin, Omeprazole"), 0),
            Triple("A patient on Isoniazid (INH) therapy is prescribed Pyridoxine (Vitamin B6) concurrently to prevent:",
                listOf("Hepatotoxicity", "Peripheral Neuropathy", "Optic Neuritis", "Hyperuricemia"), 1),
            Triple("Rifampicin medication education must inform the patient that bodily secretions (urine, sweat, tears) may turn:",
                listOf("Bright green", "Red-orange color (harmless side effect)", "Dark black", "Milky white"), 1),
            Triple("Ethambutol toxicity manifests primarily as visual disturbances due to:",
                listOf("Cataracts", "Optic Neuritis (decreased visual acuity and red-green color blindness)", "Glaucoma", "Retinal detachment"), 1),
            Triple("Peptic Ulcer Disease (PUD) duodenal ulcer pain typically presents as epigastric pain that:",
                listOf("Worsens immediately after eating", "Is relieved by food or antacids, occurring 2 to 3 hours after meals", "Radiates to right shoulder", "Is constant for 24 hours"), 1),
            Triple("The primary infectious cause of chronic gastritis and peptic ulcer disease worldwide is:",
                listOf("Escherichia coli", "Helicobacter pylori (H. pylori)", "Clostridium difficile", "Salmonella enterica"), 1),
            Triple("Gastroesophageal Reflux Disease (GERD) patient positioning after meals should be:",
                listOf("Supine with head flat", "Upright position (sitting or HOB elevated) for at least 2 hours", "Left lateral position flat", "Prone position"), 1),
            Triple("Ulcerative Colitis is an inflammatory bowel disease restricted to the mucosal layer of the:",
                listOf("Small intestine (ileum)", "Colon and Rectum, presenting with bloody mucosal diarrhea", "Stomach", "Esophagus"), 1),
            Triple("Crohn's Disease can affect any part of the GI tract from mouth to anus, characteristically displaying:",
                listOf("Continuous rectal inflammation", "Transmural inflammation with 'skip lesions' and cobblestone appearance", "Superficial mucosal lesions only", "Pyloric stenosis"), 1),
            Triple("Appendicitis pain classically begins as periumbilical discomfort and migrates to which abdominal quadrant?",
                listOf("Left Upper Quadrant (LUQ)", "Right Lower Quadrant (RLQ) at McBurney's Point", "Left Lower Quadrant (LLQ)", "Right Upper Quadrant (RUQ)"), 1),
            Triple("Rebound tenderness at McBurney's point (Blumberg's sign) is a cardinal physical finding in:",
                listOf("Acute Cholecystitis", "Acute Appendicitis", "Pancreatitis", "Diverticulosis"), 1),
            Triple("Murphy's sign (inspiratory arrest on deep palpation of RUQ) indicates:",
                listOf("Acute Appendicitis", "Acute Cholecystitis", "Renal Colic", "Peritonitis"), 1),
            Triple("Acute Pancreatitis presents with severe epigastric pain radiating to the back. Serum laboratory elevation involves:",
                listOf("Troponin and CK-MB", "Serum Amylase and Lipase", "BUN and Creatinine", "ALT and AST only"), 1),
            Triple("Cirrhosis of the liver causes portal hypertension leading to life-threatening bleeding from:",
                listOf("Peptic ulcers", "Esophageal Varices", "Hemorrhoids", "Duodenal polyps"), 1),
            Triple("Hepatic Encephalopathy in end-stage liver disease occurs due to accumulation of toxic serum levels of:",
                listOf("Urea", "Ammonia (NH3)", "Bilirubin", "Lactic acid"), 1),
            Triple("A flapping hand tremor observed in Hepatic Encephalopathy is termed:",
                listOf("Ataxia", "Asterixis", "Chorea", "Myoclonus"), 1),
            Triple("Lactulose administration in Hepatic Encephalopathy lowers blood ammonia by:",
                listOf("Promoting urinary ammonia loss", "Acidifying colonic content to trap ammonia and promoting osmotic laxative elimination", "Inhibiting liver enzymes", "Binding urea"), 1),
            Triple("Type 1 Diabetes Mellitus is characterized pathophysiologically by absolute insulin deficiency caused by:",
                listOf("Insulin resistance in muscle", "Autoimmune destruction of pancreatic beta cells", "High carbohydrate diet", "Pituitary adenoma"), 1),
            Triple("Type 2 Diabetes Mellitus is characterized primarily by:",
                listOf("Absolute absence of insulin", "Insulin resistance combined with progressive impairment of insulin secretion", "Autoimmune beta cell destruction", "Ketoacidosis in all cases"), 1),
            Triple("Diabetic Ketoacidosis (DKA) occurs predominantly in Type 1 Diabetes and presents with Kussmaul respirations, which are:",
                listOf("Slow shallow breaths", "Deep, rapid, labored respirations to blow off carbon dioxide (metabolic acidosis compensation)", "Apneic pauses", "Wheezing"), 1),
            Triple("Fruity breath odor in DKA patient is caused by exhalation of volatile:",
                listOf("Ammonia", "Acetone (ketone body)", "Methane", "Lactic acid"), 1),
            Triple("Hyperosmolar Hyperglycemic State (HHS) occurs mainly in elderly Type 2 Diabetics and is distinguished from DKA by:",
                listOf("Severe ketosis", "Extremely high blood glucose (> 600 mg/dL) with profound dehydration and minimal/no ketoacidosis", "Metabolic acidosis", "Young age"), 1),
            Triple("Hypoglycemia is defined as a blood glucose level below 70 mg/dL. Autonomic signs of hypoglycemia include:",
                listOf("Hot dry skin and flush", "Diaphoresis (sweating), tremors, tachycardia, anxiety, and hunger", "Polyuria and polydipsia", "Kussmaul breathing"), 1),
            Triple("Rule of 15 for treating mild-to-moderate conscious hypoglycemia involves administering:",
                listOf("15 mL of water and waiting 1 hour", "15 grams of fast-acting simple carbohydrate, rechecking blood glucose in 15 minutes", "15 units of regular insulin", "15 grams of fat"), 1),
            Triple("For an unconscious hypoglycemic patient without IV access in emergency settings, the immediate drug choice is:",
                listOf("Oral orange juice", "IM or SC Glucagon injection", "IV Regular Insulin", "Sublingual nifedipine"), 1),
            Triple("Graves' Disease is the most common cause of Hyperthyroidism, presenting with:",
                listOf("Weight gain, cold intolerance, and bradycardia", "Exophthalmos (bulging eyes), heat intolerance, weight loss, and tachycardia", "Hypotension and lethargy", "Ptosis"), 1),
            Triple("Thyroid Storm (Thyrotoxic Crisis) is a life-threatening emergency characterized by severe:",
                listOf("Hypothermia and bradycardia", "Hyperpyrexia (fever > 40°C), extreme tachycardia, agitation, and heart failure", "Lethargy and coma", "Hypoglycemia"), 1),
            Triple("Hypothyroidism (Myxedema) clinical manifestations include:",
                listOf("Heat intolerance and weight loss", "Fatigue, cold intolerance, weight gain, constipation, dry skin, and bradycardia", "Exophthalmos", "Diarrhea"), 1),
            Triple("Cushing's Syndrome results from chronic excess of circulating cortisol, presenting with:",
                listOf("Adrenal insufficiency", "Moon face, buffalo hump, central obesity, purple abdominal striae, and hypertension", "Hyperpigmentation and hypotension", "Hypoglycemia"), 1),
            Triple("Addison's Disease (Primary Adrenal Insufficiency) manifestations include:",
                listOf("Hypertension and moon face", "Hyperpigmentation of skin, hypotension, hyponatremia, and hyperkalemia", "Hyperglycemia", "Weight gain"), 1),
            Triple("Addisonian Crisis (Acute Adrenal Crisis) is a medical emergency precipitated by stress or sudden steroid withdrawal, presenting with:",
                listOf("Severe hypertension", "Profound hypotension / vascular shock, hyponatremia, and hyperkalemia", "Hyperglycemia", "Fluid overload"), 1),
            Triple("Preoperative nursing checklist requires confirming that the patient has been kept NPO for at least:",
                listOf("2 hours", "6 to 8 hours prior to elective surgery to prevent aspiration", "24 hours", "12 hours for liquids"), 1),
            Triple("The surgical consent form must be signed voluntarily by the patient. The nurse's role in informed consent is to:",
                listOf("Explain surgical risks and alternatives", "Witness the patient's signature and verify patient voluntariness and competence", "Force signature", "Prescribe anesthesia"), 1),
            Triple("Postoperative atelectasis (alveolar collapse) is prevented primarily by encouraging the patient to perform:",
                listOf("Bed rest flat", "Incentive Spirometry, deep breathing, coughing, and early ambulation", "Fluid restriction", "Continuous sedation"), 1),
            Triple("Deep Vein Thrombosis (DVT) in post-op immobilized patients presents with leg pain, warmth, edema, and positive:",
                listOf("Murphy's sign", "Homan's sign (dorsiflexion calf pain)", "Kernig's sign", "Trousseau's sign"), 1),
            Triple("Hypovolemic shock caused by severe blood or fluid loss is characterized hemodynamically by:",
                listOf("High BP and bradycardia", "Hypotension, tachycardia, weak thready pulse, cool clammy skin, and oliguria", "Warm flushed skin and bounding pulse", "Normal urinary output"), 1),
            Triple("In shock management, urinary output is the single best non-invasive indicator of organ perfusion. Minimum safe hourly output is:",
                listOf("10 mL/hr", "30 mL/hr (0.5 mL/kg/hr)", "100 mL/hr", "200 mL/hr"), 1),
            Triple("Sepsis is defined as life-threatening organ dysfunction caused by a dysregulated host response to infection. Septic Shock involves:",
                listOf("Hypertension", "Persistent hypotension requiring vasopressors to maintain MAP >= 65 mmHg despite fluid resuscitation", "Bradycardia", "Hypothermia only"), 1),
            Triple("Systemic Inflammatory Response Syndrome (SIRS) criteria include temperature > 38°C or < 36°C, heart rate > 90, respirations > 20, and WBC:",
                listOf("< 4,000 or > 12,000 /mm³", "< 1,000", "> 50,000", "Normal range"), 0),
            Triple("Anaphylactic shock is a severe Type 1 hypersensitivity reaction treated immediately with IM administration of:",
                listOf("Diphenhydramine", "Epinephrine (Adrenaline) 1:1,000 in anterolateral thigh", "Hydrocortisone", "Atropine"), 1),
            Triple("Post-operative wound dressing saturated with bright red blood requires the nurse to immediately:",
                listOf("Change dressing completely", "Reinforce dressing with sterile gauze, apply direct pressure, and notify surgeon", "Remove sutures", "Ignore until shift end"), 1)
        )

        ahn1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 3,
                    subjectName = "Adult Health Nursing I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Adult Health Nursing I (AHN-631) Med-Surg core concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU AHN-631 / Brunner & Suddarth's Textbook of Medical-Surgical Nursing"
                )
            )
        }

        // ==========================================
        // 2. PATHOPHYSIOLOGY I (PAT-632) - 40 Qs
        // ==========================================
        val pat1Data = listOf(
            Triple("Cellular adaptation characterized by an increase in cell size resulting in enlarged organ size is termed:",
                listOf("Hyperplasia", "Hypertrophy", "Atrophy", "Metaplasia"), 1),
            Triple("An increase in the total number of cells in an organ or tissue through cell division is termed:",
                listOf("Hypertrophy", "Hyperplasia", "Dysplasia", "Metaplasia"), 1),
            Triple("Reversible replacement of one adult cell type by another adult cell type (e.g. Barrett's esophagus) is called:",
                listOf("Anaplasia", "Metaplasia", "Hypertrophy", "Atrophy"), 1),
            Triple("Deranged cell growth characterized by atypical variations in cell size, shape, and nuclear organization is termed:",
                listOf("Metaplasia", "Dysplasia (pre-cancerous)", "Hyperplasia", "Atrophy"), 1),
            Triple("Programmed cell death designed to eliminate unwanted or damaged cells without causing inflammation is termed:",
                listOf("Necrosis", "Apoptosis", "Autolysis", "Gangrene"), 1),
            Triple("Unregulated, accidental cell death resulting from severe injury accompanied by cellular swelling and inflammation is:",
                listOf("Apoptosis", "Necrosis", "Autophagy", "Atrophy"), 1),
            Triple("Coagulative necrosis is the characteristic pattern of cell death seen in ischemic infarction of all organs EXCEPT the:",
                listOf("Heart", "Kidney", "Brain (which undergoes Liquefactive necrosis)", "Spleen"), 2),
            Triple("Caseous necrosis ('cheese-like' friable yellow appearance) is classically characteristic of infection with:",
                listOf("Staphylococcus aureus", "Mycobacterium tuberculosis", "Pseudomonas aeruginosa", "Candida albicans"), 1),
            Triple("Acute inflammation cardinal signs include Rubor (redness), Calor (heat), Tumor (swelling), Dolor (pain), and:",
                listOf("Fungus", "Functio laesa (loss of function)", "Pus", "Necrosis"), 1),
            Triple("The vascular response in acute inflammation begins with transient vasoconstriction followed immediately by prolonged:",
                listOf("Vasoconstriction", "Vasodilation and increased microvascular permeability", "Ischemia", "Thrombosis"), 1),
            Triple("Which vasoactive amine released by mast cells mediates early vasodilation and vascular permeability in acute inflammation?",
                listOf("Serotonin", "Histamine", "Bradykinin", "Leukotriene B4"), 1),
            Triple("Transudate fluid is characterized by:",
                listOf("High protein and cellular content", "Low protein concentration (< 3 g/dL) and low specific gravity due to hydrostatic changes", "Pus content", "High LDH"), 1),
            Triple("Exudate fluid accumulated during inflammation contains:",
                listOf("Low protein content", "High protein content (> 3 g/dL) and abundant leukocytes", "Clear water only", "Zero WBCs"), 1),
            Triple("Benign tumors are distinguished from malignant neoplasms because benign tumors:",
                listOf("Metastasize rapidly", "Are well-differentiated, slow-growing, encapsulated, and do not metastasize", "Infiltrate surrounding tissue", "Display anaplasia"), 1),
            Triple("The hallmark characteristic defining malignant neoplasms (cancer) is their ability to:",
                listOf("Grow slowly", "Invade surrounding local tissues and metastasize to distant anatomical sites", "Form capsular borders", "Undergo apoptosis"), 1),
            Triple("Carcinomas are malignant tumors originating from which tissue type?",
                listOf("Mesenchymal connective tissue", "Epithelial tissue", "Lymphoid tissue", "Nerve cells"), 1),
            Triple("Sarcomas are malignant tumors originating from:",
                listOf("Epithelium", "Mesenchymal connective tissue (bone, muscle, cartilage, fat)", "Glial cells", "Skin epidermis"), 1),
            Triple("Atherosclerosis pathogenesis begins with endothelial injury followed by oxidation and accumulation of:",
                listOf("HDL cholesterol", "LDL cholesterol taken up by macrophages to form foam cells", "Calcium only", "Fibrin"), 1),
            Triple("Myocardial Infarction occurs when coronary artery blood flow is occluded, causing irreversible myocardial cell death after:",
                listOf("1 minute", "20 to 30 minutes of severe ischemia", "6 hours", "24 hours"), 1),
            Triple("Pathophysiology of Heart Failure involves compensatory mechanisms such as activation of the Sympathetic Nervous System and the:",
                listOf("Renin-Angiotensin-Aldosterone System (RAAS)", "Parasympathetic system", "Thyroid axis", "Immune complex"), 1),
            Triple("Emphysema is characterized structurally by permanent enlargement and destruction of:",
                listOf("Trachea", "Alveolar walls and respiratory bronchioles, destroying elastic recoil", "Laryngeal cartilages", "Pleural space"), 1),
            Triple("Chronic Bronchitis is diagnosed clinically by productive cough present for at least:",
                listOf("1 week", "3 consecutive months per year for 2 consecutive years", "1 month", "6 months"), 1),
            Triple("Lobar Pneumonia progression stages include Congestion, Red Hepatization, Grey Hepatization, and:",
                listOf("Fibrosis", "Resolution", "Gangrene", "Caseation"), 1),
            Triple("Acute Respiratory Distress Syndrome (ARDS) pathophysiology involves diffuse damage to alveolar-capillary membranes leading to:",
                listOf("Non-cardiogenic pulmonary edema and refractory hypoxemia", "Bronchospasm only", "Pneumothorax", "Pleural effusion"), 0),
            Triple("Atherosclerotic plaque rupture triggering arterial thrombosis in cerebral circulation leads to:",
                listOf("Hemorrhagic Stroke", "Ischemic Stroke (Cerebrovascular Accident)", "Subarachnoid hemorrhage", "Epidural hematoma"), 1),
            Triple("Multiple Sclerosis is an autoimmune central nervous system disorder characterized by demyelination of:",
                listOf("Peripheral nerve axons", "CNS axons in brain and spinal cord white matter", "Neuromuscular junction", "Autonomic ganglia"), 1),
            Triple("Myasthenia Gravis is an autoimmune disorder caused by autoantibodies directed against:",
                listOf("Myelin sheath", "Postsynaptic Acetylcholine (ACh) receptors at neuromuscular junction", "Voltage-gated calcium channels", "Dopamine receptors"), 1),
            Triple("Parkinson's Disease pathophysiology involves progressive degeneration of dopaminergic neurons in the:",
                listOf("Cerebellum", "Substantia Nigra pars compacta of basal ganglia", "Hippocampus", "Hypothalamus"), 1),
            Triple("Alzheimer's Disease histopathology reveals extracellular neurotoxic plaques composed of:",
                listOf("Alpha-synuclein", "Amyloid-beta peptides and intracellular neurofibrillary tangles of hyperphosphorylated tau protein", "Prion proteins", "Lewy bodies"), 1),
            Triple("Glomerulonephritis is an inflammatory renal condition often triggered by Type III hypersensitivity immune complex deposition following infection with:",
                listOf("Group A Beta-Hemolytic Streptococcus (GABHS)", "Staphylococcus epidermidis", "Escherichia coli", "Pseudomonas"), 0),
            Triple("Nephrotic Syndrome classic clinical tetrad includes massive proteinuria (> 3.5 g/day), hypoalbuminemia, generalized edema, and:",
                listOf("Hematuria", "Hyperlipidemia", "Hypotension", "Anuria"), 1),
            Triple("Acute Kidney Injury (AKI) classified as Prerenal azotemia is caused by:",
                listOf("Tubular necrosis", "Renal hypoperfusion (e.g., severe hypovolemia, hypotension, or heart failure)", "Ureteral stone obstruction", "Glomerulonephritis"), 1),
            Triple("Intrarenal (Intrinsic) AKI primary etiology is:",
                listOf("Dehydration", "Acute Tubular Necrosis (ATN) due to ischemia or nephrotoxic agents", "Prostatic hyperplasia", "Renal artery stenosis"), 1),
            Triple("Postrenal AKI results from urinary tract obstruction such as:",
                listOf("Renal ischemia", "Bilateral ureteral calculi or Benign Prostatic Hyperplasia (BPH)", "Glomerulonephritis", "Shock"), 1),
            Triple("Iron Deficiency Anemia results in red blood cells that appear on microscopic blood film as:",
                listOf("Macrocytic hyperchromic", "Microcytic hypochromic", "Normocytic normochromic", "Spherocytic"), 1),
            Triple("Pernicious Anemia macrocytic megaloblastic changes stem from Vitamin B12 deficiency impairing cellular:",
                listOf("Hemoglobin production", "DNA synthesis and nuclear maturation", "Lipid synthesis", "ATP production"), 1),
            Triple("Sickle Cell Anemia results from a point mutation substituting valine for glutamic acid at position 6 of the beta-globin chain, causing hemoglobin polymerization under conditions of:",
                listOf("Hyperoxia", "Deoxygenation / Hypoxia, dehydration, and acidosis", "Alkalosis", "Hypothermia"), 1),
            Triple("Disseminated Intravascular Coagulation (DIC) is a complex secondary disorder characterized paradoxically by concurrent:",
                listOf("Hypertension and tachycardia", "Widespread intravascular clotting and profuse bleeding due to clotting factor consumption", "Leukocytosis", "Thrombocytosis"), 1),
            Triple("Pathophysiology of Shock at the cellular level shifts aerobic metabolism to anaerobic metabolism, generating toxic accumulation of:",
                listOf("Urea", "Lactic Acid (Lactic Acidosis)", "Pyruvate", "Carbonic acid"), 1),
            Triple("Type 1 Hypersensitivity reactions (Anaphylaxis, Asthma, Atopy) are mediated by antigen binding to IgE on surfaces of:",
                listOf("Neutrophils", "Mast cells and Basophils", "T Lymphocytes", "Macrophage cells"), 1)
        )

        pat1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 3,
                    subjectName = "Pathophysiology I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Pathophysiology I (PAT-632) disease mechanism concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU PAT-632 / Robbins & Cotran Pathologic Basis of Disease"
                )
            )
        }

        // ==========================================
        // 3. PHARMACOLOGY I (PHA-633) - 50 Qs
        // ==========================================
        val pha1Data = listOf(
            Triple("Pharmacokinetics encompasses what the body does to a drug, defined by four processes abbreviated ADME:",
                listOf("Absorption, Distribution, Metabolism, Excretion", "Administration, Dosage, Measurement, Effect", "Action, Duration, Method, Elimination", "Affinity, Dissociation, Metabolism, Efficacy"), 0),
            Triple("Pharmacodynamics is defined as:",
                listOf("The rate of drug clearance", "What the drug does to the body (mechanism of action, receptor binding, physiological effect)", "Drug cost evaluation", "Synthetic drug manufacturing"), 1),
            Triple("The term 'Bioavailability' refers to the percentage of administered drug that reaches systemic circulation in active form. IV administration bioavailability is:",
                listOf("25%", "50%", "75%", "100%"), 3),
            Triple("First-Pass Metabolism occurs primarily in the liver following which route of drug administration?",
                listOf("Intravenous (IV)", "Oral (PO)", "Sublingual (SL)", "Intramuscular (IM)"), 1),
            Triple("Drug Half-Life (t1/2) is the time required for the plasma concentration of a drug to decrease by:",
                listOf("10%", "25%", "50%", "90%"), 2),
            Triple("How many half-lives are typically required for a drug to reach steady-state plasma concentration during repeated dosing?",
                listOf("1 to 2 half-lives", "4 to 5 half-lives", "10 half-lives", "20 half-lives"), 1),
            Triple("A drug that binds to a receptor and activates it to produce a maximal biological response is an:",
                listOf("Antagonist", "Agonist", "Inverse agonist", "Competitive inhibitor"), 1),
            Triple("A drug that binds to a receptor without activating it, blocking natural agonist binding, is an:",
                listOf("Agonist", "Antagonist", "Partial agonist", "Enzyme inducer"), 1),
            Triple("The primary organ responsible for drug biotransformation (metabolism) via Cytochrome P450 enzymes is the:",
                listOf("Kidney", "Liver", "Lung", "Small intestine"), 1),
            Triple("The primary organ responsible for drug elimination (excretion) from the human body is the:",
                listOf("Liver", "Kidneys", "Skin", "Biliary system"), 1),
            Triple("Atropine is a competitive antagonist of which receptor type?",
                listOf("Nicotinic receptors", "Muscarinic acetylcholine receptors (Anticholinergic)", "Beta-1 receptors", "Alpha-1 receptors"), 1),
            Triple("Anticholinergic side effects of Atropine include:",
                listOf("Profuse sweating and diarrhea", "Dry mouth, blurred vision, urinary retention, and constipation ('dry as a bone')", "Bradycardia", "Miosis"), 1),
            Triple("Pilocarpine is a direct-acting muscarinic agonist used topically in glaucoma to produce pupil constriction termed:",
                listOf("Mydriasis", "Miosis", "Ptosis", "Nystagmus"), 1),
            Triple("Epinephrine (Adrenaline) stimulates Alpha-1, Beta-1, and Beta-2 adrenergic receptors. Beta-1 stimulation in the heart causes:",
                listOf("Bronchoconstriction", "Increased heart rate (positive chronotropy) and contractility (positive inotropy)", "Vasodilation", "Bradycardia"), 1),
            Triple("Beta-2 adrenergic receptor stimulation in bronchial smooth muscle produces:",
                listOf("Bronchoconstriction", "Bronchodilation", "Mucus hypersecretion", "Bradycardia"), 1),
            Triple("Propranolol is a non-selective Beta-adrenergic blocker. It is CONTRAINDICATED in patients with:",
                listOf("Hypertension", "Asthma or COPD (due to Beta-2 blockade causing bronchospasm)", "Angina pectoris", "Tachycardia"), 1),
            Triple("Metoprolol and Atenolol selectively block which adrenergic receptors, making them safer in asthmatic patients?",
                listOf("Alpha-1 receptors", "Beta-1 cardiac receptors (Cardioselective)", "Beta-2 receptors", "Muscarinic receptors"), 1),
            Triple("Alpha-1 adrenergic blockers such as Prazosin and Tamsulosin cause vasodilation and smooth muscle relaxation, used to treat hypertension and:",
                listOf("Asthma", "Benign Prostatic Hyperplasia (BPH)", "Glaucoma", "Diarrhea"), 1),
            Triple("ACE Inhibitors (e.g. Captopril, Enalapril, Lisinopril) inhibit conversion of Angiotensin I to Angiotensin II. A common dry cough side effect is caused by accumulation of:",
                listOf("Histamine", "Bradykinin", "Serotonin", "Substance P"), 1),
            Triple("Angiotensin II Receptor Blockers (ARBs) such as Losartan and Valsartan are prescribed as alternatives to ACE inhibitors because ARBs do NOT cause:",
                listOf("Hypotension", "Dry cough", "Hyperkalemia", "Renal impairment"), 1),
            Triple("Which diuretic class acting on the thick ascending limb of the Loop of Henle is the most potent (e.g. Furosemide / Lasix)?",
                listOf("Thiazide diuretics", "Loop Diuretics", "Potassium-sparing diuretics", "Osmotic diuretics"), 1),
            Triple("Furosemide (Lasix) loop diuretic administration requires monitoring for which serum electrolyte depletion?",
                listOf("Hyperkalemia", "Hypokalemia (Low potassium)", "Hypercalcemia", "Hypernatremia"), 1),
            Triple("Spironolactone (Aldactone) is classified as a potassium-sparing diuretic that functions as an antagonist to:",
                listOf("Renin", "Aldosterone", "ADH", "Angiotensin II"), 1),
            Triple("Mannitol is an osmotic diuretic primarily indicated to reduce elevated:",
                listOf("Blood pressure", "Intracranial Pressure (ICP) and Intraocular Pressure (IOP)", "Serum potassium", "Blood glucose"), 1),
            Triple("Digoxin is a positive inotropic cardiac glycoside that increases myocardial contractility by inhibiting:",
                listOf("Beta-1 receptors", "Na+/K+ ATPase pump", "ACE enzyme", "Calcium channels"), 1),
            Triple("Digoxin Toxicity early clinical signs include visual disturbances (yellow-green halos) and GI symptoms (nausea/vomiting). Normal serum Digoxin level is:",
                listOf("0.5 to 2.0 ng/mL", "5.0 to 10.0 ng/mL", "15 to 20 ng/mL", "50 ng/mL"), 0),
            Triple("Before administering Digoxin, the nurse MUST assess the patient's apical pulse for 1 full minute and hold medication if HR is under:",
                listOf("50 bpm", "60 bpm", "70 bpm", "80 bpm"), 1),
            Triple("Nitroglycerin vasodilates venous capacitance vessels to reduce myocardial preload. Sublingual doses may be repeated every 5 minutes up to a maximum of:",
                listOf("1 dose", "3 doses within 15 minutes", "5 doses", "Unlimited doses"), 1),
            Triple("Calcium Channel Blockers (e.g., Amlodipine, Nifedipine, Diltiazem) lower BP by blocking L-type calcium channels causing smooth muscle:",
                listOf("Vasoconstriction", "Vasodilation", "Bronchospasm", "Tachycardia only"), 1),
            Triple("Heparin anticoagulant activity is monitored in hospital labs using which test?",
                listOf("Prothrombin Time (PT)", "activated Partial Thromboplastin Time (aPTT)", "Bleeding Time", "INR"), 1),
            Triple("Warfarin (Coumadin) oral anticoagulant efficacy is monitored using:",
                listOf("aPTT", "Prothrombin Time (PT) / International Normalized Ratio (INR)", "Platelet count", "ACT"), 1),
            Triple("Target therapeutic INR range for a patient on Warfarin therapy for atrial fibrillation or DVT is generally:",
                listOf("0.5 - 1.0", "2.0 - 3.0", "4.5 - 6.0", "8.0 - 10.0"), 1),
            Triple("The antidote for Warfarin overdose presenting with elevated INR and bleeding is:",
                listOf("Protamine Sulfate", "Vitamin K1 (Phytonadione)", "Naloxone", "Flumazenil"), 1),
            Triple("Aspirin (Acetylsalicylic acid) inhibits platelet aggregation irreversibly by inhibiting which enzyme?",
                listOf("Phosphodiesterase", "Cyclooxygenase-1 (COX-1)", "Lipoxygenase", "Thrombin"), 1),
            Triple("Aspirin administration in children with viral infections (e.g. varicella, influenza) is strictly CONTRAINDICATED due to the risk of:",
                listOf("Gastrointestinal bleed", "Reye's Syndrome (severe encephalopathy and liver failure)", "Agranulocytosis", "Renal failure"), 1),
            Triple("Thrombolytic / Fibrinolytic agents (e.g. Alteplase / tPA) break down arterial blood clots by converting plasminogen to:",
                listOf("Fibrin", "Plasmin", "Thrombin", "Prothrombin"), 1),
            Triple("Statins (e.g., Atorvastatin, Simvastatin) lower serum cholesterol by competitively inhibiting:",
                listOf("Pancreatic lipase", "HMG-CoA Reductase enzyme in liver", "Bile reabsorption", "SGLT2 transporter"), 1),
            Triple("A serious potential side effect of Statin therapy requiring immediate reporting is muscle pain/weakness known as:",
                listOf("Neuropathy", "Myopathy / Rhabdomyolysis", "Arthritis", "Osteomalacia"), 1),
            Triple("Penicillin antibiotics exert bactericidal action by inhibiting bacterial cell wall synthesis through binding to:",
                listOf("50S ribosomal subunit", "Penicillin-Binding Proteins (PBPs) interfering with peptidoglycan cross-linking", "DNA gyrase", "RNA polymerase"), 1),
            Triple("Cephalosporins (e.g. Ceftriaxone) share beta-lactam structure with penicillins. Patients with severe penicillin allergy have a risk of cross-reactivity of:",
                listOf("0%", "5% to 10%", "50%", "100%"), 1),
            Triple("Aminoglycoside antibiotics (e.g. Gentamicin, Amikacin) possess major black box warnings for:",
                listOf("Hepatotoxicity", "Ototoxicity (hearing loss) and Nephrotoxicity (kidney damage)", "Cardiotoxicity", "Aplastic anemia"), 1),
            Triple("Tetracycline antibiotics are strictly CONTRAINDICATED in pregnant women and children under 8 years of age because they cause:",
                listOf("Red man syndrome", "Permanent tooth discoloration and bone growth inhibition", "Tendon rupture", "Optic neuritis"), 1),
            Triple("Fluoroquinolones (e.g. Ciprofloxacin, Levofloxacin) carry a black box warning for increased risk of:",
                listOf("Otitis media", "Tendinitis and Tendon Rupture (especially Achilles tendon)", "Seizures", "Hepatitis"), 1),
            Triple("Vancomycin IV rapid infusion can cause histamine release presenting with facial flushing and hypotension known as:",
                listOf("Gray baby syndrome", "Red Man Syndrome (prevented by slowing infusion rate over at least 60 min)", "Stevens-Johnson syndrome", "Cushingoid state"), 1),
            Triple("Metronidazole (Flagyl) produces a severe disulfiram-like reaction (flushing, vomiting, tachycardia) if combined with:",
                listOf("Milk", "Alcohol", "Grapefruit juice", "Coffee"), 1),
            Triple("Opioid analgesics (e.g., Morphine, Fentanyl) act on mu-opioid receptors. The most dangerous adverse effect requiring monitoring is:",
                listOf("Constipation", "Respiratory Depression", "Pruritus", "Pinpoint pupils"), 1),
            Triple("The specific competitive opioid antagonist used to reverse life-threatening opioid respiratory depression is:",
                listOf("Flumazenil", "Naloxone (Narcan)", "Atropine", "Protamine"), 1),
            Triple("Benzodiazepines (e.g., Diazepam, Lorazepam) enhance the inhibitory neurotransmitter:",
                listOf("Dopamine", "GABA (Gamma-Aminobutyric Acid)", "Serotonin", "Acetylcholine"), 1),
            Triple("The specific reversing antagonist for Benzodiazepine overdose is:",
                listOf("Naloxone", "Flumazenil", "Physostigmine", "N-acetylcysteine"), 1),
            Triple("Acetaminophen (Paracetamol) overdose causes acute toxic liver necrosis. The specific antidote is:",
                listOf("Naloxone", "N-Acetylcysteine (NAC)", "Atropine", "Deferoxamine"), 1)
        )

        pha1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 3,
                    subjectName = "Pharmacology I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Pharmacology I (PHA-633) drug mechanism/clinical concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU PHA-633 / Katzung's Basic & Clinical Pharmacology"
                )
            )
        }

        // ==========================================
        // 4. HEALTH ASSESSMENT I (HAS-634) - 40 Qs
        // ==========================================
        val has1Data = listOf(
            Triple("The four fundamental physical examination techniques performed during health assessment in standard order are:",
                listOf("Palpation, Percussion, Inspection, Auscultation", "Inspection, Palpation, Percussion, Auscultation", "Auscultation, Inspection, Palpation, Percussion", "Percussion, Palpation, Auscultation, Inspection"), 1),
            Triple("When performing physical examination of the abdomen, the correct sequence of techniques is modified to:",
                listOf("Inspection, Palpation, Percussion, Auscultation", "Inspection, Auscultation, Percussion, Palpation", "Auscultation, Inspection, Palpation, Percussion", "Palpation, Auscultation, Inspection, Percussion"), 1),
            Triple("Why is Auscultation performed BEFORE Palpation and Percussion during abdominal assessment?",
                listOf("To save time", "Palpation and percussion can alter bowel motility and generate artificial bowel sounds", "To relax abdominal muscles", "It is easier"), 1),
            Triple("The nurse uses the bell of the stethoscope primarily to auscultate:",
                listOf("High-pitched breath sounds", "Low-pitched vascular bruits and heart murmurs (e.g. S3, S4)", "Normal bowel sounds", "S1 and S2 heart sounds"), 1),
            Triple("Normal vesicular breath sounds heard over peripheral lung fields are characterized as:",
                listOf("Harsh, high-pitched, loud sounds with equal inspiration and expiration", "Soft, low-pitched, gentle rustling sounds with longer inspiration than expiration", "Tubular loud sounds", "Musical wheezes"), 1),
            Triple("Bronchial breath sounds normally heard over the trachea are characterized as:",
                listOf("Soft rustling sounds", "Loud, high-pitched, tubular sounds with expiration longer than inspiration", "Inaudible", "Low rumbling"), 1),
            Triple("Auscultation of discontinuous, high-pitched, popping breath sounds caused by air opening closed fluid-filled alveoli is documented as:",
                listOf("Wheezes", "Crackles (Rales)", "Rhonchi", "Stridor"), 1),
            Triple("Continuous high-pitched musical sounds produced by air squeezing through narrowed airways (e.g. in asthma) are termed:",
                listOf("Crackles", "Wheezes", "Pleural friction rub", "Rhonchi"), 1),
            Triple("Harsh, high-pitched inspiratory sound heard over the larynx/trachea indicating upper airway obstruction (emergency) is:",
                listOf("Wheezing", "Stridor", "Rhonchi", "Crackles"), 1),
            Triple("The anatomical landmark for auscultating the Apical Pulse (Mitral area) in an adult is located at the:",
                listOf("2nd Intercostal Space at right sternal border", "5th Intercostal Space at left midclavicular line", "4th Intercostal Space at left sternal border", "2nd Intercostal Space at left sternal border"), 1),
            Triple("The Aortic auscultatory site on the anterior chest wall is located at the:",
                listOf("2nd Intercostal Space, Right Sternal Border", "2nd Intercostal Space, Left Sternal Border", "3rd Intercostal Space, Erb's point", "5th Intercostal Space"), 0),
            Triple("Pulmonic auscultatory valve area is located at:",
                listOf("2nd Intercostal Space, Right Sternal Border", "2nd Intercostal Space, Left Sternal Border", "5th Intercostal Space", "Epigastrium"), 1),
            Triple("Erb's Point on the anterior chest wall is situated at:",
                listOf("2nd ICS right sternal border", "3rd Intercostal Space, Left Sternal Border (where S1 and S2 are heard equally)", "5th ICS midclavicular line", "Xiphoid process"), 1),
            Triple("Tricuspid valve auscultatory site is positioned at:",
                listOf("2nd ICS right sternal border", "4th or 5th Intercostal Space, Left Sternal Border", "5th ICS midclavicular line", "Axilla"), 1),
            Triple("S1 heart sound ('LUB') is caused by closure of the:",
                listOf("Aortic and Pulmonic valves", "Atrioventricular (Mitral and Tricuspid) valves", "Eustachian valve", "Vena cava"), 1),
            Triple("S2 heart sound ('DUB') is caused by closure of the:",
                listOf("Mitral and Tricuspid valves", "Semilunar (Aortic and Pulmonic) valves", "Foramen ovale", "Coronary sinus"), 1),
            Triple("An abnormal third heart sound (S3) heard in early diastole in older adults often indicates:",
                listOf("Normal finding", "Heart Failure (ventricular gallop due to fluid overload)", "Aortic stenosis", "Pericarditis"), 1),
            Triple("Physical assessment of Jugular Venous Distension (JVD) evaluates right atrial pressure. The patient should be positioned at a HOB angle of:",
                listOf("0 degrees (flat)", "30 to 45 degrees", "90 degrees", "180 degrees"), 1),
            Triple("Capillary Refill Time (CRT) assessment evaluates peripheral perfusion. Normal CRT is:",
                listOf("< 2 seconds", "5 to 8 seconds", "10 seconds", "15 seconds"), 0),
            Triple("When testing Cranial Nerve III, IV, and VI (Oculomotor, Trochlear, Abducens), the nurse assesses:",
                listOf("Visual acuity using Snellen chart", "Extraocular Muscle Movements (Six cardinal fields of gaze) and pupillary light response", "Facial symmetry", "Hearing whisper test"), 1),
            Triple("PERRLA acronym in neurological eye assessment documentation stands for:",
                listOf("Pupils Equal, Round, Reactive to Light and Accommodation", "Pressure Equal, Right, Reactive, Light, Acuity", "Pupils Elevated, Round, Refractive, Latent, Active", "Pulse Equal, Rapid, Regular, Light, Aligned"), 0),
            Triple("Cranial Nerve V (Trigeminal Nerve) assessment involves testing:",
                listOf("Smell", "Facial sensation (light touch) and jaw motor strength (mastication muscles)", "Tongue protrusion", "Shoulder shrug"), 1),
            Triple("Cranial Nerve VII (Facial Nerve) motor function is assessed by asking the patient to:",
                listOf("Shrug shoulders against resistance", "Smile, frown, puff cheeks, and close eyes tightly", "Stick out tongue", "Read Snellen chart"), 1),
            Triple("Cranial Nerve VIII (Vestibulocochlear / Acoustic) is tested using:",
                listOf("Snellen eye chart", "Whisper voice test, Weber test, and Rinne tuning fork test", "Gag reflex test", "Smell test"), 1),
            Triple("Cranial Nerve IX (Glossopharyngeal) and X (Vagus) are assessed by observing soft palate elevation and testing the:",
                listOf("Visual fields", "Gag reflex and swallowing ability", "Pupil contraction", "Smile symmetry"), 1),
            Triple("Cranial Nerve XI (Spinal Accessory) motor function is evaluated by asking the patient to:",
                listOf("Stick out tongue", "Shrug shoulders against resistance and turn head against hand resistance", "Smell coffee", "Gag"), 1),
            Triple("Cranial Nerve XII (Hypoglossal) controls tongue movement. Assessment involves asking the patient to:",
                listOf("Smile", "Protrude tongue and move it side to side", "Swallow water", "Frown"), 1),
            Triple("When performing Weber's tuning fork test for hearing lateralization, a normal result is heard:",
                listOf("In right ear only", "Equally in both ears at midline of skull", "In left ear only", "Not heard at all"), 1),
            Triple("Rinne tuning fork test compares Air Conduction (AC) and Bone Conduction (BC). Normal hearing displays:",
                listOf("BC > AC", "Air Conduction greater than Bone Conduction (AC > BC)", "AC = BC", "Zero conduction"), 1),
            Triple("Glasgow Coma Scale (GCS) evaluates level of consciousness across 3 categories: Eye Opening, Verbal Response, and:",
                listOf("Pupil size", "Motor Response", "Reflexes", "Sensory score"), 1),
            Triple("Maximum possible total score on the Glasgow Coma Scale for a fully alert, oriented individual is:",
                listOf("10", "15", "12", "20"), 1),
            Triple("A Glasgow Coma Scale score equal to or less than what value generally defines severe brain injury / coma requiring airway protection?",
                listOf("12", "8 (GCS <= 8 = Comatose)", "5", "3"), 1),
            Triple("Lowest possible score on the Glasgow Coma Scale (indicating deep coma or brain death) is:",
                listOf("0", "3", "1", "5"), 1),
            Triple("Deep Tendon Reflex (DTR) grading scale rates a normal active reflex as:",
                listOf("0 (Absent)", "1+ (Hypoactive)", "2+ (Normal)", "4+ (Hyperactive with clonus)"), 2),
            Triple("Babinski Reflex in a healthy adult is abnormal if positive, demonstrated by:",
                listOf("Plantar flexion (curling downward) of toes", "Dorsiflexion of great toe with fanning of other toes (indicating upper motor neuron lesion)", "Knee jerk", "Pupil contraction"), 1),
            Triple("Trousseau's Sign (carpopedal spasm induced by inflating BP cuff above SBP for 3 minutes) indicates clinical:",
                listOf("Hypercalcemia", "Hypocalcemia (or Hypomagnesemia)", "Hyperkalemia", "Hyponatremia"), 1),
            Triple("Chvostek's Sign (facial muscle twitching elicited by tapping facial nerve anterior to ear lobe) indicates:",
                listOf("Hyperkalemia", "Hypocalcemia", "Hypernatremia", "Hypoglycemia"), 1),
            Triple("Snellen eye chart placed 20 feet away tests distance visual acuity. 20/40 vision means the patient reads at 20 feet what a normal eye reads at:",
                listOf("10 feet", "40 feet", "20 feet", "80 feet"), 1),
            Triple("When assessing skin turgor for dehydration, the nurse pinches skin over the clavicle or forearm. Delayed return ('tenting') indicates:",
                listOf("Edema", "Fluid Volume Deficit (Dehydration)", "Normal skin elasticity", "Obesity"), 1),
            Triple("Pitting edema scale rating +3 indicates deep pitting indentation of approximately:",
                listOf("2 mm", "4 mm", "6 mm", "8 mm"), 2)
        )

        has1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 3,
                    subjectName = "Health Assessment I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Health Assessment I (HAS-634) physical examination concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU HAS-634 / Jarvis Physical Examination & Health Assessment"
                )
            )
        }

        // ==========================================
        // 5. ISLAMIC STUDIES / ETHICS (ISL-635) - 30 Qs
        // ==========================================
        val isl1Data = listOf(
            Triple("In bioethics and nursing practice, the ethical principle of 'Autonomy' dictates that:",
                listOf("The nurse makes decisions for the patient", "Patients have the moral right to self-determination and informed consent regarding care", "Hospital policy overrides patient wishes", "Doctors hold total authority"), 1),
            Triple("The ethical principle of 'Beneficence' obligates healthcare providers to:",
                listOf("Do no harm", "Act in the best interest of the patient to promote good and wellbeing", "Treat all patients equally", "Tell the truth"), 1),
            Triple("The ethical principle of 'Non-Maleficence' (Primum non nocere) means:",
                listOf("Promote good", "First, do no harm to the patient", "Maintain privacy", "Be faithful"), 1),
            Triple("The principle of 'Justice' in healthcare ethics requires:",
                listOf("Keeping promises", "Fair, equitable distribution of healthcare resources without discrimination", "Doing good", "Respecting privacy"), 1),
            Triple("The obligation to tell the truth to patients regarding diagnosis and prognosis is termed:",
                listOf("Fidelity", "Veracity", "Confidentiality", "Paternalism"), 1),
            Triple("The duty to keep promises and commitments made to patients and maintain professional loyalty is termed:",
                listOf("Veracity", "Fidelity", "Beneficence", "Autonomy"), 1),
            Triple("Protecting patient personal health information from unauthorized disclosure complies with the ethical and legal mandate of:",
                listOf("Veracity", "Confidentiality", "Paternalism", "Justice"), 1),
            Triple("When a healthcare provider makes choices for a competent patient without their input 'for their own good', it is termed:",
                listOf("Autonomy", "Paternalism", "Fidelity", "Justice"), 1),
            Triple("In Islamic bioethics, human life is regarded as sacred (Hurmat-e-Insaan). Which Quranic concept highlights the sanctity of life?",
                listOf("'Saving one life is as if saving the whole of mankind'", "'Life is accidental'", "'Health is secondary'", "'Wealth equals health'"), 0),
            Triple("In Islamic jurisprudence (Fiqh), the legal maxim 'Hardship begets facility' (Al-Masashaqqatu Tajlibut Taysir) allows:",
                listOf("Ignoring all rules", "Relaxing religious obligations during illness (e.g. Tayammum when water harms patient, sitting during prayer)", "Abandoning medical treatment", "Unethical research"), 1),
            Triple("In Islamic nursing care, when a patient is unable to use water for wudu due to open wounds or severe illness, Islamic ruling permits:",
                listOf("Skipping prayer permanently", "Tayammum (dry ablution with clean earth/dust)", "Drinking holy water", "Fast breaking"), 1),
            Triple("According to Islamic medical ethics, seeking medical treatment for disease (Tadawi) is:",
                listOf("Forbidden (Haram)", "Encouraged and highly recommended (Sunnah)", "Discouraged", "Compulsory for doctors only"), 1),
            Triple("Regarding modesty (Satar) during physical examination in Islamic nursing practice, the nurse should:",
                listOf("Expose the entire body at once", "Expose only the specific anatomical area required for assessment while keeping remaining body covered", "Ignore gender preferences completely", "Perform exam in public view"), 1),
            Triple("In Islamic bioethics, euthanasia (mercy killing / active termination of life) is universally ruled as:",
                listOf("Permissible upon patient request", "Strictly prohibited (Haram) as taking human life belongs solely to Allah", "Recommended in terminally ill", "Optional"), 1),
            Triple("Withholding or withdrawing futile artificial life support in brain-dead patients when medical recovery is impossible is considered in Islamic bioethics as:",
                listOf("Active murder", "Permissible passive cessation of futile treatment (Palliative care)", "Mandatory for all patients", "Unlawful"), 1),
            Triple("Organ donation after brain death to save another human life is declared by major Islamic Fiqh councils (such as OIC Islamic Fiqh Academy) as:",
                listOf("Strictly Haram", "Permissible as an act of altruism provided commercial sale of organs is forbidden", "Compulsory", "Illegal"), 1),
            Triple("In Islamic clinical practice, providing cross-gender nursing care when a same-gender nurse is unavailable is:",
                listOf("Prohibited under all circumstances", "Permissible under the principle of necessity (Darurah)", "Punishable", "A sin"), 1),
            Triple("In Islamic ethics, blood transfusion to save a bleeding patient's life is:",
                listOf("Forbidden", "Permissible and life-saving", "Discouraged", "Harmful"), 1),
            Triple("Patient autonomy in Islamic nursing care requires respect for the patient's refusal of treatment EXCEPT when:",
                listOf("Patient has a common cold", "Patient lacks mental competence / decision-making capacity or poses severe public health threat", "Patient is elderly", "Family disagrees"), 1),
            Triple("The concept of 'Amanah' (Trust) in professional nursing ethics means:",
                listOf("Earning high salary", "Viewing patient care and clinical duties as a sacred trust held accountable before Allah and society", "Fulfilling shift hours only", "Delegating all tasks"), 1),
            Triple("Whistleblowing in nursing ethics refers to:",
                listOf("Reporting unsafe, unethical, or illegal clinical practices to appropriate authorities to protect patient safety", "Gossiping about colleagues", "Telling secrets to patients", "Noise making"), 0),
            Triple("Professional negligence resulting in harm or injury to a patient is legally defined as:",
                listOf("Assault", "Malpractice", "Battery", "Slander"), 1),
            Triple("An intentional threat or attempt to inflict bodily harm on a patient that creates reasonable apprehension is legally defined as:",
                listOf("Battery", "Assault", "Negligence", "Defamation"), 1),
            Triple("Actual unconsented, intentional physical contact or touching of a patient without legal justification constitutes:",
                listOf("Assault", "Battery", "Fraud", "Libel"), 1),
            Triple("False oral statements that damage a colleague's professional reputation are legally categorized as:",
                listOf("Libel", "Slander", "Battery", "Negligence"), 1),
            Triple("False written documentation or statements damaging a person's reputation constitute:",
                listOf("Slander", "Libel", "Assault", "Perjury"), 1),
            Triple("Restraining a competent patient against their explicit will without legal or medical authorization constitutes:",
                listOf("Good nursing care", "False Imprisonment", "Malpractice", "Beneficence"), 1),
            Triple("The legal doctrine 'Respondeat Superior' means:",
                listOf("The nurse is solely responsible", "The employer (hospital) is legally held liable for negligent acts committed by employees within scope of employment", "Doctors are immune", "Patients waive rights"), 1),
            Triple("The PNC (Pakistan Nursing Council) Code of Conduct mandates that Registered Nurses must maintain professional competence through:",
                listOf("Initial diploma only", "Continuous Professional Development (CPD) and lifelong learning", "Social media posts", "Political affiliation"), 1),
            Triple("In end-of-life Islamic nursing care, positioning a dying patient towards the Qiblah and encouraging quiet recitation of the Shahada is an act of:",
                listOf("Physical restraint", "Spiritual support and culturally sensitive holistic care", "Medical intervention", "Futile care"), 1)
        )

        isl1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 3,
                    subjectName = "Islamic Studies / Ethics",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Islamic Studies & Bioethics (ISL-635) concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU ISL-635 / Islamic Bioethics & PNC Code of Ethics"
                )
            )
        }

        // Add 100 extra questions for EACH subject in Semester 3 (500 extra questions)
        questions.addAll(KpSemester3PlusQuestionBank.getQuestions(idCounter))

        return questions
    }
}
