package com.example.ui.screens

/**
 * KHYBER PAKHTUNKHWA (KP) BSN SEMESTER 1 QUESTION BANK
 * 200+ Comprehensive Questions for KMU Peshawar / PNC Syllabus
 * Subjects:
 * 1. Fundamentals of Nursing I (FON-611) - 50 Qs
 * 2. Anatomy & Physiology I (ANAT-612) - 50 Qs
 * 3. Biochemistry for Nurses (BIO-613) - 40 Qs
 * 4. Microbiology (MIC-614) - 40 Qs
 * 5. English I - Functional English (ENG-615) - 30 Qs
 * Total = 210 Questions
 */
object KpSemester1QuestionBank {

    fun getQuestions(startId: Int): List<KpSemesterQuestion> {
        var idCounter = startId
        val questions = mutableListOf<KpSemesterQuestion>()

        // ==========================================
        // 1. FUNDAMENTALS OF NURSING I (FON-611) - 50 Qs
        // ==========================================
        val fon1Data = listOf(
            Triple("According to Nursing Process (ADPIE), which step involves collecting subjective and objective data?",
                listOf("Planning", "Assessment", "Diagnosis", "Evaluation"), 1),
            Triple("Which of the following is an example of subjective data collected during nursing assessment?",
                listOf("Blood pressure reading of 130/80 mmHg", "Patient statement: 'I feel dizzy and nauseous'", "Serum potassium level of 4.0 mEq/L", "Heart rate of 88 beats per minute"), 1),
            Triple("The nurse measures an adult patient's oral temperature as 37.0°C (98.6°F). How should this reading be categorized?",
                listOf("Hypothermia", "Normal body temperature", "Low-grade fever", "Hyperpyrexia"), 1),
            Triple("When measuring radial pulse, the nurse notes an irregular rhythm. What is the most appropriate next action?",
                listOf("Document the finding as normal", "Count the apical pulse for one full minute", "Recheck the radial pulse for 15 seconds", "Administer atropine immediately"), 1),
            Triple("A normal adult resting respiratory rate ranges between:",
                listOf("8 to 12 breaths per minute", "12 to 20 breaths per minute", "22 to 28 breaths per minute", "30 to 40 breaths per minute"), 1),
            Triple("Which korotkoff sound phase corresponds to the systolic blood pressure reading?",
                listOf("Phase I - First clear tapping sound", "Phase II - Soft swishing sound", "Phase III - Crisp loud sound", "Phase V - Disappearance of sound"), 0),
            Triple("To obtain an accurate blood pressure reading, the width of the inflatable cuff bladder should be approximately what percentage of the arm circumference?",
                listOf("20%", "40%", "60%", "80%"), 1),
            Triple("Which technique of physical assessment involves using the sense of touch to feel texture, size, and temperature?",
                listOf("Inspection", "Auscultation", "Palpation", "Percussion"), 2),
            Triple("The nurse is washing hands before performing a sterile dressing change. Hand hygiene should be performed for at least:",
                listOf("5 seconds", "20 seconds", "60 seconds", "3 minutes"), 1),
            Triple("Which position is best suited for a patient experiencing dyspnea or acute respiratory distress?",
                listOf("Trendelenburg position", "Prone position", "Fowler's or High-Fowler's position", "Sims' position"), 2),
            Triple("Florence Nightingale's Environmental Theory emphasizes which key element of patient care?",
                listOf("Self-care deficit", "Fresh air, cleanliness, light, and pure water", "Behavioral system stability", "Transcultural nursing care"), 1),
            Triple("Which level of infection control destroys all pathogenic microorganisms including bacterial spores?",
                listOf("Sanitization", "Disinfection", "Sterilization", "Antisepsis"), 2),
            Triple("The nurse observes non-blanchable erythema over a patient's sacrum. What stage pressure injury is this?",
                listOf("Stage 1", "Stage 2", "Stage 3", "Stage 4"), 0),
            Triple("In Maslow's Hierarchy of Needs, which human need must be met first before higher-level needs can be satisfied?",
                listOf("Self-actualization", "Love and belonging", "Physiological needs (air, water, food)", "Self-esteem"), 2),
            Triple("When placing an occupied bed in a low position with side rails raised for a confused patient, the nurse is primarily ensuring:",
                listOf("Patient comfort", "Patient safety and fall prevention", "Time efficiency", "Proper body mechanics"), 1),
            Triple("A patient has a body temperature of 39.2°C (102.5°F). The medical term for fever is:",
                listOf("Hypothermia", "Pyrexia", "Eupnea", "Bradypnea"), 1),
            Triple("Which pulse site is used during adult CPR resuscitation checks?",
                listOf("Radial pulse", "Brachial pulse", "Carotid pulse", "Popliteal pulse"), 2),
            Triple("An adult patient's blood pressure is 150/95 mmHg. This reading is categorized as:",
                listOf("Normal blood pressure", "Elevated blood pressure", "Stage 2 Hypertension", "Hypotension"), 2),
            Triple("Which phase of the therapeutic nurse-patient relationship involves establishing trust and boundaries?",
                listOf("Orientation phase", "Working phase", "Termination phase", "Pre-interaction phase"), 0),
            Triple("Personal Protective Equipment (PPE) removal order (doffing) should generally start with:",
                listOf("Mask / Respirator", "Gloves", "Gown", "Goggles / Face shield"), 1),
            Triple("In nursing diagnosis, NANDA stands for:",
                listOf("National American Nurse Development Association", "North American Nursing Diagnosis Association", "National Alliance for Nursing Diagnosis Assessment", "New Association of Nursing Diagnostics"), 1),
            Triple("When transferring a patient from bed to wheelchair, where should the wheelchair be placed?",
                listOf("At the foot of the bed on the weaker side", "At a 45-degree angle to the bed on the patient's stronger side", "Directly behind the nurse", "Parallel to the bed on the weaker side"), 1),
            Triple("Which range represents normal arterial blood oxygen saturation (SpO2) in a healthy adult?",
                listOf("85% - 90%", "91% - 94%", "95% - 100%", "70% - 80%"), 2),
            Triple("Palpating a bounding pulse is documented on a standard 0 to 4+ numerical scale as:",
                listOf("1+", "2+", "3+", "4+"), 3),
            Triple("Which factor increases body temperature?",
                listOf("Sleep", "Fasting", "Strenuous exercise and infection", "Hypothyroidism"), 2),
            Triple("Orthostatic hypotension is defined as a drop in SBP of at least how many mmHg upon standing?",
                listOf("5 mmHg", "10 mmHg", "20 mmHg", "40 mmHg"), 2),
            Triple("Which heart sound (S1) is produced by the closure of which valves?",
                listOf("Aortic and Pulmonic valves", "Mitral and Tricuspid (AV) valves", "Eustachian valves", "Foramen ovale"), 1),
            Triple("A patient with an axillary temperature reading of 36.5°C likely has an estimated oral temperature of:",
                listOf("36.0°C", "37.0°C", "38.0°C", "39.0°C"), 1),
            Triple("The primary purpose of using surgical aseptic technique is to:",
                listOf("Reduce the number of microorganisms", "Keep an area completely free of all microorganisms and spores", "Clean skin before bath", "Wash linens"), 1),
            Triple("Which principle applies to maintaining a sterile field?",
                listOf("Sterile items below waist level remain sterile", "Prolonged exposure to air contaminates a sterile field", "Sterile objects touched by clean gloves remain sterile", "Moisture does not affect sterile drapes"), 1),
            Triple("In bedmaking, a mitered corner is made to:",
                listOf("Secure linens firmly under the mattress", "Look decorative only", "Allow patient leg movement", "Prevent pressure ulcers"), 0),
            Triple("Hypoventilation leads to which arterial blood gas alteration?",
                listOf("Respiratory Alkalosis", "Respiratory Acidosis", "Metabolic Acidosis", "Metabolic Alkalosis"), 1),
            Triple("The nurse uses percussion to assess the patient's lungs. Normal healthy lung tissue yields which percussion note?",
                listOf("Tympany", "Resonance", "Dullness", "Flatness"), 1),
            Triple("The nurse inspects a patient's skin and notices blue discoloration around lips. This condition is termed:",
                listOf("Jaundice", "Erythema", "Cyanosis", "Pallor"), 2),
            Triple("When carrying heavy objects, the nurse should maintain proper body mechanics by:",
                listOf("Bending at the waist with knees straight", "Holding objects close to the body center of gravity with knees bent", "Twisting the torso while lifting", "Lifting with back muscles"), 1),
            Triple("Which pulse point is located behind the knee?",
                listOf("Femoral pulse", "Popliteal pulse", "Posterior tibial pulse", "Dorsalis pedis pulse"), 1),
            Triple("The nurse uses a stethoscope bell to listen for low-pitched sounds such as:",
                listOf("Normal breath sounds", "Heart murmurs and vascular bruits", "High-pitched bowel sounds", "Systolic blood pressure"), 1),
            Triple("A nursing goal 'Patient will walk 50 feet with walker by Day 3' is an example of a SMART goal where 'M' stands for:",
                listOf("Measurable", "Meaningful", "Manageable", "Mandatory"), 0),
            Triple("Which factor prolongs wound healing in surgical patients?",
                listOf("High protein intake", "Adequate tissue perfusion", "Malnutrition and uncontrolled diabetes mellitus", "Normal vitamin C levels"), 2),
            Triple("The nurse is providing oral care to an unconscious patient. Which position prevents aspiration?",
                listOf("Supine position", "Side-lying (lateral) position with head turned to side", "Trendelenburg position", "High Fowler's position"), 1),
            Triple("Restraints should be evaluated and re-ordered by a provider at minimum every:",
                listOf("2 hours", "8 hours", "24 hours", "48 hours"), 2),
            Triple("Tachycardia in an adult is defined as a heart rate greater than:",
                listOf("80 bpm", "100 bpm", "120 bpm", "140 bpm"), 1),
            Triple("Which client position involves lying on abdomen with head turned to one side?",
                listOf("Supine", "Prone", "Dorsal recumbent", "Lithotomy"), 1),
            Triple("What is the primary rationale for performing Range of Motion (ROM) exercises?",
                listOf("To increase patient fatigue", "To prevent joint contractures and muscle atrophy", "To treat bone fractures", "To reduce body temperature"), 1),
            Triple("The chain of infection includes: Reservoir, Portal of Exit, Mode of Transmission, Portal of Entry, and:",
                listOf("Antibiotic resistance", "Susceptible host", "Sterile drape", "Vector control"), 1),
            Triple("The pulse deficit is calculated by taking the difference between:",
                listOf("Systolic and diastolic BP", "Apical pulse rate and radial pulse rate", "Oral and rectal temperature", "Inspiration and expiration rate"), 1),
            Triple("Cheyne-Stokes breathing is characterized by:",
                listOf("Rapid deep breathing without pauses", "Alternating periods of apnea and deep rapid breathing", "Slow shallow breathing", "Persistent wheezing"), 1),
            Triple("In active infection, which blood cell count typically increases (leukocytosis)?",
                listOf("Erythrocytes", "Thrombocytes", "White Blood Cells (WBCs)", "Reticulocytes"), 2),
            Triple("The term 'Nosocomial Infection' refers to an infection that is:",
                listOf("Present upon hospital admission", "Acquired during hospitalization (Healthcare-Associated Infection)", "Transmitted through food", "Genetic in origin"), 1),
            Triple("Which nursing theorist formulated the 'Self-Care Deficit Theory'?",
                listOf("Dorothea Orem", "Virginia Henderson", "Jean Watson", "Sr. Callista Roy"), 0)
        )

        fon1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 1,
                    subjectName = "Fundamentals of Nursing I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Fundamentals of Nursing I (FON-611) key concept. Correct answer option: '${opts[cIdx]}'. Aligned with PNC / KMU Semester 1 curriculum.",
                    reference = "KMU FON-611 / Potter & Perry Fundamentals of Nursing"
                )
            )
        }

        // ==========================================
        // 2. ANATOMY & PHYSIOLOGY I (ANAT-612) - 50 Qs
        // ==========================================
        val anat1Data = listOf(
            Triple("Which cellular organelle is known as the 'powerhouse of the cell' due to ATP production?",
                listOf("Ribosome", "Mitochondrion", "Golgi apparatus", "Lysosome"), 1),
            Triple("The cell membrane lipid bilayer is primarily composed of:",
                listOf("Triglycerides", "Phospholipids and proteins", "Glycogen", "Nucleic acids"), 1),
            Triple("Which anatomical term describes a position closer to the head?",
                listOf("Inferior", "Superior (Cranial)", "Posterior", "Distal"), 1),
            Triple("The anatomical plane that divides the body into equal left and right halves is the:",
                listOf("Transverse plane", "Coronal plane", "Midsagittal (Median) plane", "Oblique plane"), 2),
            Triple("How many bones are in the adult human skeleton?",
                listOf("180", "206", "250", "300"), 1),
            Triple("The outer connective tissue covering of a long bone is called:",
                listOf("Endosteum", "Perosteum", "Periosteum", "Epiphysis"), 2),
            Triple("Which cervical vertebra is commonly called the 'Atlas'?",
                listOf("C1", "C2", "C5", "C7"), 0),
            Triple("Which cervical vertebra acts as the 'Axis' enabling head rotation?",
                listOf("C1", "C2", "C4", "C7"), 1),
            Triple("How many pairs of true ribs (attached directly to sternum via costal cartilage) do humans have?",
                listOf("5 pairs", "7 pairs", "10 pairs", "12 pairs"), 1),
            Triple("The longest and strongest bone in the human upper extremity (arm) is the:",
                listOf("Radius", "Ulna", "Humerus", "Clavicle"), 2),
            Triple("The knee joint is an example of which type of synovial joint?",
                listOf("Ball and socket joint", "Hinge joint", "Pivot joint", "Saddle joint"), 1),
            Triple("The hip and shoulder joints are classified as which type of synovial joint?",
                listOf("Hinge joints", "Gliding joints", "Ball and socket joints", "Condyloid joints"), 2),
            Triple("Which structural type of muscle tissue is striated and under voluntary control?",
                listOf("Smooth muscle", "Cardiac muscle", "Skeletal muscle", "Visceral muscle"), 2),
            Triple("The functional contractile unit of a skeletal muscle fiber between two Z-lines is the:",
                listOf("Sarcolemma", "Sarcomere", "Sarcoplasmic reticulum", "Myofibril"), 1),
            Triple("Which neurotransmitter is released at the neuromuscular junction to initiate muscle contraction?",
                listOf("Dopamine", "Acetylcholine (ACh)", "Serotonin", "GABA"), 1),
            Triple("The central nervous system (CNS) comprises the:",
                listOf("Brain and Spinal Cord", "Cranial nerves and Spinal nerves", "Autonomic and Sympathetic system", "Somatic nerves"), 0),
            Triple("Which lobe of the cerebral cortex contains the primary visual cortex?",
                listOf("Frontal lobe", "Parietal lobe", "Temporal lobe", "Occipital lobe"), 3),
            Triple("The area of the brain responsible for balance, motor coordination, and posture is the:",
                listOf("Cerebrum", "Cerebellum", "Medulla oblongata", "Thalamus"), 1),
            Triple("Which part of the brainstem contains vital centers for heart rate, blood pressure, and respiration?",
                listOf("Pons", "Midbrain", "Medulla Oblongata", "Hypothalamus"), 2),
            Triple("How many pairs of cranial nerves originate from the human brain?",
                listOf("10 pairs", "12 pairs", "24 pairs", "31 pairs"), 1),
            Triple("Cranial Nerve I (CN I) is responsible for which sensory function?",
                listOf("Vision", "Olfaction (Smell)", "Hearing", "Taste"), 1),
            Triple("Cranial Nerve II (CN II) is the:",
                listOf("Olfactory nerve", "Optic nerve", "Oculomotor nerve", "Vagus nerve"), 1),
            Triple("Cranial Nerve X (CN X), which provides parasympathetic innervation to thoracic and abdominal organs, is the:",
                listOf("Trigeminal nerve", "Facial nerve", "Vagus nerve", "Glossopharyngeal nerve"), 2),
            Triple("The innermost layer of the meninges surrounding the brain and spinal cord is the:",
                listOf("Dura mater", "Arachnoid mater", "Pia mater", "Subdural space"), 2),
            Triple("Cerebrospinal fluid (CSF) is produced by the:",
                listOf("Astrocyte foot processes", "Choroid plexus", "Arachnoid villi", "Ependymal cilia"), 1),
            Triple("Which glial cell forms the myelin sheath around axons in the Central Nervous System?",
                listOf("Schwann cells", "Oligodendrocytes", "Microglia", "Astrocytes"), 1),
            Triple("Schwann cells form the myelin sheath in the:",
                listOf("Central Nervous System", "Peripheral Nervous System", "Brain ventricles", "Spinal grey matter"), 1),
            Triple("The epithelial tissue lining the human urinary bladder that allows stretching is:",
                listOf("Simple squamous epithelium", "Stratified columnar epithelium", "Transitional epithelium (Urothelium)", "Pseudostratified epithelium"), 2),
            Triple("Which tissue type connects muscle to bone?",
                listOf("Ligament", "Tendon", "Cartilage", "Fascia"), 1),
            Triple("Which tissue connects bone to bone across a joint?",
                listOf("Tendon", "Ligament", "Aponeurosis", "Synovium"), 1),
            Triple("Bone-forming cells responsible for matrix synthesis and mineralization are called:",
                listOf("Osteoclasts", "Osteoblasts", "Osteocytes", "Chondrocytes"), 1),
            Triple("Bone-resorbing cells that break down bone tissue are called:",
                listOf("Osteoblasts", "Osteoclasts", "Osteocytes", "Fibroblasts"), 1),
            Triple("The shaft of a long bone is anatomically termed the:",
                listOf("Epiphysis", "Diaphysis", "Metaphysis", "Periosteum"), 1),
            Triple("The epiphysis of long bones contains which type of bone tissue filled with red bone marrow?",
                listOf("Compact bone", "Spongy (Cancellous) bone", "Cortical bone", "Cartilaginous bone"), 1),
            Triple("Which muscle is the chief muscle of quiet respiration?",
                listOf("External intercostal", "Diaphragm", "Internal intercostal", "Sternocleidomastoid"), 1),
            Triple("The master endocrine gland controlled by the hypothalamus is the:",
                listOf("Thyroid gland", "Pituitary gland (Hypophysis)", "Adrenal gland", "Pancreas"), 1),
            Triple("Which hormone secreted by the posterior pituitary promotes water reabsorption in renal tubules?",
                listOf("Oxytocin", "Antidiuretic Hormone (ADH / Vasopressin)", "Growth Hormone", "Prolactin"), 1),
            Triple("Insulin is produced by which specific endocrine cells of the pancreas?",
                listOf("Alpha cells", "Beta cells", "Delta cells", "F cells"), 1),
            Triple("Glucagon, which elevates blood glucose levels, is secreted by pancreatic:",
                listOf("Alpha cells", "Beta cells", "Acinar cells", "Islet gamma cells"), 0),
            Triple("The functional basic unit of the kidney is the:",
                listOf("Neuron", "Nephron", "Glomerulus", "Alveolus"), 1),
            Triple("Which part of the brain regulates body temperature, hunger, thirst, and circadian rhythms?",
                listOf("Thalamus", "Hypothalamus", "Epithalamus", "Hippocampus"), 1),
            Triple("The microscopic structural unit of compact bone is the:",
                listOf("Trabecula", "Osteon (Haversian system)", "Canaliculus", "Lamella"), 1),
            Triple("The skin layer containing blood vessels, nerve endings, hair follicles, and sweat glands is the:",
                listOf("Epidermis", "Dermis", "Subcutaneous hypodermis", "Stratum corneum"), 1),
            Triple("Which epidermal pigment protects nuclear DNA from UV radiation damage?",
                listOf("Keratin", "Melanin", "Carotene", "Hemoglobin"), 1),
            Triple("Skin cells in the stratum basale that synthesize melanin are:",
                listOf("Keratinocytes", "Melanocytes", "Langerhans cells", "Merkel cells"), 1),
            Triple("Which region of the spinal cord has 8 pairs of spinal nerves despite having 7 vertebrae?",
                listOf("Cervical region", "Thoracic region", "Lumbar region", "Sacral region"), 0),
            Triple("How many pairs of thoracic spinal nerves are present in humans?",
                listOf("8 pairs", "12 pairs", "5 pairs", "1 pair"), 1),
            Triple("The primary site of nutrient absorption in the gastrointestinal tract is the:",
                listOf("Stomach", "Small Intestine (Jejunum/Ileum)", "Large Intestine", "Esophagus"), 1),
            Triple("Which gas exchange unit in the lung provides massive surface area for O2 and CO2 diffusion?",
                listOf("Bronchioles", "Alveoli", "Trachea", "Terminal bronchi"), 1),
            Triple("The normal resting cardiac output in an adult human is approximately:",
                listOf("2 Liters/min", "5 Liters/min", "10 Liters/min", "15 Liters/min"), 1)
        )

        anat1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 1,
                    subjectName = "Anatomy & Physiology I",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Anatomy & Physiology I (ANAT-612) core concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU ANAT-612 / Ross & Wilson Anatomy and Physiology"
                )
            )
        }

        // ==========================================
        // 3. BIOCHEMISTRY FOR NURSES (BIO-613) - 40 Qs
        // ==========================================
        val bio1Data = listOf(
            Triple("Which carbohydrate is the primary metabolic fuel source for human brain cells?",
                listOf("Fructose", "Glucose", "Galactose", "Sucrose"), 1),
            Triple("The storage polysaccharide form of glucose in human liver and skeletal muscle is:",
                listOf("Starch", "Glycogen", "Cellulose", "Chitin"), 1),
            Triple("Glycolysis takes place in which cellular compartment?",
                listOf("Mitochondrial matrix", "Cytoplasm (Cytosol)", "Endoplasmic reticulum", "Nucleolus"), 1),
            Triple("Under aerobic conditions, one molecule of glucose undergoing complete oxidation yields approximately how many ATP molecules?",
                listOf("2 ATP", "12 ATP", "30 to 32 ATP", "100 ATP"), 2),
            Triple("Under anaerobic conditions in human muscle tissue, pyruvate is converted into:",
                listOf("Acetyl-CoA", "Lactic Acid (Lactate)", "Ethanol", "Oxaloacetate"), 1),
            Triple("Proteins are polymers composed of monomeric units linked by peptide bonds called:",
                listOf("Monosaccharides", "Amino Acids", "Fatty Acids", "Nucleotides"), 1),
            Triple("How many standard amino acids are used by cells to synthesize proteins?",
                listOf("10", "20", "30", "64"), 1),
            Triple("An amino acid that cannot be synthesized by the human body and must be supplied in diet is termed:",
                listOf("Non-essential amino acid", "Essential amino acid", "Conditional amino acid", "Synthetic amino acid"), 1),
            Triple("Enzymes accelerate chemical reaction rates by:",
                listOf("Increasing activation energy", "Lowering activation energy required for reaction", "Changing equilibrium constant", "Consuming ATP"), 1),
            Triple("The non-protein organic molecule required by an enzyme for catalytic activity is a:",
                listOf("Coenzyme", "Apoenzyme", "Inhibitor", "Substrate"), 0),
            Triple("Which enzyme class catalyzes the breakdown of bonds using water (hydrolysis)?",
                listOf("Oxidoreductases", "Hydrolases", "Transferases", "Ligases"), 1),
            Triple("Normal human arterial blood pH range is tightly regulated between:",
                listOf("6.80 - 7.20", "7.35 - 7.45", "7.55 - 7.80", "8.00 - 8.50"), 1),
            Triple("The principal extracellular cation responsible for maintaining fluid balance and osmotic pressure is:",
                listOf("Potassium (K+)", "Sodium (Na+)", "Calcium (Ca2+)", "Magnesium (Mg2+)"), 1),
            Triple("The predominant intracellular cation essential for cardiac conduction and membrane resting potential is:",
                listOf("Sodium (Na+)", "Potassium (K+)", "Chloride (Cl-)", "Bicarbonate (HCO3-)"), 1),
            Triple("Normal serum potassium level ranges between:",
                listOf("1.0 - 2.5 mEq/L", "3.5 - 5.0 mEq/L", "6.0 - 7.5 mEq/L", "135 - 145 mEq/L"), 1),
            Triple("Normal serum sodium level in a healthy adult ranges between:",
                listOf("98 - 106 mEq/L", "135 - 145 mEq/L", "150 - 165 mEq/L", "3.5 - 5.0 mEq/L"), 1),
            Triple("Which hormone lowers blood glucose concentration by stimulating cellular glucose uptake and glycogen synthesis?",
                listOf("Glucagon", "Insulin", "Cortisol", "Epinephrine"), 1),
            Triple("Lipids are insoluble in water (hydrophobic) but soluble in organic solvents. The primary storage form of fat in adipose tissue is:",
                listOf("Phospholipids", "Triglycerides (Triacylglycerols)", "Cholesterol esters", "Sphingolipids"), 1),
            Triple("High-Density Lipoprotein (HDL) is often termed 'good cholesterol' because it:",
                listOf("Transports lipids from liver to arteries", "Transports excess cholesterol from peripheral tissues back to the liver", "Causes arterial plaque formation", "Increases blood pressure"), 1),
            Triple("Low-Density Lipoprotein (LDL) elevation increases the risk of:",
                listOf("Osteoporosis", "Atherosclerosis and Coronary Artery Disease", "Renal failure", "Liver cirrhosis"), 1),
            Triple("The process of breaking down fatty acids into Acetyl-CoA units in mitochondria is called:",
                listOf("Beta-oxidation", "Saponification", "Lipogenesis", "Glycolysis"), 0),
            Triple("Ketone bodies (acetoacetate, beta-hydroxybutyrate, acetone) are produced in the liver during:",
                listOf("High carbohydrate diet", "Prolonged starvation, fasting, or uncontrolled Diabetes Mellitus", "Excessive sleep", "Protein loading"), 1),
            Triple("DNA and RNA are polymers made of nucleotide monomer units consisting of a nitrogenous base, a pentose sugar, and a:",
                listOf("Amino group", "Phosphate group", "Fatty acid chain", "Glycerol molecule"), 1),
            Triple("Which nitrogenous base is present in RNA but absent in DNA?",
                listOf("Thymine", "Uracil", "Cytosine", "Guanine"), 1),
            Triple("Which nitrogen base pairs with Adenine in DNA double helix via two hydrogen bonds?",
                listOf("Guanine", "Thymine", "Cytosine", "Uracil"), 1),
            Triple("The process of synthesizing mRNA from a DNA template in the nucleus is termed:",
                listOf("Translation", "Transcription", "Replication", "Transformation"), 1),
            Triple("Protein synthesis occurring on ribosomes in cytosol using mRNA template is called:",
                listOf("Transcription", "Translation", "Transduction", "Mutation"), 1),
            Triple("Which enzyme prevents hydrogen bond reform during DNA replication by unwinding the double helix?",
                listOf("DNA Polymerase", "DNA Helicase", "DNA Ligase", "RNA Primase"), 1),
            Triple("Vitamin C (Ascorbic Acid) deficiency leads to collagen synthesis impairment causing:",
                listOf("Rickets", "Scurvy", "Pellagra", "Beri-beri"), 1),
            Triple("Vitamin D deficiency in children causes soft, deformed bones known as:",
                listOf("Osteomalacia", "Rickets", "Osteoporosis", "Scurvy"), 1),
            Triple("Which fat-soluble vitamin is essential for synthesizing blood clotting factors II, VII, IX, and X in the liver?",
                listOf("Vitamin A", "Vitamin D", "Vitamin E", "Vitamin K"), 3),
            Triple("Vitamin A deficiency primarily leads to:",
                listOf("Night blindness (Nyctalopia) and Xerophthalmia", "Bleeding gums", "Pernicious anemia", "Neuropathy"), 0),
            Triple("Deficiency of Vitamin B1 (Thiamine) leads to:",
                listOf("Pellagra", "Beri-beri", "Scurvy", "Rickets"), 1),
            Triple("Deficiency of Vitamin B3 (Niacin) causes Pellagra, characterized by the 3 Ds:",
                listOf("Dyspnea, Dysphagia, Dysuria", "Dermatitis, Diarrhea, Dementia", "Dehydration, Depression, Dizziness", "Diplopia, Dysarthria, Dyspepsia"), 1),
            Triple("Which iron-containing protein in red blood cells binds and transports oxygen?",
                listOf("Myoglobin", "Hemoglobin", "Albumin", "Transferrin"), 1),
            Triple("The main plasma protein responsible for maintaining oncotic pressure is:",
                listOf("Globulin", "Fibrinogen", "Albumin", "Prothrombin"), 2),
            Triple("Jaundice occurs due to hyperbilirubinemia. Bilirubin is the breakdown product of:",
                listOf("Cholesterol", "Heme portion of Hemoglobin", "Nucleic acids", "Triglycerides"), 1),
            Triple("Which organ is the primary site for urea synthesis (urea cycle) from toxic ammonia?",
                listOf("Kidney", "Liver", "Spleen", "Pancreas"), 1),
            Triple("The normal fasting blood glucose level in a healthy adult ranges between:",
                listOf("40 - 60 mg/dL", "70 - 100 mg/dL", "140 - 200 mg/dL", "200 - 300 mg/dL"), 1),
            Triple("Glycated Hemoglobin (HbA1c) reflects average blood glucose control over the preceding:",
                listOf("24 hours", "1 week", "2 to 3 months (8-12 weeks)", "1 year"), 2)
        )

        bio1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 1,
                    subjectName = "Biochemistry for Nurses",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Biochemistry (BIO-613) key concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU BIO-613 / Harper's Illustrated Biochemistry"
                )
            )
        }

        // ==========================================
        // 4. MICROBIOLOGY (MIC-614) - 40 Qs
        // ==========================================
        val mic1Data = listOf(
            Triple("Which father of microbiology developed germ theory and rabies vaccine?",
                listOf("Robert Koch", "Louis Pasteur", "Antonie van Leeuwenhoek", "Alexander Fleming"), 1),
            Triple("Who discovered penicillin, the first true antibiotic, from Penicillium mold?",
                listOf("Louis Pasteur", "Alexander Fleming", "Edward Jenner", "Robert Koch"), 1),
            Triple("Spherical bacteria arranged in clusters resembling bunches of grapes are classified as:",
                listOf("Streptococci", "Staphylococci", "Bacilli", "Spirilla"), 1),
            Triple("Spherical bacteria arranged in chains are classified as:",
                listOf("Staphylococci", "Streptococci", "Diplococci", "Vibrios"), 1),
            Triple("Rod-shaped bacteria are termed:",
                listOf("Cocci", "Bacilli", "Spirilla", "Spirochetes"), 1),
            Triple("Comma-shaped bacteria causing cholera belong to the genus:",
                listOf("Salmonella", "Vibrio (Vibrio cholerae)", "Shigella", "Campylobacter"), 1),
            Triple("Gram staining primary stain that turns Gram-positive bacteria purple is:",
                listOf("Safranin", "Crystal Violet", "Carbol Fuchsin", "Methylene Blue"), 1),
            Triple("The counterstain used in Gram staining that turns Gram-negative bacteria pink/red is:",
                listOf("Crystal Violet", "Safranin", "Iodine", "Malachite Green"), 1),
            Triple("Acid-fast staining (Ziehl-Neelsen stain) is used to detect which organism due to mycolic acid in cell wall?",
                listOf("Staphylococcus aureus", "Mycobacterium tuberculosis", "Escherichia coli", "Streptococcus pneumoniae"), 1),
            Triple("Bacterial endospores are extremely resistant structures formed primarily by species of:",
                listOf("Bacillus and Clostridium", "Escherichia and Klebsiella", "Streptococcus and Enterococcus", "Neisseria and Pseudomonas"), 0),
            Triple("Autoclaving sterilizes culture media and surgical items using moist heat under pressure at:",
                listOf("100°C for 5 min", "121°C at 15 psi for 15-20 min", "160°C dry heat for 10 min", "72°C for 15 seconds"), 1),
            Triple("Pasteurization of milk typically involves heating at 72°C for 15 seconds. This process:",
                listOf("Kills all bacterial spores completely", "Kills pathogenic vegetative microbes without destroying milk quality", "Sterilizes milk permanently", "Freezes milk pathogens"), 1),
            Triple("Organisms that require oxygen for growth are termed:",
                listOf("Obligate anaerobes", "Obligate aerobes", "Facultative anaerobes", "Microaerophiles"), 1),
            Triple("Organisms that are killed in the presence of oxygen (e.g. Clostridium tetani) are:",
                listOf("Obligate aerobes", "Obligate anaerobes", "Facultative anaerobes", "Capnophiles"), 1),
            Triple("Escherichia coli (E. coli) normally resides as flora in human:",
                listOf("Stomach", "Large Intestine (Colon)", "Respiratory tract", "Bloodstream"), 1),
            Triple("Which organism is the leading cause of uncomplicated Urinary Tract Infections (UTIs)?",
                listOf("Staphylococcus aureus", "Escherichia coli", "Pseudomonas aeruginosa", "Candida albicans"), 1),
            Triple("Hospital-acquired infections associated with green pus and sweet grape-like odor are caused by:",
                listOf("Pseudomonas aeruginosa", "Streptococcus pyogenes", "Clostridium perfringens", "Proteus mirabilis"), 0),
            Triple("Methicillin-Resistant Staphylococcus Aureus (MRSA) is resistant to beta-lactam antibiotics due to altered:",
                listOf("Penicillin-Binding Protein (PBP2a)", "Ribosomal RNA 50S subunit", "DNA gyrase", "Outer membrane porin"), 0),
            Triple("Clostridium difficile (C. diff) infection presents with severe diarrhea following antibiotic use. Hand hygiene requires:",
                listOf("Alcohol gel hand rub", "Washing hands with soap and water to physically remove spores", "Using sterile gloves only", "Chlorhexidine dip"), 1),
            Triple("Viruses are obligate intracellular parasites containing either DNA or RNA surrounded by a protein coat called a:",
                listOf("Capsid", "Envelope", "Peptidoglycan wall", "Capsule"), 0),
            Triple("Human Immunodeficiency Virus (HIV) selectively infects and destroys which immune cells?",
                listOf("CD4+ T Helper Lymphocytes", "CD8+ Cytotoxic T cells", "B Lymphocytes", "Neutrophils"), 0),
            Triple("Hepatitis B Virus (HBV) transmission occurs primarily through:",
                listOf("Fecal-oral route", "Blood, contaminated needles, and sexual contact", "Airborne droplets", "Insect vectors"), 1),
            Triple("Hepatitis A Virus (HAV) transmission occurs primarily via:",
                listOf("Blood transfusion", "Fecal-oral contaminated food/water route", "Sexual contact", "Airborne dust"), 1),
            Triple("Fungi that can exist as either unicellular yeast or multicellular mold depending on temperature are called:",
                listOf("Monomorphic fungi", "Dimorphic fungi", "Protozoa", "Helminths"), 1),
            Triple("Candida albicans causes oral thrush and vaginal yeast infections. It is classified as a:",
                listOf("Bacterium", "Fungal yeast", "Virus", "Protozoan"), 1),
            Triple("Malaria is caused by Plasmodium species transmitted to humans through the bite of infected female:",
                listOf("Aedes mosquitoes", "Anopheles mosquitoes", "Culex mosquitoes", "Tsetse flies"), 1),
            Triple("Dengue virus is transmitted by female mosquitoes of the genus:",
                listOf("Anopheles", "Aedes (Aedes aegypti)", "Culex", "Phlebotomus"), 1),
            Triple("Entamoeba histolytica causes amoebic dysentery characterized by stool containing:",
                listOf("Watery clear fluid", "Blood and mucus with trophozoites", "High fat oil droplets", "Rice-water appearance"), 1),
            Triple("The primary immune response involves initial production of which immunoglobulin antibody class?",
                listOf("IgG", "IgM", "IgA", "IgE"), 1),
            Triple("The most abundant antibody in serum that crosses the placenta to provide passive fetal immunity is:",
                listOf("IgA", "IgG", "IgM", "IgE"), 1),
            Triple("Which immunoglobulin is abundant in body secretions (saliva, tears, colostrum, mucosal surfaces)?",
                listOf("IgG", "IgA", "IgE", "IgD"), 1),
            Triple("Which antibody mediates allergic reactions and type I hypersensitivity by triggering histamine release from mast cells?",
                listOf("IgG", "IgE", "IgM", "IgA"), 1),
            Triple("Natural Active Immunity is acquired through:",
                listOf("Vaccination with toxoids", "Infection and recovery from disease", "Transplacental maternal IgG transfer", "IVIG administration"), 1),
            Triple("Artificial Active Immunity is acquired through:",
                listOf("Maternal colostrum feeding", "Administration of vaccines (attenuated/killed antigen)", "Antivenom injection", "Infection recovery"), 1),
            Triple("Innate immunity provides:",
                listOf("Memory T cell response", "Non-specific first-line physiological barriers (skin, mucous membranes, lysozyme)", "Antibody production after 2 weeks", "Monoclonal therapy"), 1),
            Triple("Which phagocytic white blood cells are the first responders arriving in large numbers at acute bacterial infection sites?",
                listOf("Eosinophils", "Neutrophils", "Basophils", "Monocytes"), 1),
            Triple("Which immune cells differentiate into plasma cells capable of secreting antibodies?",
                listOf("T Helper Lymphocytes", "B Lymphocytes", "NK cells", "Macrocytes"), 1),
            Triple("Tuberculosis screening skin test (Mantoux test) involves intradermal injection of Purified Protein Derivative (PPD) and is read after:",
                listOf("10 minutes", "24 hours", "48 to 72 hours", "1 week"), 2),
            Triple("Bacterial capsule functions primarily to:",
                listOf("Help bacteria swim", "Protect bacteria against phagocytosis by immune cells", "Enable ATP synthesis", "Form endospores"), 1),
            Triple("Nosocomial infections are also known as:",
                listOf("Community-acquired infections", "Healthcare-Associated Infections (HAIs)", "Idiopathic infections", "Congenital defects"), 1)
        )

        mic1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 1,
                    subjectName = "Microbiology",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "Microbiology (MIC-614) core concept. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU MIC-614 / Jawetz Medical Microbiology"
                )
            )
        }

        // ==========================================
        // 5. ENGLISH I - FUNCTIONAL ENGLISH (ENG-615) - 30 Qs
        // ==========================================
        val eng1Data = listOf(
            Triple("In English grammar, a word that modifies or describes a noun or pronoun is called an:",
                listOf("Adverb", "Adjective", "Preposition", "Conjunction"), 1),
            Triple("Identify the sentence with correct subject-verb agreement:",
                listOf("The team of nurses are arriving now.", "The nurse administer medications daily.", "The list of patient vital signs is updated hourly.", "Neither the patient nor the family members knows."), 2),
            Triple("What is the prefix meaning 'under' or 'below' in medical terminology?",
                listOf("Hyper-", "Sub-", "Poly-", "Tachy-"), 1),
            Triple("The medical suffix '-itis' signifies:",
                listOf("Surgical removal", "Inflammation", "Tumor or mass", "Enlargement"), 1),
            Triple("The medical suffix '-ectomy' signifies:",
                listOf("Surgical incision", "Surgical removal or excision", "Visual examination", "Creation of an opening"), 1),
            Triple("The root word 'Cardi/o' refers to which organ?",
                listOf("Brain", "Heart", "Liver", "Kidney"), 1),
            Triple("The medical term 'Dyspnea' means:",
                listOf("Difficulty swallowing", "Difficulty breathing or shortness of breath", "Painful urination", "Fast heart rate"), 1),
            Triple("The medical abbreviation 'NPO' stands for:",
                listOf("Nil Per Os (Nothing by mouth)", "New Patient Order", "Non-Prescription Option", "No Physical Operations"), 0),
            Triple("The abbreviation 'PRN' on a medication order means:",
                listOf("As needed", "Every morning", "Before meals", "Immediately"), 0),
            Triple("The abbreviation 'STAT' on a prescription order means:",
                listOf("At bedtime", "Immediately / Right now", "Twice a day", "After meals"), 1),
            Triple("In the sentence 'The nurse carefully checked the IV line', the word 'carefully' functions as an:",
                listOf("Adjective", "Adverb", "Noun", "Preposition"), 1),
            Triple("Choose the passive voice equivalent of: 'The doctor performed the surgery.'",
                listOf("The surgery was performed by the doctor.", "The doctor was performing surgery.", "Surgery is performing doctor.", "The doctor performed surgery."), 0),
            Triple("What is the synonym for the medical term 'Etiology'?",
                listOf("Treatment", "Cause or origin of a disease", "Prognosis", "Prevention"), 1),
            Triple("What is the antonym of 'Benign' in oncology terminology?",
                listOf("Harmless", "Malignant", "Acute", "Chronic"), 1),
            Triple("The prefix 'Tachy-' in medical terminology means:",
                listOf("Slow", "Fast or rapid", "Difficult", "Equal"), 1),
            Triple("The prefix 'Brady-' means:",
                listOf("Fast", "Slow", "Absent", "Large"), 1),
            Triple("The root word 'Nephr/o' or 'Ren/o' refers to:",
                listOf("Liver", "Kidney", "Lungs", "Stomach"), 1),
            Triple("The root word 'Hepat/o' refers to:",
                listOf("Heart", "Liver", "Spleen", "Pancreas"), 1),
            Triple("The suffix '-ology' means:",
                listOf("Study or science of", "Disease condition", "Surgical repair", "Incision"), 0),
            Triple("The term 'Hypertension' contains the prefix 'Hyper-' which means:",
                listOf("Low or deficient", "Excessive or elevated", "Normal", "Beside"), 1),
            Triple("Choose the correctly punctuated clinical documentation note:",
                listOf("Patient reports severe pain, BP is 140/90 mmHg.", "patient reports severe pain BP is 140/90", "Patient reports severe pain BP is 140 90", "Patient report severe pain bp 140 90"), 0),
            Triple("A paragraph in academic clinical writing should always contain a clear:",
                listOf("Topic sentence stating main idea", "Random list of facts", "Poetic rhyme", "Dialogue only"), 0),
            Triple("The term 'Tachypnea' means:",
                listOf("Slow heart rate", "Rapid breathing rate", "Absence of breathing", "Normal respiration"), 1),
            Triple("The suffix '-scopy' means:",
                listOf("Visual examination with an instrument", "Surgical destruction", "Suture", "Pain"), 0),
            Triple("The medical abbreviation 'BID' means:",
                listOf("Once daily", "Twice daily", "Three times daily", "Four times daily"), 1),
            Triple("The abbreviation 'QID' means:",
                listOf("Every 4 hours", "Four times a day", "Every night", "Every other day"), 1),
            Triple("The abbreviation 'AC' in medication orders means:",
                listOf("After meals", "Before meals (Ante Cibo)", "At bedtime", "With water"), 1),
            Triple("The abbreviation 'PC' in medication administration means:",
                listOf("Before meals", "After meals (Post Cibo)", "Per catheter", "Patient care"), 1),
            Triple("Identify the noun in the phrase: 'The sterile bandage was applied.'",
                listOf("Sterile", "Applied", "Bandage", "Was"), 2),
            Triple("The word 'Haematuria' translates literally to:",
                listOf("Pus in urine", "Blood in urine", "Glucose in urine", "Protein in urine"), 1)
        )

        eng1Data.forEach { (q, opts, cIdx) ->
            questions.add(
                KpSemesterQuestion(
                    id = idCounter++,
                    semesterNumber = 1,
                    subjectName = "English I (Functional English)",
                    question = q,
                    options = opts,
                    correctIndex = cIdx,
                    explanation = "English I (ENG-615) medical English & terminology. Correct answer: '${opts[cIdx]}'. Aligned with KMU BSN curriculum.",
                    reference = "KMU ENG-615 / English for Nursing & Medical Terminology"
                )
            )
        }

        // Add 100 extra questions for EACH subject in Semester 1 (500 extra questions)
        questions.addAll(KpSemester1PlusQuestionBank.getQuestions(idCounter))

        return questions
    }
}
