package com.example.ui.screens

/**
 * KHYBER PAKHTUNKHWA (KP) BSN SEMESTER 8 QUESTION BANK
 * 50+ Questions per subject (200+ total questions)
 * Subjects:
 * 1. Community Health Nursing III / Advanced Practicum - 50 Qs
 * 2. Nursing Seminar & Contemporary Issues in Nursing - 50 Qs
 * 3. Health Care Economics & Policy - 50 Qs
 * 4. Professional Elective / Disaster Management in Nursing - 50 Qs
 */
object KpSemester8QuestionBank {

    fun getQuestions(startId: Int): List<KpSemesterQuestion> {
        var idCounter = startId
        val questions = mutableListOf<KpSemesterQuestion>()

        fun addSubjectQs(
            sem: Int,
            subj: String,
            ref: String,
            rawList: List<Triple<String, List<String>, Int>>
        ) {
            for (item in rawList) {
                val correctOpt = item.second[item.third]
                questions.add(
                    KpSemesterQuestion(
                        id = idCounter++,
                        semesterNumber = sem,
                        subjectName = subj,
                        question = item.first,
                        options = item.second,
                        correctIndex = item.third,
                        explanation = "Correct answer: $correctOpt. Aligned with PNC / KMU Semester 8 curriculum.",
                        reference = ref
                    )
                )
            }
        }

        // ==========================================
        // 1. COMMUNITY HEALTH NURSING III - 50 Qs
        // ==========================================
        val chn3 = listOf(
            Triple("Primary Health Care (PHC) framework declared at Alma-Ata in 1978 defines PHC as essential health care based on practical, scientifically sound, and socially acceptable methods made universally accessible to individuals through their full:", listOf("Financial payment", "Participation and at a cost community can afford", "Government force", "Private health insurance"), 1),
            Triple("Which key principle of Primary Health Care emphasizes fair distribution of health services to all individuals regardless of social class or location?", listOf("Appropriate Technology", "Equitable Distribution", "Community Participation", "Intersectoral Coordination"), 1),
            Triple("Lady Health Workers (LHWs) program in Pakistan primary role at grassroots community level is to provide:", listOf("Complex surgical interventions", "Promotive, preventive, and basic curative maternal and child health services in rural households", "Tertiary ICU care", "Hospital administration"), 1),
            Triple("A single Lady Health Worker (LHW) in rural KP community is assigned to cover a population of approximately:", listOf("100 people", "1,000 population (approx 100-150 households)", "10,000 population", "50,000 population"), 1),
            Triple("Sustainable Development Goal (SDG) 3 established by United Nations aims to:", listOf("Achieve 100% urban housing", "Ensure healthy lives and promote well-being for all at all ages by 2030", "Eliminate all taxation", "Build highways"), 1),
            Triple("SDG Target 3.1 aims to reduce global Maternal Mortality Ratio (MMR) to less than:", listOf("500 per 100,000 live births", "70 per 100,000 live births by 2030", "10 per 100,000", "200 per 100,000"), 1),
            Triple("SDG Target 3.2 aims to end preventable deaths of newborns and children under 5 years, targeting neonatal mortality below:", listOf("50 per 1,000 live births", "12 per 1,000 live births", "25 per 1,000 live births", "5 per 1,000"), 1),
            Triple("Community Needs Assessment initial step in public health project planning involves:", listOf("Implementing intervention", "Collecting baseline epidemiological, demographic, and socioeconomic data from community", "Evaluating outcomes", "Publishing news release"), 1),
            Triple("Windshield Survey in community health nursing assessment involves:", listOf("Driving/walking through a community to systematically observe environmental, housing, and social conditions", "Reviewing hospital charts", "Conducting laboratory blood tests", "Distributing online forms"), 0),
            Triple("Integrated Management of Neonatal and Childhood Illness (IMNCI) strategy integrates clinical assessment with:", listOf("High-cost surgery", "Nutrition, immunization, disease prevention, and caregiver counseling at primary level", "Hospitalization for all", "Private clinic referrals"), 1),
            Triple("Under IMNCI guidelines, a child presenting with cough or difficult breathing AND chest indrawing or general danger signs is classified as:", listOf("No Pneumonia (cough or cold)", "Pneumonia", "Severe Pneumonia or Very Severe Disease (requiring urgent referral)", "Asthma mild"), 2),
            Triple("IMNCI General Danger Signs requiring urgent hospital referral in a child aged 2 months to 5 years include inability to drink/breastfeed, persistent vomiting, convulsions during illness, and:", listOf("Mild fever", "Lethargy or Unconsciousness", "Skin rash", "Runny nose"), 1),
            Triple("In community water sanitation, slow sand filtration method removes bacteria and suspended matter primarily through:", listOf("Boiling heat", "Biological schmutzdecke layer and mechanical straining", "Heavy chemical dosing", "Ultraviolet light"), 1),
            Triple("Chlorination of drinking water requires a minimum contact time of how many minutes before consumption to ensure bacterial disinfection?", listOf("5 minutes", "30 minutes (with residual chlorine 0.2 - 0.5 mg/L)", "2 hours", "Instant 1 second"), 1),
            Triple("Biological Oxygen Demand (BOD) in environmental wastewater testing measures the amount of dissolved oxygen needed by organisms to:", listOf("Purify metals", "Decompose organic matter in water (higher BOD indicates higher pollution)", "Cool water temp", "Kill viruses"), 1),
            Triple("Occupational Health Hazard among agricultural workers in KP rural regions caused by pesticide exposure manifests acutely as:", listOf("Hyperglycemia", "Cholinergic crisis (miosis, profuse sweating, salivation, muscle fasciculations, and bronchospasm)", "Hypertension", "Constipation"), 1),
            Triple("Atropine Sulfate is the specific pharmacological antidote administered for acute poisoning caused by organophosphate:", listOf("Heavy metals", "Organophosphate Pesticides", "Rat poison warfarin", "Cyanide"), 1),
            Triple("Byssinosis ('Brown Lung Disease') is an occupational lung disease among textile mill workers caused by inhalation of:", listOf("Silica dust", "Cotton dust particles", "Asbestos fibers", "Coal dust"), 1),
            Triple("Silicosis is an occupational lung disease affecting stone cutters, miners, and brick kiln workers caused by inhalation of free crystalline:", listOf("Cotton dust", "Silica dust", "Iron oxide", "Barium"), 1),
            Triple("Asbestosis increases long-term risk of developing which fatal malignant neoplasm of the pleura?", listOf("Leukemia", "Mesothelioma", "Melanoma", "Glioblastoma"), 1),
            Triple("Occupational Audiometric testing screens workers exposed to hazardous workplace noise levels exceeding daily threshold of:", listOf("50 dB", "85 decibels (dBA) over an 8-hour shift", "120 dB", "30 dB"), 1),
            Triple("Community Mental Health Care paradigm shifts care from traditional institutional psychiatric asylums to:", listOf("Jails", "Deinstitutionalized community-based support, outpatient clinics, and integration into primary care", "Isolated camps", "Home lockup"), 1),
            Triple("School Health Nursing program key routine screening activity includes:", listOf("Perform major surgery", "Visual acuity testing (Snellen chart), hearing screening, nutritional tracking, and spinal scoliosis assessment", "X-ray screening", "Prescribing antibiotics"), 1),
            Triple("Lady Health Visitors (LHVs) in Pakistan healthcare hierarchy primarily supervise LHWs and provide maternal care at:", listOf("Tertiary Teaching Hospitals", "Basic Health Units (BHUs) and Rural Health Centers (RHCs)", "Federal Ministry", "Private Pharmacies"), 1),
            Triple("Basic Health Unit (BHU) in KP health infrastructure is designed to serve a catchment population of approximately:", listOf("1,000 people", "10,000 to 25,000 population", "100,000 people", "500,000 people"), 1),
            Triple("Rural Health Center (RHC) in KP healthcare system serves a population of 50,000 to 100,000 and provides inpatient bed capacity of:", listOf("No beds", "10 to 20 inpatient beds with basic lab and X-ray facilities", "500 beds", "100 ICU beds"), 1),
            Triple("District Headquarter (DHQ) Hospital provides secondary healthcare services including specialty care serving an entire:", listOf("Village", "District population (300,000 to 2 million people)", "Province total", "Union council"), 1),
            Triple("Health Promotion operational definition according to Ottawa Charter (1986) is the process of enabling people to:", listOf("Buy more medications", "Increase control over, and to improve, their health", "Depend on doctors", "Reduce tax payments"), 1),
            Triple("Ottawa Charter five key action areas for health promotion include Build Healthy Public Policy, Create Supportive Environments, Strengthen Community Action, Reorient Health Services, and:", listOf("Increase Hospital Charges", "Develop Personal Skills", "Build Private Clinics", "Mandate Insurance"), 1),
            Triple("Directly Observed Therapy (DOTS) in community TB management requires a trained healthcare worker or treatment supporter to:", listOf("Mail drugs to patient", "Observe the patient directly swallow every dose of anti-TB medication", "Call patient weekly", "Rely on patient memory"), 1),
            Triple("Polio Eradication Initiative in Pakistan utilizes supplementary immunization activities (SIAs) delivering which vaccine door-to-door to all children under 5?", listOf("Inactivated Polio Vaccine (IPV) IM", "Bivalent Oral Polio Vaccine (bOPV) drops", "Pentavalent vaccine", "BCG vaccine"), 1),
            Triple("Acute Flaccid Paralysis (AFP) surveillance requires reporting any child under 15 years presenting with sudden onset of floppy weakness within:", listOf("1 month", "24 hours to local health authority", "1 year", "6 months"), 1),
            Triple("Cold Chain breach during field immunization campaign compromises vaccine potency primarily due to exposure to excess heat or:", listOf("Darkness", "Freezing temperatures (for freeze-sensitive vaccines)", "Clean air", "Plastic containers"), 1),
            Triple("Malaria control vector management method 'Indoor Residual Spraying' (IRS) applies long-acting insecticide to:", listOf("Outdoor fields", "Indoor wall surfaces and roofs where adult mosquitoes rest after blood meal", "Drinking water tanks", "Vegetables"), 1),
            Triple("Long-Lasting Insecticidal Nets (LLINs) distributed in endemic districts of KP protect against nocturnal mosquito bites for up to:", listOf("1 month", "3 years or 20 washes", "1 week", "10 years"), 1),
            Triple("Dengue Source Reduction ('Larviciding' and environmental management) focuses on eliminating container breeding sites of Aedes mosquitoes containing:", listOf("Flowing river water", "Clean stagnant standing water (e.g. discarded tires, water pots, flower vases)", "Sewage water", "Muddy puddles"), 1),
            Triple("Nipah Virus outbreak prevention in public health emphasizes avoiding consumption of raw date palm sap contaminated by:", listOf("Rodents", "Fruit Bats (Pteropus species)", "Dogs", "Mosquitoes"), 1),
            Triple("Crimean-Congo Hemorrhagic Fever (CCHF) transmitted during Eid-ul-Adha animal handling in KP is spread via contact with infected blood or bite of:", listOf("Aedes mosquito", "Hyalomma Ticks", "Sandflies", "Fleas"), 1),
            Triple("Rabies post-exposure prophylaxis (PEP) for Category III bite wound (transdermal bite/scratches or mucosal contact) requires immediate wound washing with soap and water for 15 minutes, Rabies Vaccine, and:", listOf("Tetanus only", "Rabies Immunoglobulin (RIG) infiltrated around wound", "Oral penicillin", "Alcohol soak"), 1),
            Triple("Category I Rabies exposure (touching/feeding animals, licks on intact skin) requires:", listOf("Full PEP vaccine + RIG", "No post-exposure prophylaxis required (if history reliable)", "Immediate amputation", "Tetanus toxoid 3 doses"), 1),
            Triple("Community Health Nurse visiting a home discovers a child with severe dehydration from acute diarrhea. Immediate first-line home management instruction is to administer:", listOf("Loperamide anti-diarrheal syrup", "Oral Rehydration Salt (ORS) solution continuously alongside ongoing feeding and Zinc supplementation", "Ciprofloxacin antibiotic", "Withhold all fluids"), 1),
            Triple("WHO Low-Osmolarity ORS formula per Liter of clean water contains Sodium Chloride 2.6g, Glucose 13.5g, Potassium Chloride 1.5g, and:", listOf("Calcium Carbonate 3.0g", "Trisodium Citrate 2.9g", "Magnesium Sulfate 1.0g", "Zinc Oxide 2.0g"), 1),
            Triple("Oral Zinc supplementation administered for 10-14 days during acute diarrhea in young children functions to:", listOf("Change stool color", "Reduce severity and duration of diarrhea episode and prevent recurrences over next 2-3 months", "Induce sleep", "Stop vomiting instantly"), 1),
            Triple("Water Quality Testing parameter 'Faecal Coliforms' (E. coli count) per 100 mL of safe drinking water according to WHO guidelines must be:", listOf("Less than 100", "ZERO E. coli / 100 mL sample", "Less than 50", "10 or fewer"), 1),
            Triple("Composting latrine / Sanitary Pit Latrine should be constructed at a minimum horizontal distance from drinking water wells of at least:", listOf("5 meters", "15 to 30 meters (to prevent groundwater contamination)", "2 meters", "100 meters"), 1),
            Triple("Vector control for Sandfly (transmitting Leishmaniasis in KP) includes indoor residual spraying, mesh window screens, and using bed nets treated with:", listOf("Bleach", "Permethrin / Synthetic Pyrethroid insecticide", "Kerosene", "Salt water"), 1),
            Triple("In community epidemiology, 'Attack Rate' is a specialized form of incidence rate used during:", listOf("Chronic disease tracking", "An acute epidemic outbreak in a narrowly defined population over a short time (e.g. food poisoning outbreak)", "Annual census", "Birth rate count"), 1),
            Triple("Maternal and Child Health (MCH) clinic key performance indicator tracking antenatal coverage recommends every pregnant woman receive a MINIMUM of how many ANC visits?", listOf("1 visit", "4 ANC visits (WHO updated guidelines recommend 8 contacts)", "20 visits", "2 visits"), 1),
            Triple("Postnatal Care (PNC) timing critical for maternal/neonatal survival mandates first checkup within:", listOf("2 weeks", "First 24 hours post-delivery", "6 weeks", "10 days"), 1),
            Triple("Health Equity differs from Health Equality because Health Equity ensures that people receive resources according to their:", listOf("Identical equal amount regardless of need", "Specific needs to achieve equal health outcomes", "Age only", "Income rank"), 1)
        )
        addSubjectQs(8, "Community Health Nursing III", "KMU CHN-681 / Stanhope & Lancaster Public Health Nursing", chn3)

        // ==========================================
        // 2. NURSING SEMINAR & CONTEMPORARY ISSUES - 50 Qs
        // ==========================================
        val sem = listOf(
            Triple("Pakistan Nursing Council (PNC) established under the PNC Act is the statutory regulatory body responsible for:", listOf("Setting hospital prices", "Licensing, regulating nursing education curricula, and maintaining professional registry of nurses, midwives, and LHVs in Pakistan", "Manufacturing medical drugs", "Managing hospital budgets"), 1),
            Triple("Under PNC guidelines, mandatory requirement for maintaining valid nursing license registration to practice clinical nursing is:", listOf("Lifetime automatic license", "Periodic license renewal fulfilling Continuing Professional Development (CPD) credit hours", "Passing exam every year", "Paying hospital fee"), 1),
            Triple("Continuing Nursing Education (CNE) / CPD credit hours ensure that practicing nurses maintain current clinical competence and:", listOf("Earn higher interest", "Adapt to advancing healthcare technologies and evidence-based practice standards", "Avoid tax", "Retire early"), 1),
            Triple("Evidence-Based Practice (EBP) in nursing integrates best research evidence with clinical expertise and:", listOf("Hospital financial budget", "Patient values, preferences, and clinical context", "Physician personal habits", "Historical tradition alone"), 1),
            Triple("First step in the 7-step Evidence-Based Practice (EBP) process is:", listOf("Appraising evidence", "Cultivating a spirit of inquiry and asking the clinical question in PICO format", "Searching literature", "Changing hospital policy"), 1),
            Triple("Hierarchical Level 1 (highest level) of research evidence for clinical decision-making is derived from:", listOf("Expert opinion reports", "Systematic Reviews and Meta-Analyses of Randomized Controlled Trials (RCTs)", "Single descriptive study", "Case reports"), 1),
            Triple("Level VII (lowest level) in the evidence hierarchy consists of:", listOf("Cohort studies", "Opinion of authorities, expert committee reports, or consensus panels", "Well-designed RCTs", "Qualitative studies"), 1),
            Triple("Advance Healthcare Directive (Living Will) is a legal document that allows a competent individual to:", listOf("Divide personal financial assets", "State explicit preferences for future medical treatments (e.g. DNR orders, mechanical ventilation) in case they lose decision-making capacity", "Assign job roles", "Select hospital ward"), 1),
            Triple("Durable Power of Attorney for Healthcare (Healthcare Proxy) designates a named surrogate agent to:", listOf("Pay hospital bills", "Make medical treatment decisions on behalf of the patient when the patient becomes incapacitated", "Inherit property", "Discharge patient"), 1),
            Triple("Do Not Resuscitate (DNR) medical order written by physician following patient/family consultation mandates that in event of cardiac arrest, nurses must withhold:", listOf("All nursing care and hygiene", "Cardiopulmonary Resuscitation (CPR), endotracheal intubation, and defibrillation", "Pain medications", "IV fluids"), 1),
            Triple("Euthanasia defined as active administration of a lethal agent to intentionally end a patient's life to relieve suffering is legally in Pakistan:", listOf("Fully legal and encouraged", "ILLEGAL under Pakistan Penal Code and unethical under PNC code", "Permitted with nurse consent", "Permitted for elderly"), 1),
            Triple("Palliative Care core focus differs from curative treatment because Palliative Care aims to:", listOf("Prolong dying process at all costs", "Optimize Quality of Life and relieve pain/sufferings for patients facing life-threatening illness and their families", "Accelerate death", "Perform experimental trials"), 1),
            Triple("Hospice Care is a specialized sub-type of palliative care tailored for patients with a terminal prognosis of approximately:", listOf("5 years", "6 months or less to live", "10 years", "2 years"), 1),
            Triple("Bioethical dilemma of Resource Allocation during mass ventilator shortages requires balancing Utilitarian principle of doing the greatest good for:", listOf("The richest patients", "The greatest number of individuals", "Hospital directors", "Youngest nurses"), 1),
            Triple("Informed Consent legal validity requires three elements: Voluntariness, Capacity/Competence, and:", listOf("Cash deposit", "Adequate Information / Full Disclosure of risks, benefits, and alternatives", "Doctor presence only", "Police stamp"), 1),
            Triple("Therapeutic Misconception in clinical trials occurs when a research subject falsely believes that:", listOf("The trial is free", "An experimental research protocol is designed solely for their personal therapeutic benefit rather than testing a hypothesis", "They can leave anytime", "The nurse is a doctor"), 1),
            Triple("Digital Health / Tele-Nursing involves delivering nursing care, triage, and health education remotely using:", listOf("Paper mail", "Telecommunications, video consultations, and digital mobile technology", "In-person visits only", "Radio broadcasts"), 1),
            Triple("Health Information Exchange (HIE) allows secure electronic sharing of patient health records across different:", listOf("Social media platforms", "Healthcare organizations and clinical information systems to ensure continuity of care", "Public websites", "Financial banks"), 1),
            Triple("Electronic Health Record (EHR) adoption primary patient safety benefit is reducing:", listOf("Nurse salaries", "Medication administration errors, missing documentation, and adverse drug interactions", "Hospital size", "Patient stay time"), 1),
            Triple("Cybersecurity in nursing informatics mandates protecting electronic Protected Health Information (ePHI) against:", listOf("Software updates", "Unauthorized access, data breaches, and ransomware attacks in compliance with privacy laws", "Printing papers", "Backup saving"), 1),
            Triple("Compassion Fatigue among nurses caring for chronically or critically ill patients represents a combination of Secondary Traumatic Stress and:", listOf("High job satisfaction", "Burnout", "Physical fitness", "Financial prosperity"), 1),
            Triple("Moral Distress in nursing practice occurs when a nurse knows the ethically correct action to take but:", listOf("Lacks clinical knowledge", "Is prevented from taking that action due to institutional constraints, power dynamics, or legal rules", "Forgets care plan", "Lacks salary"), 1),
            Triple("Moral Injury in healthcare workers refers to deep psychological distress resulting from actions, or lack of actions, that violate their own:", listOf("Work schedule", "Deeply held moral values and ethical code", "Hospital guidelines", "Degree requirements"), 1),
            Triple("Nursing Shortage global impact according to International Council of Nurses (ICN) leads directly to increased nurse workload, burnout, and:", listOf("Lower patient mortality", "Increased patient mortality, adverse events, and nurse turnover", "Higher hospital profits", "Shorter waiting times"), 1),
            Triple("Workplace Workplace Violence against nurses in emergency departments mandates institutions establish clear policy of:", listOf("Ignoring minor assaults", "Zero Tolerance for verbal abuse, threats, or physical assault", "Forgiving attackers without report", "Working alone"), 1),
            Triple("Gender Disparity in nursing leadership manifests as under-representation of female nurses in senior executive positions despite women comprising the:", listOf("Minority of workforce", "Overwhelming majority of the professional nursing workforce", "Zero percent", "Doctor population"), 1),
            Triple("Cultural Humility in contemporary nursing practice requires continuous commitment to self-critique, recognizing power imbalances, and maintaining:", listOf("Dominance over patient", "Respectful, non-paternalistic partnerships with culturally diverse patients", "Standardized rules without exception", "Language superiority"), 1),
            Triple("Implicit Bias in healthcare delivery refers to unconscious attitudes or stereotypes that affect our understanding, actions, and decisions toward patient groups leading to:", listOf("Equal treatment", "Health disparities and unequal clinical outcomes", "Faster discharge", "Improved diagnosis"), 1),
            Triple("Genomic Nursing integrates knowledge of human genetics and genomics into patient assessment, risk identification, and personalized:", listOf("Blood donor selection", "Pharmacogenomics (tailoring drug therapies based on genetic profile)", "Hospital billing", "Surgical equipment"), 1),
            Triple("Interprofessional Education (IPE) occurs when nursing students learn with and from students of medicine, pharmacy, and allied health to foster:", listOf("Competition between professions", "Collaborative practice and team-based patient care", "Isolated working silos", "Professional rivalry"), 1),
            Triple("Safe Nurse-to-Patient Staffing Ratio legislation aims to mandate maximum number of patients assigned per nurse to protect:", listOf("Doctor break time", "Patient safety and quality of clinical nursing care", "Hospital profits", "Pharmaceutical sales"), 1),
            Triple("Nurse Practitioner (NP) role expansion in advanced practice nursing allows qualified master's/doctoral nurses to perform advanced clinical assessment, order diagnostic tests, and:", listOf("Audit financial books", "Prescribe medications and manage chronic illness within defined scope of practice", "Replace hospital board", "Operate blood banks"), 1),
            Triple("Clinical Nurse Specialist (CNS) primary role focuses on expert clinical practice, staff education, consultation, and leading:", listOf("Hospital security", "Evidence-based practice improvements and clinical quality outcomes in specialized patient populations", "Pharmacy billing", "Facility maintenance"), 1),
            Triple("Informatics Nurse Specialist primary responsibility is integrating nursing science with information science and computer science to manage and communicate:", listOf("Hospital social media", "Data, information, knowledge, and wisdom in nursing practice", "Payroll accounts", "Building repairs"), 1),
            Triple("Magnet Recognition Program '14 Forces of Magnetism' include Quality of Nursing Leadership, Organizational Structure, Management Style, Exemplary Professional Practice, and:", listOf("High Bed Capacity", "Empirical Quality Outcomes and Professional Development", "Private Investment", "Low Salaries"), 1),
            Triple("Incivility in academic nursing settings (student-faculty or peer) damages learning environments and requires clear institutional policies promoting:", listOf("Strict punishment without hearing", "Professional Civility, respectful discourse, and psychological safety", "Ignoring minor insults", "Failing students"), 1),
            Triple("Sleep Deprivation among shift-work nurses working 12-hour night shifts significantly increases risk of clinical errors, needle-stick injuries, and long-term:", listOf("Cardiovascular disease and metabolic syndrome", "Improved memory", "High energy", "Lower stress"), 0),
            Triple("Nurses' Code of Ethics provision emphasizing primary commitment to the patient mandates that nurse's loyalty belongs to the patient above:", listOf("Personal financial gain or employer pressure", "Patient's family", "Legal code", "Scientific research"), 0),
            Triple("Conscientious Objection in nursing allows a nurse to refuse participation in a procedure (e.g. elective abortion) if it conflicts with their deeply held moral/religious beliefs, PROVIDED that:", listOf("Patient is left unattended", "Patient safety is maintained and care is seamlessly transferred to another qualified nurse", "Nurse publicly scolds patient", "Procedure is cancelled"), 1),
            Triple("Futile Care / Medically Ineffective Treatment occurs when medical interventions offer no reasonable hope of clinical recovery or benefit, raising ethical concerns of:", listOf("Autonomy", "Non-maleficence (inflicting unnecessary pain/suffering during dying process)", "Justice", "Veracity"), 1),
            Triple("Global Health Nursing addresses cross-border health issues influenced by globalization, climate change, migration, and emerging:", listOf("Local construction", "Pandemic infectious disease threats", "Hospital parking", "Nursing uniforms"), 1),
            Triple("Climate Change impact on human health managed in public health nursing includes rising incidence of heat stroke, vector-borne disease expansion, and:", listOf("Decreased asthma", "Food insecurity, malnutrition, and extreme weather disaster displacement", "Lower allergies", "Cleaner air"), 1),
            Triple("One Health concept recognizes that human health is interconnected with the health of:", listOf("Hospitals and clinics", "Animals and the shared environment", "Monetary economies", "Computers"), 1),
            Triple("Zoonotic diseases (diseases transmitted from animals to humans) account for what percentage of all emerging infectious diseases globally?", listOf("10%", "60% to 75% (e.g. COVID-19, Rabies, Avian Flu, CCHF)", "5%", "100%"), 1),
            Triple("Planetary Health paradigm focuses on the health of human civilization and the state of natural ecological systems on which it depends, advocating for:", listOf("Industrial expansion", "Sustainable ecological practices to protect public health", "Deforestation", "Increased plastic use"), 1),
            Triple("Nurse-led Innovation and Entrepreneurship empowers nurses to design new clinical devices, digital health apps, and healthcare delivery models to solve:", listOf("Financial tax loops", "Unmet patient care needs and healthcare system inefficiencies", "Doctor shortages only", "Building design"), 1),
            Triple("Professional Nursing Identity development transitions a nursing student from novice to expert through clinical experience, reflective practice, and:", listOf("Memorizing textbooks only", "Internalization of nursing values, ethics, and professional standards", "Passing 1 exam", "Years of age"), 1),
            Triple("Patricia Benner's 'From Novice to Expert' model outlines five stages of clinical competence: Novice, Advanced Beginner, Competent, Proficient, and:", listOf("Master", "Expert", "Director", "Professor"), 1),
            Triple("In Benner's model, a 'Competent' nurse typically has how many years of clinical practice experience in the same setting?", listOf("1 month", "2 to 3 years (demonstrating conscious, deliberate care planning)", "10 years", "20 years"), 1),
            Triple("An 'Expert' nurse according to Benner no longer relies on explicit rules to connect understanding to action, operating with an intuitive grasp of clinical situations based on:", listOf("Guesswork", "Deep background of extensive clinical experience and pattern recognition", "Textbook reading", "Doctor orders"), 1)
        )
        addSubjectQs(8, "Nursing Seminar & Contemporary Issues", "KMU SEM-682 / Zerwekh Nursing Today", sem)

        // ==========================================
        // 3. HEALTH CARE ECONOMICS & POLICY - 50 Qs
        // ==========================================
        val eco = listOf(
            Triple("Healthcare Economics applies economic principles to evaluate the production, distribution, and consumption of:", listOf("Consumer goods", "Healthcare resources, services, and health outcomes", "Industrial machinery", "Agricultural crops"), 1),
            Triple("Scarcity in healthcare economics refers to the fundamental condition where limited healthcare resources cannot fulfill unlimited:", listOf("Disease rates", "Human health wants, needs, and demands", "Hospital beds", "Government budgets"), 1),
            Triple("Opportunity Cost in healthcare resource allocation represents the value of the:", listOf("Total money spent", "Next best alternative foregone when a specific resource allocation choice is made", "Interest rate", "Hospital invoice"), 1),
            Triple("Law of Demand in health economics dictates that, holding other factors constant, as the price of a health service increases, consumer demand for that service generally:", listOf("Increases", "Decreases", "Remains unchanged", "Doubles"), 1),
            Triple("Price Elasticity of Demand measures how responsive consumer demand for a healthcare service is to changes in:", listOf("Quality", "Price", "Hospital location", "Doctor age"), 1),
            Triple("Emergency life-saving medical care (e.g. acute myocardial infarction resuscitation) is classified economically as price:", listOf("Highly Elastic", "Inelastic (demand remains constant regardless of price)", "Zero value", "Luxury demand"), 1),
            Triple("Elective cosmetic procedures are economically classified as price:", listOf("Inelastic", "Elastic (demand changes significantly with price changes)", "Fixed cost", "Public good"), 1),
            Triple("Moral Hazard in health insurance occurs when an insured individual utilizes MORE healthcare services simply because their out-of-pocket cost is reduced by insurance coverage, leading to:", listOf("Under-utilization", "Over-utilization and inflated overall healthcare costs", "Lower insurance premiums", "Zero hospital visits"), 1),
            Triple("Adverse Selection in health insurance markets occurs when high-risk individuals (sick people) are more likely to purchase health insurance than low-risk healthy individuals, driving up:", listOf("Hospital beds", "Insurance premium costs and potentially causing market collapse", "Doctor salaries", "Tax rates"), 1),
            Triple("Co-payment (Copay) in health insurance is a fixed out-of-pocket fee paid by the insured patient at the time of receiving a service, designed to mitigate:", listOf("Adverse selection", "Moral hazard by giving patient financial responsibility", "Hospital profits", "Doctor turnover"), 1),
            Triple("Deductible in health insurance refers to the specific amount of money the insured patient must pay out-of-pocket BEFORE the insurance company begins paying claims:", listOf("Every month", "Annually / each coverage year", "At death", "Per prescription"), 1),
            Triple("Co-insurance is a cost-sharing arrangement where the insured patient pays a specified percentage (e.g. 20%) of the total medical bill while the insurer pays:", listOf("0%", "The remaining percentage (e.g. 80%)", "10%", "100%"), 1),
            Triple("Fee-For-Service (FFS) reimbursement model pays healthcare providers based on:", listOf("Number of healthy patients", "Each individual service, test, or procedure performed (encouraging volume over quality)", "Fixed annual salary", "Patient satisfaction"), 1),
            Triple("Capitation payment model pays a healthcare provider or hospital a fixed fee per patient enrolled per unit of time (Per Member Per Month) regardless of:", listOf("Patient enrollment", "Whether the patient seeks care or the volume of services provided (encouraging preventive care)", "Provider qualifications", "Hospital location"), 1),
            Triple("Diagnosis-Related Groups (DRGs) prospective payment system reimburses hospitals a fixed predetermined rate based on the patient's primary:", listOf("Length of hospital stay in days", "Diagnosis and severity classification upon admission", "Actual itemized supplies used", "Doctor specialty"), 1),
            Triple("Pay-for-Performance (P4P) value-based reimbursement links financial incentives to healthcare providers achieving specific targets in:", listOf("Number of surgeries performed", "Clinical quality outcomes, patient safety metrics, and patient satisfaction", "Total hospital revenue", "Drug prescription counts"), 1),
            Triple("Cost-Benefit Analysis (CBA) in health economics evaluates both program inputs (costs) and program outcomes (health benefits) measured in:", listOf("Life years gained only", "Monetary currency units (e.g. Dollars / Rupees)", "Quality-Adjusted Life Years (QALYs)", "Natural health units"), 1),
            Triple("Cost-Effectiveness Analysis (CEA) compares alternative health interventions where costs are measured in money and outcomes are measured in natural clinical health units such as:", listOf("Monetary profit", "Lives saved, blood pressure mmHg reduced, or cases prevented", "QALYs", "Hospital revenue"), 1),
            Triple("Cost-Utility Analysis (CUA) measures health outcomes in standardized composite utility metrics known as:", listOf("Monetary rupees", "Quality-Adjusted Life Years (QALYs) or Disability-Adjusted Life Years (DALYs)", "Bed days", "Drug doses"), 1),
            Triple("One Quality-Adjusted Life Year (1 QALY) represents:", listOf("One year of life with severe disability", "One year of life lived in full, perfect health", "Ten years of disease", "One hospital admission"), 1),
            Triple("Disability-Adjusted Life Year (1 DALY) quantifies the loss of the equivalent of:", listOf("One year of perfect health due to premature death or disability (DALY = YLL + YLD)", "One year of employment", "One hospital bed day", "One doctor visit"), 0),
            Triple("Incremental Cost-Effectiveness Ratio (ICER) formula calculates the additional cost per additional unit of health outcome gained when comparing new treatment to standard care:", listOf("ICER = (Cost B - Cost A) / (Effect B - Effect A)", "ICER = Cost A x Effect A", "ICER = Total Cost / Total Patients", "ICER = Profit / Loss"), 0),
            Triple("Gross Domestic Product (GDP) percentage allocated to total health expenditure in Pakistan historically ranges around:", listOf("15% to 20%", "Less than 1.5% to 2.0% of GDP (below WHO recommended 5%)", "10%", "30%"), 1),
            Triple("Out-Of-Pocket (OOP) expenditure accounts for approximately what percentage of total health spending in Pakistan, exposing families to catastrophic health impoverishment?", listOf("10%", "Over 60% to 65% of total health expenditure", "25%", "90%"), 1),
            Triple("Sehat Sahulat Program (Sehat Card Plus KP) in Khyber Pakhtunkhwa provides micro-health insurance coverage for inpatient hospital care up to Rs.:", listOf("100,000 per family", "1,000,000 (10 Lakh) Rupees per family per year", "50,000 per family", "5,000,000 per family"), 1),
            Triple("Sehat Card Plus KP covers secondary and tertiary medical treatments including cardiac surgery, oncology, renal dialysis, and neurosurgery for enrolled families across:", listOf("Selected rich citizens only", "100% of permanent resident families of KP", "Government employees only", "Urban areas only"), 1),
            Triple("Health Policy is defined as formal decisions, plans, and actions undertaken by governmental or organizational bodies to achieve specific:", listOf("Commercial profit goals", "Healthcare goals within a society", "Tax collection increases", "Political campaign targets"), 1),
            Triple("Policy Making Cycle initial phase involves identifying public issues and placing them on the government's priority list, termed:", listOf("Policy Adoption", "Agenda Setting", "Policy Implementation", "Policy Evaluation"), 1),
            Triple("Second phase of Policy Making Cycle where policy options, legislation drafts, and proposals are developed is:", listOf("Agenda Setting", "Policy Formulation", "Policy Evaluation", "Policy Termination"), 1),
            Triple("Policy Implementation stage of policy process involves:", listOf("Drafting bills", "Translating enacted laws and policies into operational guidelines, programs, and administrative actions", "Evaluating past laws", "Campaigning"), 1),
            Triple("Universal Health Coverage (UHC) core objective defined by WHO ensures all people receive quality health services without suffering:", listOf("Any minor illness", "Financial hardship when paying for care", "Hospital queues", "Need for prescription"), 1),
            Triple("UHC 'Cube' model framework evaluates coverage across three dimensions: Population coverage (who is covered), Service coverage (which services are covered), and:", listOf("Private clinic growth", "Financial protection (what proportion of costs are covered)", "Doctor salaries", "Hospital building size"), 1),
            Triple("Single-Payer Healthcare System (e.g. UK National Health Service) is financed primarily through general taxation where the government acts as the:", listOf("Private insurer", "Single public payer funding health services for all citizens", "Commercial bank", "Hospital owner"), 1),
            Triple("Social Health Insurance model (Bismarck model e.g. Germany) finances healthcare through mandatory payroll contributions deducted from employees and employers into dedicated non-profit:", listOf("Private stock funds", "Sickness Funds / Health Funds", "Tax revenue", "Personal savings"), 1),
            Triple("Market-Driven Private Health Insurance model (e.g. US predominant model) relies on voluntary purchase of health insurance from commercial for-profit or non-profit insurers, leading to:", listOf("100% equal coverage", "Significant population coverage gaps and high administrative costs", "Lowest health costs globally", "Zero un-insured"), 1),
            Triple("Supply and Demand imbalance in nursing workforce leading to nurse shortages causes wage increases and increased reliance on high-cost:", listOf("Permanent staff", "Temporary agency / Travel Nurses and overtime pay", "Student nurses", "Midwives"), 1),
            Triple("Cost-Containment strategies in hospital operations include standardized clinical pathways, bulk purchasing of generic pharmaceuticals, and reducing patient:", listOf("Nursing care quality", "Unnecessary length of hospital stay (LOS) and hospital-acquired complications", "Hand hygiene", "Oxygen flow"), 1),
            Triple("Length of Stay (LOS) reduction without increasing 30-day hospital readmission rates is a key operational efficiency metric managed by nursing:", listOf("Finance officers", "Case Managers and Discharge Planners", "Janitors", "Security staff"), 1),
            Triple("Hospital-Acquired Conditions (HACs) such as catheter-associated urinary tract infections (CAUTI) and central line infections (CLABSI) under value-based purchasing result in financial:", listOf("Bonus payments to hospital", "Non-reimbursement or financial penalties imposed on the hospital", "Tax exemptions", "Free equipment"), 1),
            Triple("Direct Medical Costs in health economics evaluation include expenses directly incurred for clinical care such as:", listOf("Lost work wages", "Medications, diagnostic tests, hospital bed stay, and nursing care fees", "Travel cost to clinic", "Family caregiver time"), 1),
            Triple("Indirect Medical Costs account for economic losses resulting from patient illness including lost productivity, absenteeism, and:", listOf("Doctor consultation fee", "Premature mortality and loss of earning capacity", "Syringe price", "X-ray charge"), 1),
            Triple("Intangible Costs in health economics quantify non-financial impacts of illness such as patient:", listOf("Bus fare", "Pain, suffering, anxiety, and reduced quality of life", "Lab test bill", "Prescription cost"), 1),
            Triple("Health Technology Assessment (HTA) is a multidisciplinary process evaluating medical technologies (drugs, devices, procedures) regarding clinical effectiveness, safety, economic efficiency, and:", listOf("Manufacturer profit", "Ethical, social, and organizational impacts to inform policy decisions", "Sponsorship budget", "Packaging design"), 1),
            Triple("Public-Private Partnership (PPP) in health infrastructure involves long-term contract between government entity and private sector to design, finance, build, and operate healthcare facilities, aimed at:", listOf("Privatizing all public care", "Improving healthcare infrastructure quality and service access leveraging private efficiency", "Closing government hospitals", "Abolishing public health"), 1),
            Triple("Ecosystem of Health Disparity economics shows that living in low socioeconomic poverty areas increases exposure to environmental toxins, poor nutrition, and chronic stress, driving up:", listOf("High savings", "Disease burden, emergency room utilization, and catastrophic health spending", "Health literacy", "Life expectancy"), 1),
            Triple("Economic benefit of Investing in Nursing Education and Workforce expansion according to WHO yields a multi-fold return on investment (ROI) through improved population health, increased workforce productivity, and:", listOf("Higher unemployment", "Economic growth and gender empowerment", "Inflation", "Reduced hospital beds"), 1),
            Triple("Essential Medicines List (EML) published by WHO and adopted by Pakistan National Health Services prioritizes funding and availability for medications that satisfy the primary healthcare needs of the:", listOf("Rich elite population", "Majority of the population at prices the community can afford", "Private cosmetic clinics", "Export market"), 1),
            Triple("Generic Drug substitution policy mandates or encourages replacing brand-name pharmaceuticals with bioequivalent generic alternatives, achieving significant cost savings without compromising clinical:", listOf("Packaging color", "Efficacy, safety, and quality", "Tablet shape", "Brand popularity"), 1),
            Triple("Nurses as Health Policy Advocates leverage clinical expertise, patient stories, and research data to influence lawmakers during legislative drafting to improve:", listOf("Personal income", "Public health outcomes, patient safety regulations, and nursing scope of practice", "Political party power", "Corporate stock value"), 1),
            Triple("Key professional organization representing nursing interests globally and advocating for nursing health policy at the World Health Organization is the:", listOf("American Medical Association", "International Council of Nurses (ICN)", "World Trade Organization", "United Nations Security Council"), 1)
        )
        addSubjectQs(8, "Health Care Economics & Policy", "KMU ECO-683 / Feldstein Health Care Economics", eco)

        // ==========================================
        // 4. PROFESSIONAL ELECTIVE / DISASTER MANAGEMENT - 50 Qs
        // ==========================================
        val dis = listOf(
            Triple("Disaster defined by United Nations Office for Disaster Risk Reduction (UNDRR) is a serious disruption of community functioning causing widespread human, material, economic, or environmental losses exceeding the community's capacity to cope using its own:", listOf("Foreign debt", "Internal resources", "Police force", "Hospital beds"), 1),
            Triple("Disaster Management Cycle consists of four continuous phases: Prevention / Mitigation, Preparedness, Response, and:", listOf("Panic", "Recovery / Rehabilitation", "Investigation", "Demolition"), 1),
            Triple("Disaster Mitigation phase involves long-term measures designed to eliminate or reduce the impact and risks of hazards BEFORE a disaster occurs, exemplified by:", listOf("Distributing food during flood", "Building earthquake-resistant hospital infrastructure and flood levees", "Triage at disaster site", "Rebuilding homes post disaster"), 1),
            Triple("Disaster Preparedness phase activities include creating emergency response plans, conducting disaster drills, establishing warning systems, and:", listOf("Constructing dams", "Stockpiling emergency medical supplies and training response personnel", "Filing insurance claims", "Clearing rubble"), 1),
            Triple("Disaster Response phase occurs IMMEDIATELY during and post impact, focusing primarily on search and rescue, rapid medical triage, and providing:", listOf("Long-term economic loans", "Emergency life-saving medical care, shelter, and clean water", "Architectural redesign", "Academic research"), 1),
            Triple("Disaster Recovery / Rehabilitation phase focuses on restoring normal community functioning, rebuilding infrastructure, providing psychological counseling, and:", listOf("Conducting emergency triage", "Re-establishing sustainable healthcare systems and long-term socio-economic recovery", "Triggering evacuation alarms", "Executing START triage"), 1),
            Triple("Mass Casualty Incident (MCI) is defined as an emergency event where the number and severity of casualties overwhelms available local healthcare resources and:", listOf("Requires no extra help", "Demands extraordinary emergency response capabilities and triage protocol", "Affects only 1 person", "Causes zero injuries"), 1),
            Triple("START Triage algorithm used in mass casualty incidents stands for:", listOf("Systematic Treatment And Rapid Transport", "Simple Triage And Rapid Treatment", "Standard Triage And Rescue Technique", "Swift Treatment And Emergency Triage"), 1),
            Triple("Under START Triage algorithm, first step performed by triage nurse at mass casualty scene is shouting clear verbal instructions directing all casualties who can walk to move to a designated area. These walking wounded patients are assigned triage tag color:", listOf("Red (Immediate)", "Yellow (Delayed)", "Green (Minor / Walking Wounded)", "Black (Expectant / Deceased)"), 2),
            Triple("Under START Triage, an adult casualty who is NOT breathing initially has their airway manually opened (Head-Tilt/Chin-Lift). If breathing does NOT resume after opening airway, patient is tagged:", listOf("Red", "Yellow", "Green", "Black (Expectant / Deceased)"), 3),
            Triple("Under START Triage, if an un-breathing casualty STOPS and starts breathing post manual airway opening, they are immediately tagged:", listOf("Red (Immediate - priority 1)", "Yellow (Delayed)", "Green (Minor)", "Black"), 0),
            Triple("Under START Triage, a breathing casualty with Respiratory Rate > 30 breaths/minute is immediately assigned triage tag color:", listOf("Yellow", "Red (Immediate - priority 1)", "Green", "Black"), 1),
            Triple("Under START Triage, a breathing casualty with Respiratory Rate < 30/min, Capillary Refill > 2 seconds (or absent radial pulse) is tagged:", listOf("Yellow", "Red (Immediate - priority 1)", "Green", "Black"), 1),
            Triple("Under START Triage, a casualty who breathes < 30/min, has Capillary Refill < 2 sec / normal radial pulse, but CANNOT follow simple commands ('raise 2 fingers') is tagged:", listOf("Yellow", "Red (Immediate - priority 1)", "Green", "Black"), 1),
            Triple("Under START Triage, a casualty who breathes < 30/min, normal capillary refill, AND CAN follow simple commands is assigned triage tag color:", listOf("Red", "Yellow (Delayed - priority 2)", "Green", "Black"), 1),
            Triple("JumpSTART Triage algorithm is specifically modified for mass casualty triage of:", listOf("Elderly nursing home patients", "Pediatric patients under 8 years of age (including 5 rescue breaths for respiratory arrest)", "Pregnant women", "Chemical spill victims"), 1),
            Triple("Command and control organizational framework universally utilized for managing emergency disaster response operations is the:", listOf("Incident Command System (ICS)", "Maslow Hierarchy", "SWOT Analysis", "PNC Governance"), 0),
            Triple("Incident Commander (IC) in Incident Command System holds ultimate responsibility for:", listOf("Driving ambulance", "Overall management, strategy, and decision-making for the entire incident response", "Administering IV drugs", "Cooking food"), 1),
            Triple("Hospital Emergency Incident Command System (HEICS) adapts ICS to coordinate internal hospital emergency operations during mass casualty influx led by the:", listOf("Head Nurse", "Hospital Incident Commander (usually Medical Superintendent / Executive Director)", "Emergency Physician", "Janitorial lead"), 1),
            Triple("Decontamination in Chemical, Biological, Radiological, or Nuclear (CBRN) disaster response must be performed BEFORE patients enter hospital facility to prevent:", listOf("Water waste", "Secondary contamination of hospital staff, clean treatment areas, and unexposed patients", "Billing delays", "Patient panic"), 1),
            Triple("Primary initial step in field decontamination for chemical spill casualties is removing all patient clothing, which removes approximately what percentage of chemical contamination?", listOf("10%", "80% to 90% of chemical contamination", "30%", "100% complete"), 1),
            Triple("Personal Protective Equipment (PPE) Level A for CBRN disaster response provides the highest level of respiratory and skin protection consisting of:", listOf("Standard surgical mask and gown", "Totally encapsulating chemical-protective suit with self-contained breathing apparatus (SCBA)", "N95 mask and apron", "Gloves and face shield"), 1),
            Triple("Potassium Iodide (KI) tablets are distributed during radiological / nuclear disaster emergencies to protect which organ against absorption of radioactive iodine isotopes?", listOf("Liver", "Thyroid Gland (preventing radiation-induced thyroid cancer)", "Kidneys", "Lungs"), 1),
            Triple("Anthrax (Bacillus anthracis) aerosolized spore exposure during bioterrorism event is treated first-line with post-exposure prophylactic antibiotic therapy duration of 60 days using:", listOf("Amoxicillin", "Ciprofloxacin or Doxycycline", "Azithromycin", "Ceftriaxone"), 1),
            Triple("Smallpox (Variola virus) bioterrorism threat suspicion requires strict Airborne and Contact Precautions, immediate isolation, and ring vaccination using:", listOf("MMR vaccine", "Smallpox / Vaccinia Vaccine", "Varicella vaccine", "Polio drops"), 1),
            Triple("Botulinum Toxin (produced by Clostridium botulinum) causes lethal neuroparalytic illness presenting clinically with symmetrical descending flaccid paralysis and early:", listOf("High fever and hyperreflexia", "Cranial nerve palsies (diplopia, dysarthria, dysphagia, ptosis) without fever", "Severe diarrhea", "Generalized seizures"), 1),
            Triple("Mass Casualty Surge Capacity in hospital emergency management refers to the ability to rapidly expand hospital beds, personnel, equipment, and structural space to care for a sudden influx of:", listOf("Routine walk-in patients", "Critically injured casualties exceeding normal capacity", "Elective surgical patients", "Outpatient clinic visits"), 1),
            Triple("Psychological First Aid (PFA) principles provided to disaster survivors focus on promoting safety, calm, connectedness, self-efficacy, and:", listOf("Deep psychiatric analysis", "Hope and practical support for immediate basic needs", "Prescribing heavy sedatives", "Hypnosis"), 1),
            Triple("Post-Traumatic Stress Disorder (PTSD) long-term psychological intervention after mass disaster exposure includes evidence-based cognitive-behavioral therapy and:", listOf("Permanent isolation", "Eye Movement Desensitization and Reprocessing (EMDR)", "ECT therapy", "Hospital lockup"), 1),
            Triple("Complex Humanitarian Emergency (CHE) is defined as a multi-faceted humanitarian crisis combining armed conflict, mass population displacement, food insecurity, and:", listOf("High economic growth", "Breakdown of health systems and public infrastructure", "Urban technological expansion", "Zero mortality"), 1),
            Triple("Internally Displaced Persons (IDPs) differ from Refugees in international law because IDPs have been forced to flee their homes but have NOT crossed an:", listOf("Urban boundary", "Internationally recognized state border (remaining within home country)", "Ocean", "Hospital threshold"), 1),
            Triple("Refugee health management priority in temporary camp settings includes preventing explosive waterborne infectious disease outbreaks of:", listOf("Hypertension", "Cholera and Dysentery through clean water, sanitation, and Oral Cholera Vaccine", "Diabetes", "Asthma"), 1),
            Triple("Sphere Handbook minimum humanitarian standard for clean drinking water supply in disaster relief camps mandates providing at least how many liters per person per day?", listOf("2 Liters", "15 Liters per person per day (for drinking, cooking, and personal hygiene)", "50 Liters", "1 Liter"), 1),
            Triple("Sphere minimum humanitarian standard for basic toilet coverage in emergency disaster camps specifies a maximum ratio of how many people per latrine?", listOf("5 people per latrine", "20 people per latrine (separated by gender with safety locks/lights)", "100 people per latrine", "500 people"), 1),
            Triple("Cold Wave / Hypothermia emergency management in flood or earthquake displaced victims focuses on gradual rewarming, removing wet clothes, and applying:", listOf("Direct boiling hot water soak", "Warm dry blankets, insulation, and warm oral fluids if conscious", "Rubbing snow", "Alcohol massage"), 1),
            Triple("Heat Stroke (core body temperature > 40°C / 104°F with altered mental status) during extreme heat waves in KP requires rapid evaporative/immersion cooling targeting core temp drop to:", listOf("37°C within 30 minutes (stopping cooling at 38°C to prevent rebound hypothermia)", "30°C", "25°C", "42°C"), 0),
            Triple("Earthquake disaster injury management requires high clinical index of suspicion for Crush Syndrome caused by prolonged muscle compression resulting in rhabdomyolysis, hyperkalemia, and acute:", listOf("Liver failure", "Kidney Injury (Acute Tubular Necrosis due to myoglobinuria)", "Heart valve damage", "Stroke"), 1),
            Triple("First-line fluid resuscitation for Crush Injury victim prior to or immediately upon extrication from earthquake rubble is aggressive IV infusion of:", listOf("5% Dextrose in Water", "0.9% Normal Saline (bolus 1 to 1.5 L/hr to maintain high urine output > 200 mL/hr)", "Packed Red Blood Cells", "Hypertonic 3% Saline"), 1),
            Triple("Crush Injury victim with severe Rhabdomyolysis presenting with peaked T-waves on ECG requires urgent treatment for life-threatening:", listOf("Hypokalemia", "Hyperkalemia (using Calcium Gluconate, Insulin + Dextrose, Albuterol, and Dialysis)", "Hyponatremia", "Hypercalcemia"), 1),
            Triple("Flood disaster public health disease surveillance primary focus during post-flood standing water phase includes monitoring for Leptospirosis, Vector-borne diseases, and:", listOf("Cardiovascular diseases", "Waterborne Gastroenteritis (Diarrhea, Cholera, Typhoid, Hepatitis A/E)", "Lung cancer", "Osteoporosis"), 1),
            Triple("Leptospirosis infection contracted during wading through flood water contaminated with rat urine enters human body through:", listOf("Inhalation", "Skin abrasions, mucous membranes, or swallowed water", "Insect bites", "Intact nails"), 1),
            Triple("Wildfire smoke inhalation emergency care mandates high-flow 100% Oxygen administration to treat suspected toxicity from Carbon Monoxide and:", listOf("Carbon Dioxide", "Hydrogen Cyanide gas (treated with Hydroxocobalamin / Cyanokit)", "Nitrogen", "Helium"), 1),
            Triple("Triage tag color BLACK (Expectant / Deceased) in mass casualty disasters is assigned to casualties who are dead or whose injuries are so catastrophic that survival is unlikely even with:", listOf("Basic ice pack", "Maximal advanced resuscitation care, allowing resources to focus on red-tagged survivors", "Bandages", "Rest"), 1),
            Triple("In mass casualty disaster response, Ethical principle of Utility replaces individual patient autonomy, mandating doing the greatest good for the:", listOf("Individual richest patient", "Largest number of potential survivors", "Hospital board", "First arriving patient"), 1),
            Triple("Disaster Nursing Education core competencies established by International Council of Nurses (ICN) cover Ethical Practice, Legal Practice, Critical Thinking, Preparedness, Assessment, Response, and:", listOf("Financial Audit", "Recovery and Community Communication", "Private Business", "Hospital Ownership"), 1),
            Triple("Crisis Standards of Care (CSC) legally authorized during catastrophic disasters allow healthcare systems to shift from standard individual-centered care to:", listOf("No care", "Population-based resource allocation strategies prioritizing salvageable lives", "Paid care only", "Private clinic referrals"), 1),
            Triple("National Disaster Management Authority (NDMA) Pakistan and Provincial Disaster Management Authority (PDMA KP) lead national and provincial disaster policy, coordination, and:", listOf("Private medical practice", "Disaster risk reduction, relief allocation, and emergency rehabilitation", "Export management", "School grading"), 1),
            Triple("District Disaster Management Authority (DDMA) headed by the Deputy Commissioner (DC) at district level coordinates local disaster response involving health departments, rescue 1122, and:", listOf("Private real estate", "District Headquarter (DHQ) Hospital and emergency services", "Bank managers", "Foreign embassies"), 1),
            Triple("Rescue 1122 Emergency Service in Khyber Pakhtunkhwa provides pre-hospital emergency medical care, fire fighting, urban search and rescue, and water rescue across all districts of:", listOf("Federal territory only", "Khyber Pakhtunkhwa province", "Sindh", "Balochistan"), 1),
            Triple("Hospital Disaster Plan must be tested through full-scale functional simulation drills at least how often to maintain operational readiness?", listOf("Once every 10 years", "At least Annually (1 to 2 times per year)", "Never", "Every month"), 1)
        )
        addSubjectQs(8, "Professional Elective / Disaster Management", "KMU DIS-684 / Veenema Disaster Nursing & Emergency Preparedness", dis)

        // Add 100 extra questions for EACH subject in Semester 8 (400 extra questions)
        questions.addAll(KpSemester8PlusQuestionBank.getQuestions(idCounter))

        return questions
    }
}
