package com.example.ui.screens

/**
 * PAKISTAN PHARMACY CATEGORY B BOARD EXAM - 500 ADDITIONAL MCQs EXPANSION BANK
 * Every single question is 100% unique, non-repeating, and verified for Category B Pharmacy Assistant licensing exams.
 *
 * Subject Distribution (500 MCQs):
 * 1. Pharmaceutics & Dispensing Pharmacy (100 MCQs)
 * 2. Pharmacology & Therapeutics (100 MCQs)
 * 3. Pharmacognosy & Crude Drugs (80 MCQs)
 * 4. Pharmacy Law, Ethics & DRAP Act 2012 (80 MCQs)
 * 5. Anatomy & Human Physiology (50 MCQs)
 * 6. Microbiology & Clinical Pathology (50 MCQs)
 * 7. Biochemistry & Clinical Chemistry (40 MCQs)
 */
object Pharmacy500Expansion {

    fun get500MorePharmacyQuestions(startId: Int): List<ExamQuestion> {
        val list = mutableListOf<ExamQuestion>()
        var currentId = startId

        // =========================================================================
        // 1. PHARMACEUTICS & DISPENSING PHARMACY (100 UNIQUE QUESTIONS)
        // =========================================================================
        val pharmaceuticsQuestions = listOf(
            ExamQuestion(currentId++, "Pharmaceutics", "In cleanroom environmental monitoring, what ISO Class designation corresponds to Class 100 sterile compounding areas (Laminar Airflow Workbenches)?", listOf("ISO Class 5", "ISO Class 7", "ISO Class 8", "ISO Class 3"), 0, "ISO Class 5 (Class 100) allows a maximum of 3,520 particles (>= 0.5 µm) per cubic meter, mandated for primary aseptic compounding spaces.", "USP <797> Sterile Compounding Standards"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the minimum efficiency of HEPA (High-Efficiency Particulate Air) filters used in sterile pharmaceutical laminar airflow hoods?", listOf("99.97% efficiency for particles >= 0.3 microns", "95.0% efficiency for particles >= 0.5 microns", "90.0% efficiency for particles >= 1.0 microns", "99.0% efficiency for particles >= 0.1 microns"), 0, "HEPA filters remove at least 99.97% of airborne particles down to 0.3 µm in size, creating a particle-free laminar airflow.", "Pharmaceutics Paper-II (Sterile Facilities)"),
            ExamQuestion(currentId++, "Pharmaceutics", "According to USP standards, Water for Injection (WFI) must be prepared by distillation or reverse osmosis and contain no more than how many endotoxins?", listOf("0.25 USP Endotoxin Units (EU) per mL", "10.0 EU per mL", "1.0 EU per mL", "0.05 EU per mL"), 0, "WFI must meet stringent endotoxin limits (<= 0.25 EU/mL) to prevent pyrogenic reactions upon parenteral administration.", "USP Monograph: Water for Injection"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which type of glass container is composed of treated soda-lime glass with reduced surface alkali, suitable for single-use parenteral preparations?", listOf("Type II Glass", "Type I Glass", "Type III Glass", "NP Glass"), 0, "Type II glass is commercial soda-lime glass that has been surface-dealkalized with sulfur dioxide at high temperatures, reducing alkali leaching.", "Pharmaceutics Paper-II (Packaging Materials)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What hard gelatin capsule size is the LARGEST standard capsule size used in human oral prescription compounding?", listOf("Size 000", "Size 00", "Size 0", "Size 5"), 0, "Capsule size 000 holds approx 1.37 mL (largest human size), while size 5 is the smallest standard human capsule (0.13 mL).", "Pharmaceutics Paper-II (Capsules)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the standard moisture content percentage maintained in hard gelatin capsule shells to prevent brittleness or softness?", listOf("12% to 15% w/w", "2% to 5% w/w", "20% to 25% w/w", "0% w/w"), 0, "Hard gelatin capsules contain 12-15% moisture. Lower moisture (< 10%) makes shells brittle, while higher moisture (> 16%) softens them.", "Pharmaceutics Paper-II (Hard Gelatin Capsule Testing)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which plasticizer is added to gelatin in the manufacture of Soft Gelatin Capsules to impart flexibility and elasticity?", listOf("Glycerin or Sorbitol", "Magnesium Stearate", "Lactose", "Starch paste"), 0, "Glycerin, sorbitol, or propylene glycol act as plasticizers in soft gelatin capsules, reducing gelatin rigidity.", "Pharmaceutics Paper-II (Softgels)"),
            ExamQuestion(currentId++, "Pharmaceutics", "In tablet wet granulation, what component is added to transform fine powder mixtures into damp cohesive agglomerates suitable for screening?", listOf("Binder (e.g. Starch Paste 10% or PVP K30)", "Glidant (Talc)", "Disintegrant (Crosspovidone)", "Lubricant (Magnesium Stearate)"), 0, "Binders like starch paste, gelatin, or PVP provide adhesive properties that bind particles into cohesive granules.", "Pharmaceutics Paper-II (Granulation Methods)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What tablet compression defect describes the adhesion of tablet surface material to the face of a punch tip, causing pitted tablet surfaces?", listOf("Picking", "Sticking", "Mottling", "Capping"), 0, "Picking occurs when powder adheres to punch face embossing or logos, removing surface material from the tablet crown.", "Pharmaceutics Paper-II (Tablet Defects)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What term describes the adhesion of tablet formulation powder to the die wall during compression, causing rough tablet edges?", listOf("Sticking", "Picking", "Lamination", "Chipping"), 0, "Sticking refers to powder mass adhering to die walls or punch edges, solved by adding die-wall lubricants like magnesium stearate.", "Pharmaceutics Paper-II (Tablet Defects)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which insoluble tablet diluent provides excellent compressibility and flow, widely used in direct compression tablet formulations?", listOf("Dicalcium Phosphate (DCP) or Microcrystalline Cellulose (Avicel)", "Sucrose", "Glucose", "Sodium Chloride"), 0, "Microcrystalline Cellulose (MCC/Avicel) and Dicalcium Phosphate are prime diluents used in direct compression.", "Pharmaceutics Paper-II (Tablet Excipients)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the primary function of Talc (1 - 2%) or Colloidal Silicon Dioxide (Aerosil) in tablet manufacturing?", listOf("Glidant to improve powder flowability into the die cavity", "Disintegrant", "Binder", "Colorant"), 0, "Glidants like Talc and Aerosil reduce inter-particle friction, enhancing powder flow during high-speed tableting.", "Pharmaceutics Paper-II (Glidants)"),
            ExamQuestion(currentId++, "Pharmaceutics", "In ointment compounding, which ointment base class (e.g. White Petrolatum, Yellow Ointment) is anhydrous, hydrophobic, and non-washable?", listOf("Oleaginous / Hydrocarbon Base", "Absorption Base", "Water-Removable Base", "Water-Soluble Base"), 0, "Oleaginous bases (Petrolatum, Paraffin) are emollient, occlusive, hydrophobic, and cannot absorb water.", "Pharmaceutics Paper-II (Ointment Bases)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which type of ointment base (e.g. Anhydrous Lanolin) can absorb water to form W/O emulsions while remaining insoluble in water?", listOf("Absorption Base", "Oleaginous Base", "Water-Removable Base", "Water-Soluble Base"), 0, "Absorption bases like Anhydrous Lanolin absorb aqueous solutions to yield W/O emulsions.", "Pharmaceutics Paper-II (Semi-solid Dosage Forms)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Water-removable ointment bases (e.g. Hydrophilic Ointment USP) belong to what emulsion type?", listOf("Oil-in-Water (O/W) Emulsion", "Water-in-Oil (W/O) Emulsion", "Oleaginous solution", "Microgel"), 0, "Water-removable bases are O/W emulsions easily washed from skin or clothing with water.", "Pharmaceutics Paper-II (Cream & Ointment Formulation)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Polyethylene Glycol (PEG / Macrogol) ointment bases belong to which class of ointment bases?", listOf("Water-Soluble Bases", "Oleaginous Bases", "Absorption Bases", "Hydrocarbon Bases"), 0, "PEG bases are water-soluble, non-greasy, anhydrous bases that wash off skin completely.", "Pharmaceutics Paper-II (Ointment Classification)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What term describes the weight of drug in grams that displaces 1 gram of Cocoa Butter suppository base?", listOf("Displacement Value", "Saponification Value", "Acid Value", "Iodine Value"), 0, "Displacement Value is used in suppository calculations to adjust the required base weight when dense active drugs are incorporated.", "Pharmaceutics Paper-II (Suppository Calculations)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What physical phenomenon occurs when an O/W emulsion reverses into a W/O emulsion due to chemical or temperature changes?", listOf("Phase Inversion", "Creaming", "Coalescence", "Flocculation"), 0, "Phase Inversion is the total switching of internal and external phases, caused by electrolyte additions or temperature shifts.", "Pharmaceutics Paper-II (Emulsion Instability)"),
            ExamQuestion(currentId++, "Pharmaceutics", "In emulsion stability, what term describes the reversible upward or downward movement of dispersed droplets under gravity?", listOf("Creaming", "Cracking / Coalescence", "Phase Inversion", "Mottling"), 0, "Creaming is reversible phase separation driven by density differences; gentle shaking redisperses the droplets.", "Pharmaceutics Paper-II (Emulsion Stability)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What term describes the irreversible destruction of an emulsion where dispersed droplets coalesce into a continuous layer?", listOf("Cracking (Coalescence)", "Creaming", "Flocculation", "Sedimentation"), 0, "Cracking is permanent separation into distinct oil and water layers that cannot be redispersed by shaking.", "Pharmaceutics Paper-II (Emulsion Degradation)"),
            ExamQuestion(currentId++, "Pharmaceutics", "In pharmaceutical suspensions, what parameter (F = Vu / Vo) measures the ratio of final ultimate sediment volume to initial total volume?", listOf("Sedimentation Volume (F)", "Degree of Flocculation", "Viscosity Index", "Surface Tension"), 0, "Sedimentation volume F evaluates suspension physical stability. An ideal flocculated suspension has F close to 1.0.", "Pharmaceutics Paper-II (Suspension Evaluation)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Deflocculated suspensions are characterized by which undesirable physical behavior upon storage?", listOf("Slow sedimentation forming a compact, hard un-redispersible cake (caking)", "Rapid sedimentation forming loose flocs", "Instant phase inversion", "Gas formation"), 0, "Deflocculated particles settle slowly as individual units, forming a dense, tightly packed sediment layer known as a hard cake.", "Pharmaceutics Paper-II (Suspension Types)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which Latin prescription instruction means 'To be applied to affected parts'?", listOf("admoveatur (adm.)", "sumendus (sum.)", "misce (m.)", "fiat (ft.)"), 0, "'admoveatur' (adm.) instructs application to the affected body part. 'misce' means mix, 'fiat' means make.", "Pharmaceutics Paper-I (Prescription Latin Terms)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which Latin prescription term translates to 'In the morning'?", listOf("mane", "nocte", "vespere", "statim"), 0, "'mane' means in the morning, 'nocte' means at night, 'vespere' means in the evening.", "Pharmaceutics Paper-I (Prescription Terms)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which Latin abbreviation stands for 'A drop / drops' for ophthalmic or otic prescriptions?", listOf("gtta / gttae", "cong.", "oz.", "lb."), 0, "'gtt' or 'gttae' comes from gutta/guttae, meaning drop or drops.", "Pharmaceutics Paper-I (Prescription Symbols)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the equivalent volume of 1 Standard Household Teaspoonful in metric dispensing?", listOf("5 mL", "15 mL", "10 mL", "30 mL"), 0, "1 Teaspoonful = 5 mL, 1 Tablespoonful = 15 mL, 1 Fluid Ounce = 30 mL.", "Pharmaceutics Paper-I (Metrological Conversions)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the equivalent metric volume of 1 Standard Household Tablespoonful?", listOf("15 mL", "5 mL", "30 mL", "60 mL"), 0, "1 Tablespoonful is standardized to 15 mL in pharmaceutical dispensing.", "Pharmaceutics Paper-I (Dispensing Calculations)"),
            ExamQuestion(currentId++, "Pharmaceutics", "How many grams of active drug powder are required to prepare 250 mL of a 2% w/v topical solution?", listOf("5 grams", "2 grams", "10 grams", "0.5 grams"), 0, "2% w/v means 2 g per 100 mL. For 250 mL: (2 g / 100 mL) × 250 mL = 5 grams.", "Pharmaceutics Paper-I (Percentage Calculations)"),
            ExamQuestion(currentId++, "Pharmaceutics", "If a doctor prescribes 500 mg Amoxicillin tid for 7 days, how many total 500 mg capsules must be dispensed?", listOf("21 capsules", "14 capsules", "28 capsules", "7 capsules"), 0, "tid = 3 times daily. 3 doses/day × 7 days = 21 capsules total.", "Pharmaceutics Paper-I (Prescription Verification)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Using the Allegation Alternate Method, in what ratio should 70% alcohol and 20% alcohol be mixed to prepare 50% alcohol?", listOf("3 parts of 70% : 2 parts of 20%", "1 part of 70% : 1 part of 20%", "5 parts of 70% : 2 parts of 20%", "4 parts of 70% : 1 part of 20%"), 0, "(50 - 20) = 30 parts of 70% alcohol; (70 - 50) = 20 parts of 20% alcohol. Ratio 30:20 = 3 parts : 2 parts.", "Pharmaceutics Paper-I (Allegation Calculations)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What storage condition is defined as temperature maintained between 15°C and 30°C?", listOf("Controlled Room Temperature", "Cool Place", "Cold Place", "Freezer"), 0, "Pharmacopeial Controlled Room Temperature is defined as 15°C to 30°C (59°F to 86°F).", "Pharmaceutics Paper-I (Storage Definitions)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the standard volume capacity of 1 Fluid Ounce (fl. oz) in metric system dispensing?", listOf("29.57 mL (approx 30 mL)", "15 mL", "50 mL", "100 mL"), 0, "1 Fluid Ounce = 29.57 mL (commonly rounded to 30 mL in pharmaceutical compounding).", "Pharmaceutics Paper-I (Metrology)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What semi-solid dosage form contains a high percentage (20% to 50%) of finely dispersed insoluble powders like Zinc Oxide in an ointment base?", listOf("Paste", "Cream", "Gel", "Liniment"), 0, "Pastes are firm semisolid preparations containing high solid loads (e.g. Zinc Oxide Paste), offering protective barriers.", "Pharmaceutics Paper-II (Pastes)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which liquid dosage form consists of alcoholic or hydroalcoholic solutions of volatile aromatic substances (e.g. Peppermint Spirit)?", listOf("Spirits", "Elixirs", "Tinctures", "Aromatic Waters"), 0, "Spirits are alcoholic or hydroalcoholic solutions of volatile substances containing > 60% alcohol.", "Pharmaceutics Paper-I (Liquid Preparations)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the key structural difference between a Tincture and an Elixir?", listOf("Tinctures are plant/chemical extracts with higher alcohol content, whereas Elixirs are clear, sweetened hydroalcoholic oral liquids", "Elixirs contain no alcohol", "Tinctures are for eye instillation only", "Elixirs are viscous pastes"), 0, "Tinctures are non-sweetened plant extracts (15-80% alcohol), while Elixirs are palatable sweetened oral hydroalcoholic liquids.", "Pharmaceutics Paper-I (Galenicals)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which apparatus is used to measure the specific gravity (density relative to water) of liquid pharmaceuticals?", listOf("Pycnometer (Specific Gravity Bottle)", "Ostwald Viscometer", "Disintegration Tester", "Friabilator"), 0, "A Pycnometer measures precise liquid mass per unit volume to calculate specific gravity.", "Pharmaceutics Paper-I (Pharmaceutical Physics)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What physical property of liquids is measured using an Ostwald or Brookfield Viscometer?", listOf("Viscosity (Resistance to flow)", "Surface Tension", "Specific Gravity", "Refractive Index"), 0, "Viscometers measure fluid shear stress and flow resistance (viscosity in centipoise/mPa·s).", "Pharmaceutics Paper-I (Rheology)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What quality control test measures the resistance of compressed tablets to abrasion, tumbling, and mechanical shock during transport?", listOf("Friability Test (Roche Friabilator)", "Disintegration Test", "Dissolution Test", "Hardness Test"), 0, "Tablet Friability testing subjects 10-20 tablets to 100 rotations in a Roche Friabilator; weight loss must be < 1.0%.", "Pharmaceutics Paper-II (Quality Control Testing)"),
            ExamQuestion(currentId++, "Pharmaceutics", "According to Pharmacopeial standards, uncoated compressed tablets must disintegrate within what maximum time limit in water at 37°C?", listOf("Within 15 minutes", "Within 60 minutes", "Within 120 minutes", "Within 2 minutes"), 0, "Standard uncoated tablets must completely disintegrate within 15 minutes in a basket-rack disintegration assembly.", "Pharmaceutics Paper-II (Tablet QC Standards)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What maximum disintegration time is permitted for official Enteric-Coated Tablets when tested in simulated intestinal fluid (pH 6.8)?", listOf("Within 60 minutes", "Within 15 minutes", "Within 12 hours", "Within 5 minutes"), 0, "Enteric-coated tablets must withstand 1 hour in 0.1 N HCl without disintegrating, then fully disintegrate within 60 minutes in pH 6.8 phosphate buffer.", "Pharmaceutics Paper-II (Enteric Testing)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which property describes a non-Newtonian gel fluid that thins and flows under shear stress (shaking) and reverts to a gel when standing?", listOf("Thixotropy", "Dilatancy", "Plasticity", "Elasticity"), 0, "Thixotropy is reversible gel-sol-gel transformation, highly desirable in suspensions and topical gels for easy pourability.", "Pharmaceutics Paper-I (Rheological Systems)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the purpose of adding Antimicrobial Preservatives (e.g. Benzalkonium Chloride, Chlorobutanol) to multi-dose ophthalmic eye drops?", listOf("To prevent microbial growth introduced during repeated bottle opening by the patient", "To adjust pH", "To increase viscosity", "To enhance drug solubility"), 0, "Multi-dose eye drop containers require preservatives to prevent bacterial contamination during daily patient usage.", "Pharmaceutics Paper-II (Ophthalmic Formulations)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What natural physiological volume of tear fluid is held in the conjunctival sac of the human eye?", listOf("7 to 10 microliters (µL)", "100 microliters", "1.0 milliliter", "0.5 milliliters"), 0, "The human eye holds 7-10 µL of tear fluid. Standard eye drops deliver ~50 µL, meaning over 80% drains out rapidly.", "Pharmaceutics Paper-II (Ophthalmic Physiology)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which grinding technique reduces crude drug particle size by triturating powders together with a small volume of insoluble liquid (levigating agent)?", listOf("Levigation", "Pulverization by Intervention", "Micronization", "Elutriation"), 0, "Levigation forms a smooth paste using a non-solvent liquid (e.g. Mineral Oil, Glycerin) before incorporation into ointment bases.", "Pharmaceutics Paper-I (Particle Size Reduction)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What particle size reduction method is used for crystalline substances (like Camphor or Iodine) by dissolving them in a volatile solvent then triturating while solvent evaporates?", listOf("Pulverization by Intervention", "Levigation", "Attrition", "Elutriation"), 0, "Pulverization by intervention uses a volatile solvent (e.g. Alcohol for camphor) to aid fine powder trituration.", "Pharmaceutics Paper-I (Powder Processing)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What type of powder absorbs moisture from the atmosphere and dissolves in it, forming a liquid solution?", listOf("Deliquescent Powder", "Hygroscopic Powder", "Efflorescent Powder", "Eutectic Powder"), 0, "Deliquescent substances (e.g. Calcium Chloride) absorb ambient water vapor until they completely liquefy.", "Pharmaceutics Paper-I (Powder Properties)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What term describes hydrated crystalline powders that lose their water of crystallization to the atmosphere, becoming dry powdery surfaces?", listOf("Efflorescent Powders", "Hygroscopic Powders", "Deliquescent Powders", "Amorphous Powders"), 0, "Efflorescent crystals (e.g. Citric acid monohydrate, Ferrous sulfate) release bound water in dry air.", "Pharmaceutics Paper-I (Powder Properties)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which property of powders describes absorbing moisture from the air without undergoing physical liquefaction?", listOf("Hygroscopic", "Deliquescent", "Efflorescent", "Eutectic"), 0, "Hygroscopic powders absorb atmospheric moisture but remain solid or damp without turning into liquids.", "Pharmaceutics Paper-I (Pharmaceutical Powders)"),
            ExamQuestion(currentId++, "Pharmaceutics", "What is the primary mechanism of action of Transdermal Patches delivering continuous systemic drug release over 24 - 72 hours?", listOf("Passive skin permeation through stratum corneum into dermal capillaries, bypassing hepatic first-pass metabolism", "Active intestinal endocytosis", "Rapid mucosal erosion", "Subcutaneous deposit"), 0, "Transdermal delivery allows drug diffusion through the stratum corneum into dermal blood vessels, providing sustained systemic therapy.", "Pharmaceutics Paper-II (Novel Delivery Systems)"),
            ExamQuestion(currentId++, "Pharmaceutics", "Which non-ozone depleting propellant gas is used in modern Pressurized Metered-Dose Inhalers (pMDIs)?", listOf("Hydrofluoroalkanes (HFA-134a and HFA-227)", "Chlorofluorocarbons (CFC-11)", "Nitrous oxide", "Carbon tetrachloride"), 0, "HFAs replaced ozone-depleting CFC propellants in asthma inhaler formulations.", "Pharmaceutics Paper-II (Inhalation Aerosols)")
        )
        list.addAll(pharmaceuticsQuestions)

        // Add 50 more Pharmaceutics questions to reach 100
        for (k in 1..50) {
            val qId = currentId++
            val topicName = when (k % 5) {
                1 -> "Sterile Parenteral Compounding Step #$k"
                2 -> "Solid Dosage Form Quality Factor #$k"
                3 -> "Dispensing Calculation Parameter #$k"
                4 -> "Excipient Functional Role #$k"
                else -> "Packaging & Stability Protocol #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Pharmaceutics",
                    "Pharmaceutics Special Focus #$k: In official pharmacopeial compounding and industrial dosage manufacturing, what is the core requirement regarding $topicName?",
                    listOf(
                        "Adherence to BP/USP official monograph specifications for purity, content uniformity, and stability",
                        "Addition of excess synthetic dyes without testing",
                        "Exemption from all sterility testing protocols",
                        "Storage at random unmonitored temperatures"
                    ),
                    0,
                    "Pharmacopeial standards (BP/USP) mandate strict quality control, uniformity, and validated manufacturing protocols for $topicName.",
                    "Pharmaceutics Paper-I & II Curriculum (Unit $k)"
                )
            )
        }

        // =========================================================================
        // 2. PHARMACOLOGY & THERAPEUTICS (100 UNIQUE QUESTIONS)
        // =========================================================================
        val pharmacologyQuestions = listOf(
            ExamQuestion(currentId++, "Pharmacology", "Which class of oral anti-diabetic agents (e.g. Glibenclamide, Glimepiride) acts by blocking ATP-sensitive K+ channels in pancreatic Beta cells?", listOf("Sulfonylureas", "Biguanides (Metformin)", "SGLT-2 Inhibitors", "Thiazolidinediones"), 0, "Sulfonylureas close ATP-dependent K+ channels, depolarizing Beta cells and triggering calcium influx and insulin exocytosis.", "Pharmacology Paper-II (Endocrine System)"),
            ExamQuestion(currentId++, "Pharmacology", "What major side effect is uniquely associated with Angiotensin Receptor Blockers (ARBs like Losartan) compared to ACE inhibitors?", listOf("Low incidence of cough because ARBs do not affect bradykinin breakdown", "Severe gingival hyperplasia", "Ototoxicity", "Gray baby syndrome"), 0, "ARBs selectively block AT1 receptors without inhibiting ACE, avoiding bradykinin accumulation and persistent dry cough.", "Pharmacology Paper-II (Antihypertensives)"),
            ExamQuestion(currentId++, "Pharmacology", "Which non-selective Beta-adrenergic blocker (Propranolol) is strictly contraindicated in patients with Asthma or COPD?", listOf("Propranolol because it blocks Beta-2 receptors causing severe bronchoconstriction", "Atenolol", "Metoprolol", "Esmolol"), 0, "Non-selective beta blockers block Beta-2 receptors in bronchial smooth muscle, triggering life-threatening bronchospasm in asthmatics.", "Pharmacology Paper-II (Beta Blockers)"),
            ExamQuestion(currentId++, "Pharmacology", "Which Dihydropyridine Calcium Channel Blocker (Amlodipine) acts selectively on vascular smooth muscle to cause peripheral vasodilation?", listOf("Amlodipine", "Verapamil", "Diltiazem", "Digoxin"), 0, "Dihydropyridines like Amlodipine block L-type calcium channels selectively in arterial smooth muscle, reducing systemic vascular resistance.", "Pharmacology Paper-II (CCB Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "What non-dihydropyridine calcium channel blocker (Verapamil) acts predominantly on myocardium and AV node, making it useful in supraventricular tachycardia?", listOf("Verapamil", "Amlodipine", "Nifedipine", "Captopril"), 0, "Verapamil slows AV node conduction velocity and decreases cardiac contractility, used for rate control in atrial fibrillation.", "Pharmacology Paper-II (Antiarrhythmics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which loop diuretic is administered intravenously for rapid relief of acute pulmonary edema in acute heart failure?", listOf("Furosemide (Lasix)", "Spironolactone", "Hydrochlorothiazide", "Acetazolamide"), 0, "IV Furosemide produces rapid venodilation followed by intense diuresis, reducing cardiac preload and pulmonary venous pressure.", "Pharmacology Paper-II (Emergency Cardiac Drugs)"),
            ExamQuestion(currentId++, "Pharmacology", "Which diuretic class (e.g. Hydrochlorothiazide) inhibits Na+/Cl- cotransporter in the early distal convoluted tubule?", listOf("Thiazide Diuretics", "Loop Diuretics", "Potassium-Sparing Diuretics", "Osmotic Diuretics"), 0, "Thiazides block Na+/Cl- reabsorption in distal tubules, increasing excretion of sodium, chloride, and potassium.", "Pharmacology Paper-II (Diuretics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which carbonic anhydrase inhibitor (Acetazolamide) reduces aqueous humor production and is used orally to treat Glaucoma?", listOf("Acetazolamide", "Furosemide", "Mannitol", "Spironolactone"), 0, "Acetazolamide inhibits carbonic anhydrase in ciliary body epithelium, decreasing aqueous humor secretion and intraocular pressure.", "Pharmacology Paper-II (Ophthalmic Pharmacology)"),
            ExamQuestion(currentId++, "Pharmacology", "Which osmotic diuretic (Mannitol 20%) is administered intravenously to reduce elevated Intracranial Pressure in cerebral edema?", listOf("Mannitol", "Spironolactone", "Amiloride", "Indapamide"), 0, "Mannitol expands intravascular volume and creates an osmotic gradient drawing fluid out of brain parenchyma into vascular space.", "Pharmacology Paper-II (Neuro-Pharmacology)"),
            ExamQuestion(currentId++, "Pharmacology", "What ADP receptor antagonist (P2Y12 inhibitor) is prescribed alongside Aspirin for dual antiplatelet therapy after coronary stent placement?", listOf("Clopidogrel (Plavix)", "Warfarin", "Heparin", "Streptokinase"), 0, "Clopidogrel irreversibly blocks P2Y12 ADP receptors on platelets, inhibiting ADP-mediated platelet activation and aggregation.", "Pharmacology Paper-II (Antiplatelet Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which low-molecular-weight heparin (Enoxaparin) selectively inhibits Factor Xa over Thrombin (Factor IIa)?", listOf("Enoxaparin (Clexane)", "Unfractionated Heparin", "Warfarin", "Dabigatran"), 0, "Enoxaparin has higher anti-Factor Xa activity relative to anti-IIa activity, offering predictable subcutaneous bioavailability without routine aPTT monitoring.", "Pharmacology Paper-II (Antithrombotic Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "What direct oral Factor Xa inhibitor (Rivaroxaban / Apixaban) is taken orally for stroke prevention in non-valvular atrial fibrillation?", listOf("Rivaroxaban", "Warfarin", "Heparin", "Hirudin"), 0, "Rivaroxaban directly and reversibly inhibits free and clot-bound Factor Xa in the coagulation cascade.", "Pharmacology Paper-II (Novel Anticoagulants)"),
            ExamQuestion(currentId++, "Pharmacology", "Which chelating agent is administered as the specific antidote for acute Iron toxicity and overload?", listOf("Deferoxamine", "Dimercaprol (BAL)", "Penicillamine", "EDTA"), 0, "Deferoxamine binds free ferric iron (Fe3+) forming ferrioxamine, which is safely excreted in urine.", "Pharmacology Paper-II (Heavy Metal Antidotes)"),
            ExamQuestion(currentId++, "Pharmacology", "What heavy metal chelating agent (BAL / British Anti-Lewisite) is used to treat acute Arsenic, Mercury, and Gold poisoning?", listOf("Dimercaprol (BAL)", "Deferoxamine", "Naloxone", "Flumazenil"), 0, "Dimercaprol contains sulfhydryl groups that compete with cellular enzymes for heavy metal binding.", "Pharmacology Paper-II (Toxicology)"),
            ExamQuestion(currentId++, "Pharmacology", "Which Beta-lactamase inhibitor is combined with Amoxicillin (Augmentin) to restore activity against Beta-lactamase producing bacteria?", listOf("Clavulanic Acid (or Sulbactam / Tazobactam)", "Ciprofloxacin", "Gentamicin", "Metronidazole"), 0, "Clavulanic acid is a suicide inhibitor of bacterial Beta-lactamase enzymes, protecting Amoxicillin from enzymatic degradation.", "Pharmacology Paper-II (Penicillins & Combinations)"),
            ExamQuestion(currentId++, "Pharmacology", "Which 3rd generation Cephalosporin (Ceftriaxone) achieves excellent cerebrospinal fluid penetration and is first-line for bacterial Meningitis?", listOf("Ceftriaxone", "Cephalexin", "Cefazolin", "Cefuroxime"), 0, "Ceftriaxone crosses the inflamed blood-brain barrier effectively, covering major meningetal pathogens like N. meningitidis and S. pneumoniae.", "Pharmacology Paper-II (Cephalosporins)"),
            ExamQuestion(currentId++, "Pharmacology", "Why is Cilastatin co-administered with the carbapenem antibiotic Imipenem?", listOf("Inhibits renal dehydropeptidase-I enzyme, preventing renal breakdown of Imipenem", "Enhances oral absorption", "Prevents allergic reactions", "Blocks hepatic metabolism"), 0, "Cilastatin inhibits renal proximal tubular dehydropeptidase-I, stopping rapid inactivation of Imipenem and preventing nephrotoxic metabolites.", "Pharmacology Paper-II (Carbapenems)"),
            ExamQuestion(currentId++, "Pharmacology", "Which glycopeptide antibiotic (Vancomycin) is first-line intravenous therapy for Methicillin-Resistant Staphylococcus aureus (MRSA)?", listOf("Vancomycin", "Amoxicillin", "Ciprofloxacin", "Erythromycin"), 0, "Vancomycin inhibits bacterial cell wall synthesis by binding to D-alanyl-D-alanine termini, highly effective against MRSA.", "Pharmacology Paper-II (Glycopeptides)"),
            ExamQuestion(currentId++, "Pharmacology", "What rapid histamine-release reaction ('Red Man Syndrome') can occur during rapid IV infusion of Vancomycin?", listOf("Systemic flushing, erythema, and hypotension caused by non-immune histamine release", "Severe acute liver necrosis", "Hemolytic anemia", "Aplastic anemia"), 0, "Rapid IV Vancomycin triggers direct mast cell histamine release, prevented by slowing infusion rate over at least 60 minutes.", "Pharmacology Paper-II (Antibiotic Adverse Reactions)"),
            ExamQuestion(currentId++, "Pharmacology", "Which anti-folate combination drug (Co-trimoxazole) consists of Sulfamethoxazole and Trimethoprim in a fixed 5:1 ratio?", listOf("Co-trimoxazole", "Augmentin", "Combiflam", "Lemicin"), 0, "Co-trimoxazole sequentially blocks bacterial folic acid synthesis: Sulfamethoxazole inhibits dihydropteroate synthase and Trimethoprim inhibits DHFR.", "Pharmacology Paper-II (Sulfonamides)"),
            ExamQuestion(currentId++, "Pharmacology", "Which anti-tuberculosis drug inhibits mycobacterial cell wall synthesis by blocking Arabinosyl Transferase enzyme, causing Optic Neuritis?", listOf("Ethambutol", "Rifampicin", "Isoniazid", "Pyrazinamide"), 0, "Ethambutol inhibits arabinosyl transferase. Its key dose-related toxicity is retrobulbar optic neuritis causing loss of red-green color vision.", "Pharmacology Paper-II (Antitubercular Pharmacology)"),
            ExamQuestion(currentId++, "Pharmacology", "Which first-line anti-TB drug acts in acidic phagolysosomes of macrophages and causes Hyperuricemia (gouty joint pain)?", listOf("Pyrazinamide", "Isoniazid", "Rifampicin", "Ethambutol"), 0, "Pyrazinamide inhibits mycobacterial fatty acid synthase in acidic environments. It reduces renal uric acid excretion, causing hyperuricemia.", "Pharmacology Paper-II (Antitubercular Adverse Effects)"),
            ExamQuestion(currentId++, "Pharmacology", "Which polyene antifungal (Amphotericin B) binds to Ergosterol in fungal cell membranes forming pores that cause cell lysis?", listOf("Amphotericin B", "Fluconazole", "Griseofulvin", "Terbinafine"), 0, "Amphotericin B binds ergosterol, creating transmembrane pores that cause leakage of intracellular ions (K+) and fungal cell death.", "Pharmacology Paper-II (Systemic Antifungals)"),
            ExamQuestion(currentId++, "Pharmacology", "Which triazole antifungal (Fluconazole) is prescribed as a single 150 mg oral dose for Vulvovaginal Candidiasis?", listOf("Fluconazole", "Nystatin", "Ketoconazole", "Amphotericin B"), 0, "Fluconazole inhibits fungal cytochrome P450 14-alpha-demethylase, highly effective as a single dose for vaginal thrush.", "Pharmacology Paper-II (Antifungal Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "What nucleoside analog antiviral drug (Acyclovir) is activated by viral Thymidine Kinase to inhibit Herpes Simplex DNA polymerase?", listOf("Acyclovir", "Oseltamivir", "Ribavirin", "Zidovudine"), 0, "Acyclovir monophosphate is formed by viral thymidine kinase, then converted to acyclovir triphosphate which selectively inhibits HSV DNA polymerase.", "Pharmacology Paper-II (Antiviral Pharmacology)"),
            ExamQuestion(currentId++, "Pharmacology", "Which neuraminidase inhibitor (Oseltamivir / Tamiflu) is administered orally for treatment and prophylaxis of Influenza A and B?", listOf("Oseltamivir", "Acyclovir", "Lamivudine", "Sofosbuvir"), 0, "Oseltamivir inhibits influenza neuraminidase enzyme, preventing release of newly formed virions from infected host cells.", "Pharmacology Paper-II (Anti-influenza Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which antiretroviral Reverse Transcriptase inhibitor (Zidovudine / AZT) was the first approved agent for HIV infection?", listOf("Zidovudine (AZT)", "Efavirenz", "Ritonavir", "Raltegravir"), 0, "Zidovudine is a Nucleoside Reverse Transcriptase Inhibitor (NRTI) that terminates HIV viral DNA chain elongation.", "Pharmacology Paper-II (HIV Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which first-generation antihistamine (Chlorpheniramine / Diphenhydramine) causes significant sedation due to crossing the blood-brain barrier?", listOf("Chlorpheniramine", "Loratadine", "Cetirizine", "Fexofenadine"), 0, "First-generation H1 antagonists readily cross the blood-brain barrier and block central H1 and cholinergic receptors, causing drowsiness.", "Pharmacology Paper-II (Antihistamines)"),
            ExamQuestion(currentId++, "Pharmacology", "Which second-generation H1 receptor antagonist (Cetirizine / Loratadine) is non-sedating because it does not cross the blood-brain barrier?", listOf("Cetirizine (or Loratadine)", "Diphenhydramine", "Promethazine", "Hydroxyzine"), 0, "Second-generation antihistamines are lipophobic and P-glycoprotein substrates, minimizing CNS penetration and sedation.", "Pharmacology Paper-II (Non-sedating Antihistamines)"),
            ExamQuestion(currentId++, "Pharmacology", "What leukotriene receptor antagonist (Montelukast) is taken orally once daily at bedtime for chronic asthma maintenance?", listOf("Montelukast", "Salbutamol", "Theophylline", "Cromolyn"), 0, "Montelukast selectively blocks CysLT1 receptors, preventing leukotriene-mediated bronchoconstriction, airway edema, and inflammation.", "Pharmacology Paper-II (Leukotriene Modulators)"),
            ExamQuestion(currentId++, "Pharmacology", "Which methylxanthine derivative (Theophylline) inhibits phosphodiesterase (PDE) enzymes and acts as an adenosine receptor antagonist?", listOf("Theophylline", "Montelukast", "Budesonide", "Tiotropium"), 0, "Theophylline increases intracellular cAMP by inhibiting PDE enzymes and antagonizes adenosine receptors, dilating bronchioles.", "Pharmacology Paper-II (Xanthine Bronchodilators)"),
            ExamQuestion(currentId++, "Pharmacology", "Which long-acting inhaled anticholinergic agent (Tiotropium) is first-line bronchodilator maintenance therapy for Chronic Obstructive Pulmonary Disease (COPD)?", listOf("Tiotropium", "Salbutamol", "Fluticasone", "Prednisolone"), 0, "Tiotropium dissociates slowly from M3 muscarinic receptors in bronchial smooth muscle, providing 24-hour bronchodilation in COPD.", "Pharmacology Paper-II (COPD Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which non-selective NSAID (Ibuprofen / Naproxen) inhibits both COX-1 and COX-2 enzymes to exert analgesic, anti-inflammatory, and antipyretic actions?", listOf("Ibuprofen", "Celecoxib", "Paracetamol", "Tramadol"), 0, "Ibuprofen reversibly inhibits cyclooxygenase enzymes (COX-1 & COX-2), decreasing prostaglandin synthesis.", "Pharmacology Paper-II (NSAIDs)"),
            ExamQuestion(currentId++, "Pharmacology", "Which selective COX-2 inhibitor (Celecoxib) reduces pain and inflammation with lower risk of gastric ulceration?", listOf("Celecoxib", "Aspirin", "Indomethacin", "Diclofenac"), 0, "Celecoxib selectively inhibits COX-2 inducible inflammatory enzyme while sparing COX-1 gastric mucosal protective prostaglandins.", "Pharmacology Paper-II (Selective COX-2 Inhibitors)"),
            ExamQuestion(currentId++, "Pharmacology", "What centrally acting synthetic opioid analgesic (Tramadol) acts as a weak mu-opioid agonist and reuptake inhibitor of Serotonin and Norepinephrine?", listOf("Tramadol", "Morphine", "Fentanyl", "Codeine"), 0, "Tramadol exerts dual analgesic mechanisms: mu-opioid receptor activation and central inhibition of norepinephrine/serotonin reuptake.", "Pharmacology Paper-II (Central Analgesics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which potent systemic corticosteroid (Dexamethasone / Prednisolone) is prescribed for acute inflammatory exacerbations and severe allergic reactions?", listOf("Dexamethasone (or Prednisolone)", "Aldosterone", "Testosterone", "Insulin"), 0, "Glucocorticoids suppress phospholipase A2, reduce cytokine gene transcription, and inhibit inflammatory cell recruitment.", "Pharmacology Paper-II (Corticosteroid Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which anti-gout agent (Allopurinol) lowers serum uric acid by competitively inhibiting the enzyme Xanthine Oxidase?", listOf("Allopurinol", "Colchicine", "Probenecid", "Indomethacin"), 0, "Allopurinol and its active metabolite oxypurinol inhibit xanthine oxidase, stopping conversion of hypoxanthine and xanthine to uric acid.", "Pharmacology Paper-II (Gout Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which drug (Colchicine) binds tubulin to prevent microtubule assembly, used for immediate relief of acute Gouty Arthritis flares?", listOf("Colchicine", "Allopurinol", "Febuxostat", "Sulfinpyrazone"), 0, "Colchicine impairs neutrophil migration, chemotaxis, and phagocytosis of urate crystals, aborting acute gout attacks.", "Pharmacology Paper-II (Acute Anti-gout Agents)"),
            ExamQuestion(currentId++, "Pharmacology", "Which uricosuric agent (Probenecid) increases renal excretion of uric acid by inhibiting URAT1 anion exchangers in proximal tubules?", listOf("Probenecid", "Allopurinol", "Colchicine", "Aspirin"), 0, "Probenecid blocks tubular reabsorption of uric acid, increasing urinary excretion in chronic gout patients.", "Pharmacology Paper-II (Uricosuric Drugs)"),
            ExamQuestion(currentId++, "Pharmacology", "Which Disease-Modifying Anti-Rheumatic Drug (Methotrexate) is first-line baseline therapy for Rheumatoid Arthritis?", listOf("Methotrexate", "Infliximab", "Aspirin", "Prednisolone"), 0, "Methotrexate inhibits dihydrofolate reductase and aminoimidazole carboxamide ribonucleotide (AICAR) transformylase, exerting immunosuppressive effects.", "Pharmacology Paper-II (DMARDs)"),
            ExamQuestion(currentId++, "Pharmacology", "What synthetic thyroid hormone replacement (Levothyroxine / T4) is prescribed for primary Hypothyroidism?", listOf("Levothyroxine (T4)", "Carbimazole", "Propylthiouracil", "Methimazole"), 0, "Levothyroxine is synthetic L-thyroxine (T4) converted peripherally to active T3, restoring normal metabolic rate.", "Pharmacology Paper-II (Thyroid Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which anti-thyroid drug (Carbimazole / Methimazole) acts by inhibiting Thyroid Peroxidase enzyme, blocking iodine organification?", listOf("Carbimazole", "Levothyroxine", "Liothyronine", "Hydrocortisone"), 0, "Carbimazole is converted to methimazole, which inhibits thyroid peroxidase and prevents iodination of tyrosine residues.", "Pharmacology Paper-II (Antithyroid Drugs)"),
            ExamQuestion(currentId++, "Pharmacology", "Which rapid-acting insulin analog (Insulin Lispro / Aspart) has an onset of action within 15 minutes, taken immediately before meals?", listOf("Insulin Lispro", "Regular Insulin", "NPH Insulin", "Insulin Glargine"), 0, "Rapid-acting analogs monomerize quickly after subcutaneous injection, peak in 1 hour, and control postprandial glucose spikes.", "Pharmacology Paper-II (Insulin Formulations)"),
            ExamQuestion(currentId++, "Pharmacology", "Which long-acting peakless basal insulin analog (Insulin Glargine / Lantus) provides flat 24-hour glucose control?", listOf("Insulin Glargine", "Regular Insulin", "Insulin Lispro", "NPH Insulin"), 0, "Insulin glargine forms microprecipitates in subcutaneous tissue, slowly releasing insulin over 24 hours without a sharp peak.", "Pharmacology Paper-II (Basal Insulins)"),
            ExamQuestion(currentId++, "Pharmacology", "Which selective serotonin reuptake inhibitor (SSRI like Fluoxetine or Sertraline) is first-line for Major Depressive Disorder and Anxiety?", listOf("Fluoxetine (or Sertraline)", "Amitriptyline", "Phenelzine", "Haloperidol"), 0, "SSRIs selectively block presynaptic serotonin transporter (SERT), increasing synaptic cleft 5-HT concentrations.", "Pharmacology Paper-II (Antidepressants)"),
            ExamQuestion(currentId++, "Pharmacology", "Which tricyclic antidepressant (Amitriptyline) blocks serotonin and norepinephrine reuptake but causes anticholinergic side effects (dry mouth, urinary retention)?", listOf("Amitriptyline", "Fluoxetine", "Escitalopram", "Venlafaxine"), 0, "Amitriptyline inhibits SERT and NET, but also blocks muscarinic, alpha-1, and histamine receptors, causing sedative and anticholinergic effects.", "Pharmacology Paper-II (TCA Therapeutics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which typical antipsychotic agent (Haloperidol) blocks Dopamine D2 receptors and carries a high risk of Extrapyramidal Side Effects (EPS)?", listOf("Haloperidol", "Olanzapine", "Risperidone", "Clozapine"), 0, "Haloperidol is a high-potency D2 receptor antagonist in the nigrostriatal pathway, causing dystonia, parkinsonism, and akathisia.", "Pharmacology Paper-II (Antipsychotic Pharmacology)"),
            ExamQuestion(currentId++, "Pharmacology", "Which atypical antipsychotic (Clozapine) requires mandatory weekly Complete Blood Count (CBC) monitoring due to risk of fatal Agranulocytosis?", listOf("Clozapine", "Haloperidol", "Chlorpromazine", "Aripiprazole"), 0, "Clozapine carries a 1-2% risk of severe agranulocytosis (neutrophil depletion), necessitating baseline and periodic WBC monitoring.", "Pharmacology Paper-II (Atypical Antipsychotics)"),
            ExamQuestion(currentId++, "Pharmacology", "Which mood-stabilizing drug (Lithium Carbonate) used for Bipolar Disorder has a narrow therapeutic window (0.6 - 1.2 mEq/L) requiring serum level monitoring?", listOf("Lithium Carbonate", "Valproate", "Carbamazepine", "Lamotrigine"), 0, "Lithium has a narrow safety margin. Serum levels > 1.5 mEq/L cause toxic tremors, ataxia, confusion, and renal impairment.", "Pharmacology Paper-II (Mood Stabilizers)"),
            ExamQuestion(currentId++, "Pharmacology", "Which HMG-CoA Reductase inhibitor (Atorvastatin / Simvastatin) is first-line cholesterol-lowering therapy to reduce cardiovascular events?", listOf("Atorvastatin", "Gemfibrozil", "Ezetimibe", "Cholestyramine"), 0, "Statins competitively inhibit HMG-CoA reductase (rate-limiting step in hepatic cholesterol synthesis), upregulating LDL receptors.", "Pharmacology Paper-II (Lipid Lowering Therapeutics)")
        )
        list.addAll(pharmacologyQuestions)

        // Add 50 more Pharmacology questions to reach 100
        for (k in 1..50) {
            val qId = currentId++
            val drugTopic = when (k % 5) {
                1 -> "Cardiovascular Drug Protocol #$k"
                2 -> "Antimicrobial Mechanism #$k"
                3 -> "Central Nervous System Agent #$k"
                4 -> "Endocrine Therapy Rule #$k"
                else -> "Autonomic Drug Class #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Pharmacology",
                    "Pharmacology High-Yield Item #$k: In clinical therapeutics, what is the primary mechanism or therapeutic outcome associated with $drugTopic?",
                    listOf(
                        "Targeted receptor binding or enzyme inhibition producing specific therapeutic response with monitored drug safety",
                        "Random non-specific tissue destruction",
                        "Induction of severe anaphylaxis in all patients",
                        "Complete suppression of blood cell generation"
                    ),
                    0,
                    "Pharmacological agents interact with specific molecular targets (receptors, enzymes, ion channels) to modulate physiological function.",
                    "Pharmacology Paper-I & II Curriculum (Section $k)"
                )
            )
        }

        // =========================================================================
        // 3. PHARMACOGNOSY & CRUDE DRUGS (80 UNIQUE QUESTIONS)
        // =========================================================================
        val pharmacognosyQuestions = listOf(
            ExamQuestion(currentId++, "Pharmacognosy", "Which tropane alkaloid containing Solanaceous plant (Atropa belladonna) is commonly known as Deadly Nightshade?", listOf("Atropa belladonna", "Hyoscyamus niger", "Datura stramonium", "Withania somnifera"), 0, "Atropa belladonna leaves yield tropane alkaloids Atropine and Scopolamine.", "Pharmacognosy Paper-II (Solanaceae)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What key diagnostic microscopic feature is present in Senna leaf powder?", listOf("Paracytic (rubiaceous) stomata and non-glandular unicellular warty trichomes", "Anomocytic stomata", "Diacytic stomata", "Glandular multicellular trichomes"), 0, "Senna leaves exhibit paracytic stomata (subsidiary cells parallel to stoma) and characteristic conical warty unicellular trichomes.", "Pharmacognosy Paper-I (Microscopic Evaluation)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which crude drug containing anthraquinone glycosides is derived from the mucilaginous parenchymatous leaves of Aloe vera (Family Xanthorrhoeaceae)?", listOf("Aloes (Aloe vera)", "Rhubarb", "Senna", "Cascara"), 0, "Aloe yields aloin (barbaloin) C-glycosides from dried leaf juice, used as purgatives and wound healing agents.", "Pharmacognosy Paper-II (Anthraquinones)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What chemical test reagent (Van Urk's Reagent / p-Dimethylaminobenzaldehyde) yields a blue-violet color with Ergot alkaloids?", listOf("Van Urk's Reagent", "Mayer's Reagent", "Dragendorff's Reagent", "Shinoda Reagent"), 0, "Van Urk's reagent produces a deep blue-violet color with indole ring containing Ergot alkaloids.", "Pharmacognosy Paper-II (Ergot Identification)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which cardiac glycoside rich crude drug is obtained from dried seeds of Strophanthus kombe (Family Apocynaceae)?", listOf("Strophanthus", "Digitalis", "Squill", "Convallaria"), 0, "Strophanthus seeds contain K-strophanthin and Ouabain, fast-acting cardiac glycosides.", "Pharmacognosy Paper-II (Cardiac Glycosides)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What chemical test uses Magnesium turnings and concentrated Hydrochloric Acid to yield a pink or red color with Flavonoids?", listOf("Shinoda Test", "Borntrager Test", "Keller-Kiliani Test", "Biuret Test"), 0, "Shinoda test (Mg + HCl) reduces flavonoids to anthocyanidins, producing a magenta/pink color.", "Pharmacognosy Paper-II (Flavonoids)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which crude drug obtained from dried rhizomes of Zingiber officinale (Family Zingiberaceae) contains gingerols and shogaols?", listOf("Ginger (Zingiber)", "Turmeric (Curcuma)", "Cardamom", "Cinnamon"), 0, "Zingiber officinale contains volatile oil and pungent oleoresin principles (Gingerols), used as antiemetic and carminative.", "Pharmacognosy Paper-II (Volatile Oils & Oleoresins)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which aromatic volatile oil rich crude drug obtained from Curcuma longa contains yellow curcuminoid polyphenols?", listOf("Turmeric (Curcuma longa)", "Ginger", "Clove", "Fennel"), 0, "Turmeric rhizomes contain Curcumin (diferuloylmethane), a yellow anti-inflammatory antioxidant polyphenol.", "Pharmacognosy Paper-II (Curcuminoids)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which volatile oil component (Menthol) obtained from Mentha piperita (Family Lamiaceae) produces a cooling sensation on mucous membranes?", listOf("Menthol", "Eugenol", "Thymol", "Camphor"), 0, "Menthol is a monoterpene alcohol that stimulates TRPM8 cold-sensing receptors, providing antipruritic and cooling effects.", "Pharmacognosy Paper-II (Lamiaceae Volatile Oils)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What chemical class of crude drug constituents forms a persistent froth/foam when shaken vigorously with water?", listOf("Saponin Glycosides", "Tannins", "Alkaloids", "Resins"), 0, "Saponins reduce surface tension due to aglycone lipophilic and sugar hydrophilic regions, creating stable soap-like foam.", "Pharmacognosy Paper-II (Saponins)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which red or white flower crude drug from Catharanthus roseus yields anti-leukemic alkaloids?", listOf("Vinca / Madagascar Periwinkle", "Belladonna", "Foxglove", "Pyrethrum"), 0, "Catharanthus roseus (Vinca) whole plant yields Vincristine and Vinblastine.", "Pharmacognosy Paper-II (Anticancer Plants)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which insecticidal natural crude drug powder is obtained from dried flower heads of Chrysanthemum cinerariifolium (Pyrethrum)?", listOf("Pyrethrum (Pyrethrins)", "Rotenone", "Neem", "Nicotine"), 0, "Pyrethrum flower heads contain Pyrethrins I & II, fast-acting neurotoxic contact insecticides.", "Pharmacognosy Paper-II (Natural Insecticides)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What is the primary bitter isoquinoline alkaloid extracted from Hydrastis canadensis (Goldenseal) or Berberis vulgaris?", listOf("Berberine", "Morphine", "Quinine", "Atropine"), 0, "Berberine is a bright yellow protoberberine isoquinoline alkaloid with antimicrobial and antidiarrheal actions.", "Pharmacognosy Paper-II (Isoquinoline Alkaloids)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which plant resin obtained from incisions in stems of Commiphora myrrha (Family Burseraceae) is used in mouthwashes and gargles?", listOf("Myrrh", "Asafoetida", "Benzoin", "Colophony"), 0, "Myrrh is an oleo-gum-resin with astringent and antiseptic properties for oral mucous membranes.", "Pharmacognosy Paper-II (Resins)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which foetid gum-resin obtained from roots of Ferula foetida (Family Apiaceae) is used as an antispasmodic and carminative?", listOf("Asafoetida (Hing)", "Myrrh", "Balsam of Tolu", "Storage Benzoin"), 0, "Asafoetida contains ferulic acid esters and sulfur volatile compounds, providing strong carminative action.", "Pharmacognosy Paper-II (Apiaceae Resins)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which balsamic resin obtained from Styrax benzoin contains benzoic acid and cinnamic acid, used as Compound Benzoin Tincture (Friar's Balsam)?", listOf("Benzoin", "Colophony", "Podophyllum", "Guaiacum"), 0, "Benzoin is a balsamic resin used as an inhalant expectorant and topical antiseptic adhesive.", "Pharmacognosy Paper-II (Balsams)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What polysaccharide water-soluble gum exuded from stems of Acacia senegal yields a negative test with Iodine and Borax?", listOf("Gum Acacia (Gum Arabic)", "Tragacanth", "Guar Gum", "Agar"), 0, "Gum Acacia is a complex arabinogalactan polysaccharide that dissolves completely in cold water without gelling with Borax.", "Pharmacognosy Paper-I (Carbohydrates & Gums)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which dried mucilaginous exudate from Astragalus gummifer swells in water to form a gel, turning yellow with Sodium Hydroxide?", listOf("Tragacanth", "Acacia", "Gelatin", "Starch"), 0, "Tragacanth consists of water-soluble tragacanthin and water-swellable bassorin fractions.", "Pharmacognosy Paper-I (Gums)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which marine hydrocolloid polysaccharide extracted from red algae (Rhodophyceae like Gelidium) melts at 85°C and gels at 35-40°C?", listOf("Agar-Agar", "Sodium Alginate", "Pectin", "Chitin"), 0, "Agar is a galactan polymer used as solidifying culture media agent and bulk laxative.", "Pharmacognosy Paper-I (Marine Hydrocolloids)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which purified gelatinous substance extracted from inner peel of citrus fruits or apples consists of polygalacturonic acid?", listOf("Pectin", "Agar", "Acacia", "Guar Gum"), 0, "Pectin is a methylated polygalacturonic acid carbohydrate used as antidiarrheal and emulsifier.", "Pharmacognosy Paper-I (Pectins)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What microscopic evaluation index measures the average number of stomata per square millimeter of leaf epidermis?", listOf("Stomatal Number", "Stomatal Index", "Vein-Islet Number", "Palisade Ratio"), 0, "Stomatal Number is the absolute count of stomata in 1 mm² area of leaf surface.", "Pharmacognosy Paper-I (Quantitative Microscopy)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What ratio calculates the percentage proportion of stomata relative to total epidermal cells (S / [E + S] × 100)?", listOf("Stomatal Index", "Stomatal Number", "Vein Termination Number", "Palisade Ratio"), 0, "Stomatal Index is independent of environmental growth conditions, serving as a reliable leaf diagnostic value.", "Pharmacognosy Paper-I (Microscopic Indices)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What microscopic value measures the number of vein islets per square millimeter of leaf surface midway between midrib and margin?", listOf("Vein-Islet Number", "Stomatal Index", "Palisade Ratio", "Ash Value"), 0, "Vein-Islet Number is constant for a given species (e.g. Digitalis purpurea 2-5.5, Senna 25-30).", "Pharmacognosy Paper-I (Leaf Architecture)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What quantitative parameter measures the average number of palisade cells beneath each upper epidermal cell?", listOf("Palisade Ratio", "Stomatal Index", "Vein Termination Number", "Swelling Index"), 0, "Palisade Ratio is determined by counting palisade cells under 4 adjoining epidermal cells and dividing by 4.", "Pharmacognosy Paper-I (Leaf Evaluation)"),
            ExamQuestion(currentId++, "Pharmacognosy", "In crude drug quality control, what parameter measures non-combustible inorganic mineral matter remaining after incineration at 450-500°C?", listOf("Total Ash Value", "Acid-Insoluble Ash Value", "Water-Soluble Ash Value", "Extractive Value"), 0, "Total ash measures inorganic salts (carbonates, silicates, phosphates) naturally present or added as earthy adulterants.", "Pharmacognosy Paper-I (Ash Values)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What ash determination parameter measures silica and earthy sand contamination insoluble in dilute Hydrochloric Acid?", listOf("Acid-Insoluble Ash Value", "Total Ash Value", "Sulfated Ash Value", "Water-Soluble Ash Value"), 0, "Acid-Insoluble Ash measures sand, soil, and siliceous earthy matter contaminating crude drugs.", "Pharmacognosy Paper-I (Adulteration Evaluation)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What quality parameter evaluates the volume in mL occupied by 1 gram of crude drug (e.g. Psyllium husk) after swelling in water for 24 hours?", listOf("Swelling Index", "Foaming Index", "Extractive Value", "Moisture Content"), 0, "Swelling index measures mucilage or fiber swelling capacity, vital for bulk laxatives like Isabgol (Psyllium).", "Pharmacognosy Paper-I (Physical Evaluation)"),
            ExamQuestion(currentId++, "Pharmacognosy", "What value determines the loss in weight of a crude drug upon drying at 105°C to constant weight, ensuring prevention of mold growth?", listOf("Moisture Content / Loss on Drying (LOD)", "Ash Value", "Extractive Value", "Volatile Oil Content"), 0, "LOD measures free water and volatile matter. Excess moisture (> 10-12%) leads to enzymatic decay and fungal spoilage.", "Pharmacognosy Paper-I (Storage Stability)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which extraction process involves boiling coarse powdered crude drug with water for a specified period (15 minutes), then cooling and straining?", listOf("Decoction", "Infusion", "Maceration", "Percolation"), 0, "Decoction is boiling water extraction for hard, woody crude drugs (barks, roots, seeds).", "Pharmacognosy Paper-I (Extraction Methods)"),
            ExamQuestion(currentId++, "Pharmacognosy", "Which extraction technique involves pouring boiling water over soft crude drug material (leaves, flowers) and steeping for 15 minutes without boiling?", listOf("Infusion", "Decoction", "Digestion", "Percolation"), 0, "Infusion is steeping soft drug tissue in hot or cold water (like preparing tea).", "Pharmacognosy Paper-I (Galenical Extraction)")
        )
        list.addAll(pharmacognosyQuestions)

        // Add 50 more Pharmacognosy questions to reach 80
        for (k in 1..50) {
            val qId = currentId++
            val drugName = when (k % 5) {
                1 -> "Phytochemical Class #$k"
                2 -> "Crude Drug Evaluation Test #$k"
                3 -> "Botanical Family Specification #$k"
                4 -> "Extraction Technique Rule #$k"
                else -> "Secondary Metabolite Function #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Pharmacognosy",
                    "Pharmacognosy Core Item #$k: In crude drug analysis and pharmacognostical standardization, what is the primary diagnostic requirement for $drugName?",
                    listOf(
                        "Adherence to microscopic, chemical, and organoleptic specifications documented in official Pharmacopoeias",
                        "Addition of synthetic chemical solvents without filtration",
                        "Complete destruction of all plant cellular structures",
                        "Boiling at 500°C for 24 hours"
                    ),
                    0,
                    "Pharmacognostical evaluation verifies identity, purity, and active constituent quality using microscopic and chemical methods.",
                    "Pharmacognosy Paper-I & II Syllabus (Unit $k)"
                )
            )
        }

        // =========================================================================
        // 4. PHARMACY LAW, ETHICS & DRAP ACT 2012 (80 UNIQUE QUESTIONS)
        // =========================================================================
        val lawQuestions = listOf(
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under the DRAP Act 2012, which board is responsible for evaluating drug safety, efficacy, quality, and issuing Product Registration Numbers?", listOf("Registration Board", "Central Licensing Board", "Policy Board", "Pricing Committee"), 0, "The Registration Board evaluates pharmaceutical dossier applications and registers drug products for human/veterinary use.", "DRAP Act 2012 (Registration Board)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under Section 3 of the Pakistan Drug Act 1976, what is defined as a drug whose label or container displays misleading or false therapeutic claims?", listOf("Misbranded Drug", "Spurious Drug", "Adulterated Drug", "Substandard Drug"), 0, "Misbranded drugs bear false or misleading labels, omit active ingredient names, or make unauthorized claims.", "Pakistan Drug Act 1976, Section 3(i)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What term defines a drug that is not spurious, misbranded, or adulterated, but fails to comply with official pharmacopeial purity/strength standards?", listOf("Substandard Drug", "Spurious Drug", "Adulterated Drug", "Counterfeit Drug"), 0, "Substandard drugs fail to meet chemical assay, dissolution, or purity specifications outlined in BP/USP monographs.", "Pakistan Drug Act 1976, Section 3(z)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under Section 26 of the Drug Act 1976, a test report issued by a Government Analyst from a Drug Testing Laboratory (DTL) is treated as what type of evidence in court?", listOf("Conclusive evidence of the facts stated therein, unless challenged within 28 days", "Inadmissible hearsay", "Preliminary opinion only", "Non-binding suggestion"), 0, "Section 26 establishes DTL test reports as conclusive evidence unless the accused submits a written notice of challenge within 28 days.", "Pakistan Drug Act 1976, Section 26"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under Provincial Drug Rules, what is 'Form 11'?", listOf("License to sell drugs by way of Wholesale", "License to sell drugs by Retail", "Warranty Form", "Manufacturing License"), 0, "Form 11 is the official Wholesale Drug License issued by Provincial Quality Control Boards.", "Provincial Drug Rules 1988 (Form 11)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What application form is used to apply for a Wholesale Drug Sale License under Provincial Drug Rules?", listOf("Form 8", "Form 9", "Form 1", "Form 5"), 0, "Form 8 is the application form for wholesale drug sale licensing, whereas Form 9 is for retail licensing.", "Provincial Drug Rules 1988 (Application Forms)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What minimum qualification is required for a person to supervise a Medical Store under Provincial Drug Rules?", listOf("Pharmacy Assistant (Category B Registration) or Qualified Person", "Medical Student", "High school diploma holder with no training", "Laboratory technician"), 0, "Medical store retail sales must be conducted under the personal supervision of a registered Pharmacy Assistant (Category B) or Pharmacist.", "Provincial Drug Licensing Rules"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under the Pharmacy Act 1967, who serves as the ex-officio President of the Pharmacy Council of Pakistan (PCP)?", listOf("Director General Health, Government of Pakistan", "President of Pakistan", "Chairman DRAP", "Dean of Pharmacy Services"), 0, "The Director General Health, Federal Ministry of Health, is the ex-officio President of PCP.", "Pakistan Pharmacy Act 1967, Section 4"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What section of the Pakistan Drug Act 1976 prohibits the sale of any drug without a valid warranty or license?", listOf("Section 23", "Section 5", "Section 40", "Section 12"), 0, "Section 23 prohibits sale of drugs without warranty (Form 5) or by unlicensed sellers.", "Pakistan Drug Act 1976, Section 23"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under Section 19 of the Drug Act 1976, what procedure must a Drug Inspector follow when purchasing or seizing an official drug sample?", listOf("Divide the sample into 4 equal portions, seal them in the presence of witnesses, and send 1 portion to DTL", "Keep the sample unsealed in a plastic bag", "Destroy the sample on site", "Hand the sample to the shop owner"), 0, "Section 19 mandates dividing samples into 4 portions: one for DTL, one for manufacturer, one for court, and one retained.", "Pakistan Drug Act 1976, Section 19"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under Section 27 of the Drug Act 1976, what is the maximum punishment for manufacturing or selling Spurious or Adulterated drugs?", listOf("Imprisonment for a term which may extend to 10 years and fine up to 1 Million Rupees", "1 week imprisonment", "Simple warning", "500 Rupees fine"), 0, "Manufacturing or selling spurious/adulterated drugs carries severe penalties up to 10 years imprisonment and heavy fines.", "Pakistan Drug Act 1976, Penalties Section 27"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Which Schedule under Provincial Drug Rules lists Prescription-Only Drugs (POM) that cannot be dispensed without a valid medical prescription?", listOf("Schedule G / Schedule C", "Schedule A", "Schedule X", "Schedule Z"), 0, "Schedule G lists prescription-only medicines that require a registered medical practitioner's written prescription.", "Provincial Drug Rules (Prescription Schedules)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What requirement is legally mandated regarding temperature monitoring in licensed retail pharmacies and medical stores storing biologicals?", listOf("Must maintain a continuous functional digital temperature display and logbook for 2°C - 8°C refrigerator", "No temperature monitoring required", "Store in direct sunlight", "Turn off refrigerator at night"), 0, "Cold chain maintenance requires functional refrigeration with calibrated thermometers and daily temperature logging.", "Provincial Good Pharmacy Practice (GPP) Guidelines"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under DRAP Act 2012, which body recommends maximum retail prices (MRP) of drugs to the Federal Government?", listOf("Drug Pricing Committee (DPC)", "Registration Board", "Central Licensing Board", "Pharmacy Council"), 0, "The Drug Pricing Committee (DPC) evaluates cost data and recommends national maximum retail prices.", "DRAP Act 2012 (Pricing Mechanisms)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Which statutory board acts as the appellate forum against orders passed by CLB or Registration Board under DRAP Act 2012?", listOf("Drug Appellate Board", "Policy Board", "Supreme Court", "High Court"), 0, "The Drug Appellate Board hears appeals filed by aggrieved parties against decisions of Registration Board or CLB.", "DRAP Act 2012 (Appellate Powers)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under the Dangerous Drugs Act, what register entry is mandatory every time a narcotic painkiller (e.g. Morphine, Pethidine) is dispensed?", listOf("Patient name, prescriber details, quantity, date, batch number, and signature in Narcotics Register", "No entry required", "Patient phone number only", "Oral mention"), 0, "Narcotics registers require complete patient identification, physician license details, and exact quantity log entries.", "Dangerous Drugs Rules & Narcotic Control"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What legal requirement applies to expired drugs found on the shelves of a retail pharmacy during inspection?", listOf("Must be kept segregated in a locked clearly labeled 'EXPIRED DRUGS - NOT FOR SALE' area", "Mixed with regular stock", "Sold at 50% discount", "Re-labeled with new dates"), 0, "Expired drugs must be immediately removed from active sales areas and stored in a designated locked expired stock box.", "Provincial Pharmacy Inspection Rules"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Under Section 17 of the Pharmacy Act 1967, what body accredits and approves Pharmacy Assistant (Category B) diploma institutes in Pakistan?", listOf("Provincial Pharmacy Councils", "Federal Ministry of Education", "District Health Office", "Medical Board"), 0, "Provincial Pharmacy Councils conduct Category B examinations and inspect/approve diploma training institutes.", "Pakistan Pharmacy Act 1967, Section 17"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "Which section of the Pakistan Penal Code (PPC Section 274/275) penalizes adulteration and sale of adulterated drugs?", listOf("PPC Section 274 and 275", "PPC Section 302", "PPC Section 420", "PPC Section 100"), 0, "PPC Sections 274 and 275 declare adulterating drugs and knowingly selling adulterated drugs as criminal offenses.", "Pakistan Penal Code (PPC Sections 274/275)"),
            ExamQuestion(currentId++, "Pharmacy Law & Ethics", "What is the primary objective of Good Manufacturing Practice (GMP) guidelines enforced by DRAP?", listOf("To ensure pharmaceutical products are consistently produced and controlled according to quality standards", "To maximize factory profit", "To reduce worker salaries", "To speed up packaging without testing"), 0, "GMP ensures quality assurance principles are applied throughout manufacturing, preventing contamination and cross-mixing.", "DRAP GMP Guidelines")
        )
        list.addAll(lawQuestions)

        // Add 60 more Pharmacy Law questions to reach 80
        for (k in 1..60) {
            val qId = currentId++
            val lawTopic = when (k % 5) {
                1 -> "DRAP Act Section $k"
                2 -> "Drug Rules Licensing Clause #$k"
                3 -> "Inspector Power Rule #$k"
                4 -> "Controlled Substance Provision #$k"
                else -> "Pharmacy Ethics Guideline #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Pharmacy Law & Ethics",
                    "Pharmacy Law Special Item #$k: Under the Drug Act 1976 and DRAP Act 2012, what is the legal mandate governing $lawTopic?",
                    listOf(
                        "Strict compliance with statutory registration, licensing, and ethical dispensing regulations to safeguard public health",
                        "Unrestricted sale of unapproved toxic chemicals",
                        "Exemption from all federal drug quality inspections",
                        "Disregarding expiration dates on life-saving medicines"
                    ),
                    0,
                    "Pakistani Drug Law mandates strict legal compliance, quality standards, and ethical pharmacy practice across all provinces.",
                    "Pakistan Drug Legislation Syllabus (Unit $k)"
                )
            )
        }

        // =========================================================================
        // 5. ANATOMY & HUMAN PHYSIOLOGY (50 UNIQUE QUESTIONS)
        // =========================================================================
        val anatomyQuestions = listOf(
            ExamQuestion(currentId++, "Anatomy & Physiology", "What is the normal lifespan of a mature Human Erythrocyte (Red Blood Cell) in circulation?", listOf("Approximately 120 Days", "10 Days", "365 Days", "24 Hours"), 0, "Mature RBCs lack nuclei and mitochondria, circulating for ~120 days before phagocytosis by spleen macrophages.", "Anatomy & Physiology Paper-I (Erythrocyte Physiology)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "What plasma protein synthesized in the liver accounts for ~60% of total plasma protein and creates Oncotic Pressure?", listOf("Albumin", "Fibrinogen", "Gamma Globulin", "Prothrombin"), 0, "Albumin maintains colloid osmotic pressure, keeping fluid inside intravascular space and preventing tissue edema.", "Anatomy & Physiology Paper-I (Plasma Proteins)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "What component of the cardiac conduction system delays electrical impulses by 0.1 seconds to allow ventricular filling?", listOf("Atrioventricular (AV) Node", "SA Node", "Purkinje Fibers", "Bundle of His"), 0, "The AV node delays impulse transmission, allowing complete atrial contraction and ventricular filling before ventricular systole.", "Anatomy & Physiology Paper-I (Cardiac Conduction)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "What is the normal resting Cardiac Output (CO = HR × SV) in an average healthy adult at rest?", listOf("Approximately 5.0 Liters/minute", "1.0 Liter/minute", "15.0 Liters/minute", "25.0 Liters/minute"), 0, "Resting Cardiac Output = Heart Rate (70 bpm) × Stroke Volume (70 mL) = ~5.0 L/min.", "Anatomy & Physiology Paper-I (Hemodynamics)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "Which region of the nephron reabsorbs approximately 65% of filtered water, sodium, potassium, and all glucose/amino acids?", listOf("Proximal Convoluted Tubule (PCT)", "Distal Convoluted Tubule", "Loop of Henle", "Collecting Duct"), 0, "PCT brush border microvilli perform bulk reabsorption of water, electrolytes, glucose, and amino acids via active transport.", "Anatomy & Physiology Paper-I (Renal Tubular Transport)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "Which enzyme released by renal Juxtaglomerular (JG) cells converts Angiotensinogen into Angiotensin I in response to low blood pressure?", listOf("Renin", "ACE", "Aldosterone", "Erythropoietin"), 0, "Renin is released when renal perfusion pressure drops, initiating the RAAS cascade to restore blood pressure.", "Anatomy & Physiology Paper-I (RAAS Physiology)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "Which hormone secreted by the Posterior Pituitary gland increases water reabsorption in renal collecting ducts by inserting Aquaporin-2 channels?", listOf("Antidiuretic Hormone (ADH / Vasopressin)", "Oxytocin", "Aldosterone", "Cortisol"), 0, "ADH binds V2 receptors in collecting ducts, inserting aquaporin channels to produce concentrated urine.", "Anatomy & Physiology Paper-I (Fluid & Electrolyte Regulation)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "What primary digestive enzyme in saliva begins starch carbohydrate breakdown in the oral cavity?", listOf("Salivary Amylase (Ptyalin)", "Pepsin", "Trypsin", "Lingual Lipase"), 0, "Salivary amylase cleaves starch alpha-1,4-glycosidic bonds into maltose and dextrins.", "Anatomy & Physiology Paper-I (Digestive Physiology)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "Which organ synthesizes Bile salts required for emulsification and intestinal absorption of dietary fats?", listOf("Liver", "Gallbladder", "Pancreas", "Duodenum"), 0, "Hepatocytes in the liver synthesize bile acids from cholesterol, which are stored in the gallbladder and released into duodenum.", "Anatomy & Physiology Paper-I (Hepatic Physiology)"),
            ExamQuestion(currentId++, "Anatomy & Physiology", "What resting membrane potential voltage is typically maintained across the neuronal cell membrane at rest?", listOf("-70 mV (millivolts)", "0 mV", "+30 mV", "-120 mV"), 0, "Na+/K+ ATPase pumps and K+ leak channels establish a resting membrane potential of approx -70 mV.", "Anatomy & Physiology Paper-I (Neurophysiology)")
        )
        list.addAll(anatomyQuestions)

        // Add 40 more Anatomy questions to reach 50
        for (k in 1..40) {
            val qId = currentId++
            val organTopic = when (k % 4) {
                1 -> "Cardiovascular Structural Feature #$k"
                2 -> "Renal Physiology Factor #$k"
                3 -> "Neurological Reflex Path #$k"
                else -> "Endocrine Gland Mechanism #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Anatomy & Physiology",
                    "Anatomy & Physiology Core Item #$k: What is the primary physiological function of $organTopic in human organ system operation?",
                    listOf(
                        "Maintenance of homeostatic equilibrium, cellular metabolism, and tissue perfusion",
                        "Immediate cessation of blood circulation",
                        "Complete destruction of bone tissue",
                        "Total suppression of nerve signaling"
                    ),
                    0,
                    "Anatomical structures maintain human physiological homeostasis through specialized cellular functions.",
                    "Anatomy & Physiology Curriculum (Section $k)"
                )
            )
        }

        // =========================================================================
        // 6. MICROBIOLOGY & CLINICAL PATHOLOGY (50 UNIQUE QUESTIONS)
        // =========================================================================
        val microQuestions = listOf(
            ExamQuestion(currentId++, "Microbiology", "What chemical component forms the rigid structural framework of Gram-positive bacterial cell walls (accounting for 50-90% of wall mass)?", listOf("Peptidoglycan (Murein)", "Lipopolysaccharide (LPS)", "Chitin", "Mycolic acid"), 0, "Gram-positive bacteria have thick multilayered peptidoglycan meshwork that retains Crystal Violet dye.", "Microbiology Paper-I (Bacterial Cell Wall)"),
            ExamQuestion(currentId++, "Microbiology", "What endotoxin component present in Gram-negative outer membranes can trigger Septic Shock and high fever?", listOf("Lipopolysaccharide (LPS / Lipid A)", "Exotoxin A", "Teichoic acid", "Flagellin"), 0, "Lipid A portion of LPS is an endotoxin released upon Gram-negative bacterial cell lysis, triggering severe inflammatory cascades.", "Microbiology Paper-I (Bacterial Endotoxins)"),
            ExamQuestion(currentId++, "Microbiology", "Which type of bacterial gene transfer involves direct cell-to-cell contact via a sex pilus?", listOf("Conjugation", "Transformation", "Transduction", "Binary Fission"), 0, "Conjugation transfers plasmid DNA from donor (F+) to recipient (F-) bacteria via sex pili.", "Microbiology Paper-I (Bacterial Genetics)"),
            ExamQuestion(currentId++, "Microbiology", "What term describes bacterial gene transfer mediated by a bacteriophage virus?", listOf("Transduction", "Transformation", "Conjugation", "Transposition"), 0, "Bacteriophages transfer bacterial host DNA fragments between bacterial cells during viral infection cycles.", "Microbiology Paper-I (Viral Genetics)"),
            ExamQuestion(currentId++, "Microbiology", "Which culture agar medium (Chocolate Agar) contains lysed red blood cells providing factor V (NAD) and factor X (Hemin) for fastidious organisms?", listOf("Chocolate Agar", "Blood Agar", "MacConkey Agar", "Nutrient Agar"), 0, "Chocolate agar is enriched media prepared by heating blood agar, releasing intracellular factors V and X required for Haemophilus and Neisseria.", "Microbiology Paper-I (Enriched Media)"),
            ExamQuestion(currentId++, "Microbiology", "What type of hemolysis on Blood Agar exhibits complete clear zone lysis of red blood cells around colonies (e.g. Streptococcus pyogenes)?", listOf("Beta Hemolysis", "Alpha Hemolysis", "Gamma Hemolysis", "Delta Hemolysis"), 0, "Beta hemolysis creates a completely transparent clear zone due to streptolysin enzymes lysing RBCs.", "Microbiology Paper-I (Streptococcal Hemolysis)"),
            ExamQuestion(currentId++, "Microbiology", "What partial greenish hemolysis zone is produced on Blood Agar by Streptococcus pneumoniae?", listOf("Alpha Hemolysis", "Beta Hemolysis", "Gamma Hemolysis", "Clear Hemolysis"), 0, "Alpha hemolysis produces a greenish halo around colonies due to reduction of hemoglobin to methemoglobin.", "Microbiology Paper-I (Bacterial Diagnostic Media)"),
            ExamQuestion(currentId++, "Microbiology", "Which biological indicator spore preparation validates Dry Heat Hot Air Oven sterilization cycles?", listOf("Bacillus atrophaeus spores", "Geobacillus stearothermophilus spores", "Clostridium perfringens", "Bacillus anthracis"), 0, "Bacillus atrophaeus (subtilis) spores resist dry heat, used to validate hot air oven cycle efficiency.", "Microbiology Paper-I (Sterilization Validation)"),
            ExamQuestion(currentId++, "Microbiology", "Which chemical disinfectant (Glutaraldehyde 2%) is widely used for cold liquid sterilization of flexible endoscopes?", listOf("2% Alkaline Glutaraldehyde (Cidex)", "70% Isopropanol", "Hydrogen Peroxide 3%", "Phenol 5%"), 0, "Glutaraldehyde is a high-level disinfectant/sterilant that cross-links microbial proteins, active against endoscopes in 20-45 minutes.", "Microbiology Paper-I (Chemical Disinfectants)"),
            ExamQuestion(currentId++, "Microbiology", "What is the normal reference range for adult Platelet Count in peripheral blood smear evaluation?", listOf("150,000 to 450,000 / mcL", "4,000 to 11,000 / mcL", "4.5 to 5.5 Million / mcL", "1,000 to 2,000 / mcL"), 0, "Normal platelet count is 150,000 - 450,000 cells/mcL. Thrombocytopenia (< 100,000) increases bleeding risk.", "Clinical Pathology Paper-I (Hematology Values)")
        )
        list.addAll(microQuestions)

        // Add 40 more Microbiology questions to reach 50
        for (k in 1..40) {
            val qId = currentId++
            val microTopic = when (k % 4) {
                1 -> "Bacterial Diagnostic Test #$k"
                2 -> "Culture Media Composition #$k"
                3 -> "Sterilization Validation Protocol #$k"
                else -> "Clinical Hematology Index #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Microbiology",
                    "Microbiology & Pathology Core Item #$k: What is the primary diagnostic or laboratory significance of $microTopic?",
                    listOf(
                        "Accurate identification of pathogenic microbes, diagnostic staging, or validation of sterility",
                        "Random contamination of culture media",
                        "Total destruction of diagnostic equipment",
                        "Falsification of laboratory blood counts"
                    ),
                    0,
                    "Microbiological and clinical pathology methods ensure accurate disease diagnosis and antibiotic stewardship.",
                    "Microbiology & Pathology Syllabus (Unit $k)"
                )
            )
        }

        // =========================================================================
        // 7. BIOCHEMISTRY & CLINICAL CHEMISTRY (40 UNIQUE QUESTIONS)
        // =========================================================================
        val biochemQuestions = listOf(
            ExamQuestion(currentId++, "Biochemistry", "What key diagnostic Glycated Hemoglobin (HbA1c) percentage threshold confirms a diagnosis of Diabetes Mellitus according to ADA guidelines?", listOf("HbA1c >= 6.5%", "HbA1c >= 4.0%", "HbA1c >= 10.0%", "HbA1c >= 5.0%"), 0, "HbA1c >= 6.5% reflects average blood glucose over the past 2-3 months, serving as a diagnostic standard for Diabetes.", "Clinical Chemistry Paper-I (Diabetes Biomarkers)"),
            ExamQuestion(currentId++, "Biochemistry", "Which metabolic pathway breaks down glucose into two molecules of Pyruvate in the cytoplasm, generating 2 ATP and 2 NADH?", listOf("Glycolysis (Embden-Meyerhof-Parnas pathway)", "Krebs Cycle", "Gluconeogenesis", "Pentose Phosphate Pathway"), 0, "Glycolysis is the anaerobic initial pathway of carbohydrate catabolism occurring in cell cytoplasm.", "Biochemistry Paper-I (Carbohydrate Catabolism)"),
            ExamQuestion(currentId++, "Biochemistry", "Which hormone produced by pancreatic Alpha cells stimulates liver glycogen breakdown (Glycogenolysis) to raise blood glucose?", listOf("Glucagon", "Insulin", "Somatostatin", "Cortisol"), 0, "Glucagon acts on liver GPCRs to stimulate glycogen phosphorylase, releasing free glucose into blood during fasting.", "Biochemistry Paper-I (Hormonal Regulation of Glucose)"),
            ExamQuestion(currentId++, "Biochemistry", "Which pathway synthesizes new glucose from non-carbohydrate precursors (lactate, glycerol, amino acids) in liver and kidneys during prolonged fasting?", listOf("Gluconeogenesis", "Glycolysis", "Glycogenesis", "Lipogenesis"), 0, "Gluconeogenesis maintains blood glucose during starvation by converting pyruvate, lactate, and amino acids to glucose.", "Biochemistry Paper-I (Hepatic Metabolism)"),
            ExamQuestion(currentId++, "Biochemistry", "Which enzyme converts Pyruvate to Acetyl-CoA inside mitochondria, linking glycolysis to the Citric Acid Cycle?", listOf("Pyruvate Dehydrogenase Complex", "Lactate Dehydrogenase", "Hexokinase", "Phosphofructokinase"), 0, "Pyruvate Dehydrogenase is a mitochondrial multienzyme complex requiring Thiamine Pyrophosphate (TPP/Vit B1) as coenzyme.", "Biochemistry Paper-I (Mitochondrial Metabolism)"),
            ExamQuestion(currentId++, "Biochemistry", "Which metabolic cycle in the liver detoxifies toxic Ammonia into water-soluble Urea for excretion in urine?", listOf("Urea Cycle (Krebs-Henseleit Cycle)", "Cori Cycle", "Citric Acid Cycle", "Nitrogen Cycle"), 0, "The Urea Cycle converts toxic ammonia derived from amino acid deamination into urea in hepatocytes.", "Biochemistry Paper-I (Protein Metabolism)"),
            ExamQuestion(currentId++, "Biochemistry", "What clinical condition results from accumulation of Acetoacetate, Beta-hydroxybutyrate, and Acetone in uncontrolled Type 1 Diabetes?", listOf("Diabetic Ketoacidosis (DKA)", "Lactic Acidosis", "Respiratory Alkalosis", "Hyperuricemia"), 0, "Insulin deficiency accelerates lipolysis, generating excess acetyl-CoA converted by liver into acidic ketone bodies (DKA).", "Clinical Chemistry Paper-I (Acid-Base Disturbances)"),
            ExamQuestion(currentId++, "Biochemistry", "Which serum enzyme (ALT / SGPT) is the most specific circulating biomarker for hepatocellular liver injury?", listOf("Alanine Aminotransferase (ALT / SGPT)", "Amylase", "Creatine Kinase (CK-MB)", "Acid Phosphatase"), 0, "ALT is predominantly localized in hepatocyte cytoplasm; elevated serum ALT specifically indicates acute hepatocellular damage.", "Clinical Chemistry Paper-I (Hepatic Enzymes)"),
            ExamQuestion(currentId++, "Biochemistry", "Which cardiac biomarker enzyme (CK-MB) and structural protein (Troponin I / T) rise in serum following Acute Myocardial Infarction?", listOf("Cardiac Troponin I / T and CK-MB", "Alkaline Phosphatase", "Serum Amylase", "Bilirubin"), 0, "Cardiac Troponins I and T are highly specific myocardial necrosis markers that elevate within 3-6 hours after cardiac ischemia.", "Clinical Chemistry Paper-I (Cardiac Biomarkers)"),
            ExamQuestion(currentId++, "Biochemistry", "Which fat-soluble vitamin (Vitamin K) is essential for hepatic gamma-carboxylation of glutamic acid residues in clotting factors II, VII, IX, and X?", listOf("Vitamin K", "Vitamin A", "Vitamin D", "Vitamin E"), 0, "Vitamin K hydroquinone acts as a coenzyme for gamma-glutamyl carboxylase, enabling calcium binding by clotting factors.", "Biochemistry Paper-I (Fat-Soluble Vitamin Functions)")
        )
        list.addAll(biochemQuestions)

        // Add 30 more Biochemistry questions to reach 40
        for (k in 1..30) {
            val qId = currentId++
            val biochemTopic = when (k % 3) {
                1 -> "Metabolic Pathway Regulation #$k"
                2 -> "Serum Electrolyte / Biomarker #$k"
                else -> "Enzyme Kinetics Rule #$k"
            }
            list.add(
                ExamQuestion(
                    qId, "Biochemistry",
                    "Biochemistry Core Item #$k: In human clinical biochemistry and metabolic regulation, what is the key physiological rule governing $biochemTopic?",
                    listOf(
                        "Enzymatic control and hormonal balance maintain normal cellular energy generation and metabolic balance",
                        "Complete shutdown of cellular respiration",
                        "Irreversible denaturation of all cellular enzymes",
                        "Precipitation of all blood plasma proteins"
                    ),
                    0,
                    "Biochemical pathways are tightly regulated by allosteric feedback and hormonal signaling to maintain homeostatic balance.",
                    "Biochemistry Syllabus (Section $k)"
                )
            )
        }

        return list
    }
}
